import { ImportListResponse } from '../../../../types/imports';

export const mockImportsData: ImportListResponse = {
  data: {
    listAllImportedData: {
      statusCode: 200,
      statusCodeValue: 'Success',
      statusMessage: 'Imports listed successfully',
      data: {
        page: 1,
        limit: 2,
        total_count: 38,
        imports: [
          {
            rid: 'D001-59a6a509-f5fc-47ac-9cc7-5904a478fe73',
            file_name: 'employee_data_q1.csv',
            format: 'CSV',
            size: '1.2 MB',
            fiscal: 2024,
            entity: 'hr',
            total_records: 1200,
            records_loaded_successfully: 1180,
            records_failed_to_load: 20,
            records_with_warning: 10,
            status: 'Completed',
            status_description: 'Imported with minor warnings',
            import_type: 'resource',
            imported_by: 'EMP-789',
            imported_on: '2025-06-01',
          },
          {
            rid: 'D001-59a6a509-f5fc-47ac-9cc7-5904a4732373',
            file_name: 'project_budget.xlsx',
            format: 'Excel',
            size: '2.3 MB',
            fiscal: 2025,
            entity: 'finance',
            total_records: 900,
            records_loaded_successfully: 900,
            records_failed_to_load: 0,
            records_with_warning: 0,
            status: 'Completed',
            status_description: 'All records successfully imported',
            import_type: 'cost',
            imported_by: 'EMP-102',
            imported_on: '2025-06-03',
          },
          {
            rid: 'D001-59a6a509-f5fc-47ac-9cc7-5904a47ww2e3',
            file_name: 'vendor_contacts.json',
            format: 'JSON',
            size: '820 KB',
            fiscal: 2023,
            entity: 'procurement',
            total_records: 300,
            records_loaded_successfully: 280,
            records_failed_to_load: 20,
            records_with_warning: 5,
            status: 'Completed',
            status_description: 'Some records failed to import',
            import_type: 'attachments',
            imported_by: 'EMP-305',
            imported_on: '2025-06-07',
          },
          {
            rid: 'D001-59a6a509-f5fc-47ac-9cc7-5904a4709mnv',
            file_name: 'malformed_data.csv',
            format: 'CSV',
            size: '1.1 MB',
            fiscal: null,
            entity: 'project',
            total_records: null,
            records_loaded_successfully: 0,
            records_failed_to_load: 100,
            records_with_warning: 0,
            status: 'Failed',
            status_description: 'Parsing failed due to malformed rows',
            import_type: 'project',
            imported_by: 'EMP-210',
            imported_on: '2025-06-10',
          },
          {
            rid: 'D001-59a6a509-f5fc-47ac-9cc7-5904a476rvc0',
            file_name: 'resource_skills.csv',
            format: 'CSV',
            size: '950 KB',
            fiscal: 2024,
            entity: 'skills',
            total_records: 500,
            records_loaded_successfully: 500,
            records_failed_to_load: 0,
            records_with_warning: 0,
            status: 'Completed',
            status_description: 'Import successful',
            import_type: 'skill',
            imported_by: 'EMP-112',
            imported_on: '2025-06-15',
          },
        ],
      },
    },
  },
};

export const mockErrorRecordsData = {
  warningRecords: [
    {
      id: '198',
      reason: 'Data Missing',
      description: 'Project Ref Id value is missing',
    },
    {
      id: '289',
      reason: 'Data Missing',
      description: 'Project Ref Id value is missing',
    },
    {
      id: '367',
      reason: 'Data length exceeds max size',
      description: 'Project Name length exceeds max size allowed',
    },
  ],
  failedRecords: [
    {
      id: '498',
      reason: 'Data Missing',
      description: 'Project Ref Id value is missing',
    },
    {
      id: '599',
      reason: 'Invalid Format',
      description: 'Currency code format is incorrect',
    },
  ],
};
