/* eslint-disable @typescript-eslint/no-explicit-any */
export const mockAssignProjects: any[] = [
  {
    _level: 1,
    project_code: 'PRJ-001',
    project_name: 'AI Analytics Dashboard',
    project_type_name: 'Development',
    fiscal_year: 2025,
    classification_name: 'Internal',
    project_classification_other: '',
    project_client_group: 'Enterprise Solutions',
    project_group: 'AI & ML',
    total_effort: 1520.5,
    total_cost: 450000,
    total_cost_fte: 380000,
    total_cost_subcon: 50000,
    total_cost_nonlabor: 20000,
    project_point_of_contact: 'John Doe',
    technical_point_of_contact: 'Alice Smith',
    assessment_status: 'Completed',
    rd_percent_potential_ai: '25%',
    qre: 'QRE-102',
    comments: 'Delivered ahead of schedule.',
    modified_datetime: '2025-09-18T14:23:00Z',
    r_number: 'R-9001',
    currency_symbol: '$',
  },
  {
    _level: 1,
    project_code: 'PRJ-002',
    project_name: 'Cloud Migration Initiative',
    project_type_name: 'Migration',
    fiscal_year: 2024,
    classification_name: 'External',
    project_classification_other: 'Client-Based',
    project_client_group: 'FinTech',
    project_group: 'Cloud Services',
    total_effort: 1870,
    total_cost: 560000,
    total_cost_fte: 480000,
    total_cost_subcon: 60000,
    total_cost_nonlabor: 20000,
    project_point_of_contact: 'Michael Brown',
    technical_point_of_contact: 'Sarah Wilson',
    assessment_status: 'Ongoing',
    rd_percent_potential_ai: '10%',
    qre: 'QRE-204',
    comments: 'Pending client approval for phase 2.',
    modified_datetime: '2025-10-12T10:15:00Z',
    r_number: 'R-9002',
    currency_symbol: '$',
  },
  {
    _level: 1,
    project_code: 'PRJ-003',
    project_name: 'Smart Manufacturing System',
    project_type_name: 'R&D',
    fiscal_year: 2023,
    classification_name: 'Innovation',
    project_classification_other: '',
    project_client_group: 'Industrial Automation',
    project_group: 'IoT & Embedded',
    total_effort: 2250,
    total_cost: 725000,
    total_cost_fte: 600000,
    total_cost_subcon: 100000,
    total_cost_nonlabor: 25000,
    project_point_of_contact: 'Emily Clark',
    technical_point_of_contact: 'Robert Johnson',
    assessment_status: 'In Review',
    rd_percent_potential_ai: '40%',
    qre: 'QRE-303',
    comments: 'Final report under review.',
    modified_datetime: '2025-08-01T09:42:00Z',
    r_number: 'R-9003',
    currency_symbol: '$',
  },
  {
    _level: 2,
    project_code: 'PRJ-003A',
    project_name: 'Phase 1 – Sensor Integration',
    project_type_name: 'Prototype',
    fiscal_year: 2023,
    classification_name: 'Innovation',
    project_classification_other: 'Hardware',
    project_client_group: 'Industrial Automation',
    project_group: 'IoT & Embedded',
    total_effort: 800,
    total_cost: 250000,
    total_cost_fte: 200000,
    total_cost_subcon: 30000,
    total_cost_nonlabor: 20000,
    project_point_of_contact: 'Emily Clark',
    technical_point_of_contact: 'Robert Johnson',
    assessment_status: 'Completed',
    rd_percent_potential_ai: '15%',
    qre: 'QRE-303A',
    comments: 'Sensors integrated successfully.',
    modified_datetime: '2025-07-12T16:05:00Z',
    r_number: 'R-9003A',
    currency_symbol: '$',
  },
];
