export type TimeSheetList = {
  rid: string;
  r_number: string;
  file_name: string;
  format: string;
  size: string;
  fiscal: string | number | null;
  entity: string;
  total_records: number | null;
  records_loaded_successfully: number | null;
  records_failed_to_load: number | null;
  records_with_warning: number | null;
  records_failed_to_stage?: number | null;
  status: string;
  status_descriptions?: string | null;
  import_type?: string | null;
  imported_by: string;
  imported_on: string;
  document_url: string;
};
