import React from 'react';

const icons = {
  accountDetails: () => import('./account-details.svg?react'),
  accountHome: () => import('./account-home.svg?react'),
  accountSettings: () => import('./account-settings.svg?react'),
  accounts: () => import('./accounts.svg?react'),
  accountDetailsIcon: () => import('./accountDetailsIcon.svg?react'),
  activitiesIcon: () => import('./activities-icon.svg?react'),
  action: () => import('./action.svg?react'),
  addicon: () => import('./addicon.svg?react'),
  administration: () => import('./administration.svg?react'),
  adminChevronDown: () => import('./admin-chevron-down.svg?react'),
  adminChevronUp: () => import('./admin-chevron-up.svg?react'),
  adminPermission: () => import('./admin-permission.svg?react'),
  adminSubmenuActive: () => import('./admin-submenu-active.svg?react'),
  adminTemplate: () => import('./admin-template.svg?react'),
  allAccount: () => import('./all-account.svg?react'),
  arrowDown: () => import('./arrow-down.svg?react'),
  arrowIcon: () => import('./arrow-icon.svg?react'),
  arrowUp: () => import('./arrow-up.svg?react'),
  arrowBackIcon: () => import('./arrowBackIcon.svg?react'),
  attachment: () => import('./attachment.svg?react'),
  attachmentsSideIcon: () => import('./attachments-icon.svg?react'),
  burgerMenuIcon: () => import('./burgerMenuIcon.svg?react'),
  calendar: () => import('./calendar.svg?react'),
  case: () => import('./case.svg?react'),
  casesIcon: () => import('./cases-icon.svg?react'),
  checklistIcon: () => import('./checklist-icon.svg?react'),
  checklistTemplate: () => import('./checklist-template.svg?react'),
  checkboxChecked: () => import('./checkboxChecked.svg?react'),
  checkboxUnChecked: () => import('./checkboxUnChecked.svg?react'),
  checkedIcon: () => import('./checked-icon.svg?react'),
  chevronDoubleLeft: () => import('./chevron-double-left.svg?react'),
  chevronDown: () => import('./chevron-down.svg?react'),
  chevronLeft: () => import('./chevron-left.svg?react'),
  childAccount: () => import('./child-account.svg?react'),
  closeCircle: () => import('./close-circle.svg?react'),
  close: () => import('./close.svg?react'),
  comingSoon: () => import('./coming-soon.svg?react'),
  configureSetting: () => import('./configure-setting.svg?react'),
  copyIcon: () => import('./copy-icon.svg?react'),
  createResource: () => import('./create-resource.svg?react'),
  dashboard: () => import('./dashboard.svg?react'),
  deleteIcon: () => import('./delete-icon.svg?react'),
  detailsKeyContactErrorIcon: () =>
    import('./details-key-contact-error-icon.svg?react'),
  detailsIcon: () => import('./details-icon.svg?react'),
  download: () => import('./download.svg?react'),
  edit: () => import('./edit.svg?react'),
  emailTemplate: () => import('./email-template.svg?react'),
  templateImport: () => import('./template-import.svg?react'),
  errorInfoIcon: () => import('./error-info-icon.svg?react'),
  eyeIcon: () => import('./eye-icon.svg?react'),
  filter: () => import('./filter.svg?react'),
  filterArrowRightIcon: () => import('./filterArrowRightIcon.svg?react'),
  financialIcon: () => import('./financial-icon.svg?react'),
  fiscalYearArrowIcon: () => import('./fiscal-year-arrow-icon.svg?react'),
  globe: () => import('./globe.svg?react'),
  help: () => import('./help.svg?react'),
  importTemplate: () => import('./import-template.svg?react'),
  importsIcon: () => import('./imports-icon.svg?react'),
  interactionTemplate: () => import('./interaction-template.svg?react'),
  interactionsIcon: () => import('./interactions-icon.svg?react'),
  keyContactAddIcon: () => import('./key-contact-add-icon.svg?react'),
  keyContactRemoveIcon: () => import('./key-contact-remove-icon.svg?react'),
  leftArrow: () => import('./left-arrow.svg?react'),
  logout: () => import('./logout.svg?react'),
  manageGeo: () => import('./manage-geo.svg?react'),
  manageGroup: () => import('./manage-group.svg?react'),
  manageProfile: () => import('./manage-profile.svg?react'),
  manageSettings: () => import('./manage-settings.svg?react'),
  manageUser: () => import('./manage-user.svg?react'),
  manageConfigSetting: () => import('./manage-config-setting.svg?react'),
  manageUserAccess: () => import('./manage-user-access.svg?react'),
  managerUser: () => import('./manager-user.svg?react'),
  menuArrowRight: () => import('./menu-arrow-right.svg?react'),
  menuArrowRightHover: () => import('./menu-arrow-right-hover.svg?react'),
  menuIcon: () => import('./menu-icon.svg?react'),
  moduleArrowRight: () => import('./module-arrow-right.svg?react'),
  newFilterIcon: () => import('./filter-icon.svg?react'),
  newProject: () => import('./new-project.svg?react'),
  notes: () => import('./notes.svg?react'),
  notesSideIcon: () => import('./notes-icon.svg?react'),
  notification: () => import('./notification.svg?react'),
  phone: () => import('./phone.svg?react'),
  plus: () => import('./plus.svg?react'),
  profile: () => import('./profile.svg?react'),
  projectDetails: () => import('./project-details.svg?react'),
  projects: () => import('./projects.svg?react'),
  projectsSideIcon: () => import('./projects-icon.svg?react'),
  refresh: () => import('./refresh.svg?react'),
  resourceFilterIcon: () => import('./resourceFilterIcon.svg?react'),
  resourceHeader: () => import('./resource-header.svg?react'),
  resourcesIcon: () => import('./resources-icon.svg?react'),
  search: () => import('./search.svg?react'),
  searchBlack: () => import('./search-black.svg?react'),
  settings: () => import('./settings.svg?react'),
  setting: () => import('./setting.svg?react'),
  sortIcon: () => import('./sort-icon.svg?react'),
  survey: () => import('./survey.svg?react'),
  surveyTemplate: () => import('./survey-template.svg?react'),
  taskTemplate: () => import('./task-template.svg?react'),
  techSummaryIcon: () => import('./tech-summary.svg?react'),
  timesheet: () => import('./timesheet.svg?react'),
  timeSheetIcon: () => import('./timesheet-icon.svg?react'),
  user: () => import('./user.svg?react'),
  Vector: () => import('./Vector.svg?react'),
  verticalSeparatorIcon: () => import('./verticalSeparatorIcon.svg?react'),
  tickIcon: () => import('./tick-Icon.svg?react'),
  orgIcon: () => import('./org-icon.svg?react'),
  RejectIcon: () => import('./RejectIcon.svg?react'),
  AcceptIcon: () => import('./AcceptIcon.svg?react'),
  ConfigIcon: () => import('./config-icon.svg?react'),
  ManageGroupIcon: () => import('./Managegroup.svg?react'),
  arrowDownDisabledIcon: () => import('./arrow-down-icon.svg?react'),
  cases: () => import('./cases.svg?react'),
  actionItems: () => import('./action-items.svg?react'),
  dropdownmenuIcon: () => import('./dropdown-menu.svg?react'),
  interactionDetailIcon: () => import('./interaction-detail-icon.svg?react'),
  pdfIcon: () => import('./pdf-icon.svg?react'),
  adminSetting: () => import('./admin-setting.svg?react'),
  documentIcon: () => import('./doc-attachments.svg?react'),
  editTextIcon: () => import('./edit-text-icon.svg?react'),
  gearIcon: () => import('./gear.svg?react'),
  infoIcon: () => import('./info-icon.svg?react'),
  editTaskIcon: () => import('./editTaskIcon.svg?react'),
  pencilIcon: () => import('./PencilIcon.svg?react'),
  commentIcon: () => import('./comment-icon.svg?react'),
  customChecklistIcon: () => import('./ChecklistIcon.svg?react'),
  callLogIcon: () => import('./call-log-icon.svg?react'),
  draftEmailIcon: () => import('./draft-email-icon.svg?react'),
  meetingIcon: () => import('./meeting-icon.svg?react'),
  taskCreateIcon: () => import('./task-create-icon.svg?react'),
  paperclipIcon: () => import('./PaperclipIcon.svg?react'),
  linkTaskIcon: () => import('./link-task.svg?react'),
  expandView: () => import('./expand-view.svg?react'),
  collapseView: () => import('./collapse-view.svg?react'),
  avatarIcon: () => import('./avatar-icon.svg?react'),
  cameraIcon: () => import('./camera-icon.svg?react'),
  swapIcon: () => import('./swap.svg?react'),
  workflowIcon: () => import('./workflow-icon.svg?react'),
  historySubmissionIcon: () => import('./histroy-submission.svg?react'),
  reviewProjectIcon: () => import('./review-project.svg?react'),
  caseTeamIcon: () => import('./case-team.svg?react'),
  configRuleIcon: () => import('./config-rule.svg?react'),
  dossierIcon: () => import('./dossier.svg?react'),
  manageRuleIcon: () => import('./manage-rule.svg?react'),
  projectTaskIcon: () => import('./project-task.svg?react'),
  workBreakdownIcon: () => import('./workbreakdown.svg?react'),
  userIcon: () => import('./usericon.svg?react'),
  manageGroupAccount: () => import('./managegroupaccount.svg?react'),
  notesAdminSideIcon: () => import('./notes-admin-icon.svg?react'),
  attachmentsAdminIcon: () => import('./attachments-admin.svg?react'),
  zoomInIcon: () => import('./zoom-in-icon.svg?react'),
  zoomOutIcon: () => import('./zoom-out-icon.svg?react'),
  dataMapperIcon: () => import('./data-mapper.svg?react'),
  exportIcon: () => import('./export-icon.svg?react'),
  fourPartIcon: () => import('./fpa-icon.svg?react'),
};

function createLazySvgIcon(name: keyof typeof icons) {
  const importer = icons[name];
  return React.lazy(importer);
}

export const AccountDetailsIcon = createLazySvgIcon('accountDetails');
export const AccountHomeIcon = createLazySvgIcon('accountHome');
export const AccountSettingsIcon = createLazySvgIcon('accountSettings');
export const AccountsIcon = createLazySvgIcon('accounts');
export const AccountDeatilsIcon = createLazySvgIcon('accountDetailsIcon');
export const ActionIcon = createLazySvgIcon('action');
export const ActivitiesIcon = createLazySvgIcon('activitiesIcon');
export const AddIcon = createLazySvgIcon('addicon');
export const AdminChevronDownIcon = createLazySvgIcon('adminChevronDown');
export const AdminChevronUpIcon = createLazySvgIcon('adminChevronUp');
export const AdminPermissionIcon = createLazySvgIcon('adminPermission');
export const AdminSubmenuActiveIcon = createLazySvgIcon('adminSubmenuActive');
export const AdminTemplateIcon = createLazySvgIcon('adminTemplate');
export const AdministrationIcon = createLazySvgIcon('administration');
export const AllAccountIcon = createLazySvgIcon('allAccount');
export const ArrowBackIcon = createLazySvgIcon('arrowBackIcon');
export const ArrowDownIcon = createLazySvgIcon('arrowDown');
export const ArrowDownDisabledIcon = createLazySvgIcon('arrowDownDisabledIcon');
export const ArrowIcon = createLazySvgIcon('arrowIcon');
export const ArrowUpIcon = createLazySvgIcon('arrowUp');
export const AttachmentIcon = createLazySvgIcon('attachment');
export const AttachmentsSideIcon = createLazySvgIcon('attachmentsSideIcon');
export const BackIcon = createLazySvgIcon('chevronDoubleLeft');
export const BurgerMenuIcon = createLazySvgIcon('burgerMenuIcon');
export const CalendarIcon = createLazySvgIcon('calendar');
export const CaseIcon = createLazySvgIcon('case');
export const CasesIcon = createLazySvgIcon('casesIcon');
export const ChecklistIcon = createLazySvgIcon('checklistIcon');
export const ChecklistTemplateIcon = createLazySvgIcon('checklistTemplate');
export const CheckboxChecked = createLazySvgIcon('checkboxChecked');
export const CheckboxUnchecked = createLazySvgIcon('checkboxUnChecked');
export const CheckedIcon = createLazySvgIcon('checkedIcon');
export const ChildAccountIcon = createLazySvgIcon('childAccount');
export const ChevronDownIcon = createLazySvgIcon('chevronDown');
export const ChevronLeftIcon = createLazySvgIcon('chevronLeft');
export const CloseCircleIcon = createLazySvgIcon('closeCircle');
export const CloseIcon = createLazySvgIcon('close');
export const ComingSoon = createLazySvgIcon('comingSoon');
export const ConfigureSettingIcon = createLazySvgIcon('configureSetting');
export const CopyIcon = createLazySvgIcon('copyIcon');
export const CreateResourceIcon = createLazySvgIcon('createResource');
export const DashboardIcon = createLazySvgIcon('dashboard');
export const DeleteIcon = createLazySvgIcon('deleteIcon');
export const DetailsIcon = createLazySvgIcon('detailsIcon');
export const DetailsKeyContactErrorIcon = createLazySvgIcon(
  'detailsKeyContactErrorIcon'
);
export const DownloadIcon = createLazySvgIcon('download');
export const TemplateImportIcon = createLazySvgIcon('templateImport');
export const EditIcon = createLazySvgIcon('edit');
export const EmailTemplateIcon = createLazySvgIcon('emailTemplate');
export const ErrorInfoIcon = createLazySvgIcon('errorInfoIcon');
export const EyeIcon = createLazySvgIcon('eyeIcon');
export const FilterArrowRightIcon = createLazySvgIcon('filterArrowRightIcon');
export const FilterIcon = createLazySvgIcon('filter');
export const FinancialIcon = createLazySvgIcon('financialIcon');
export const FiscalYearArrowIcon = createLazySvgIcon('fiscalYearArrowIcon');
export const GlobeIcon = createLazySvgIcon('globe');
export const HelpIcon = createLazySvgIcon('help');
export const ImportTemplateIcon = createLazySvgIcon('importTemplate');
export const ImportsIcon = createLazySvgIcon('importsIcon');
export const InteractionTemplateIcon = createLazySvgIcon('interactionTemplate');
export const InteractionsIcon = createLazySvgIcon('interactionsIcon');
export const KeyContactAddIcon = createLazySvgIcon('keyContactAddIcon');
export const KeyContactRemoveIcon = createLazySvgIcon('keyContactRemoveIcon');
export const LeftArrowIcon = createLazySvgIcon('leftArrow');
export const LogoutIcon = createLazySvgIcon('logout');
export const ManageGeoIcon = createLazySvgIcon('manageGeo');
export const ManageGroupIcon = createLazySvgIcon('manageGroup');
export const ManageProfileIcon = createLazySvgIcon('manageProfile');
export const ManageSettingsIcon = createLazySvgIcon('manageSettings');
export const ManageUserAccessIcon = createLazySvgIcon('manageUserAccess');
export const ManageUserIcon = createLazySvgIcon('manageUser');
export const ManageConfigSettingIcon = createLazySvgIcon('manageConfigSetting');
export const ManagerUserIcon = createLazySvgIcon('managerUser');
export const MenuArrowRight = createLazySvgIcon('menuArrowRight');
export const MenuArrowRightHover = createLazySvgIcon('menuArrowRightHover');
export const MenuIcon = createLazySvgIcon('menuIcon');
export const ModuleArrowRight = createLazySvgIcon('moduleArrowRight');
export const NewFilterIcon = createLazySvgIcon('newFilterIcon');
export const NotesIcon = createLazySvgIcon('notes');
export const NotesSideIcon = createLazySvgIcon('notesSideIcon');
export const NotificationIcon = createLazySvgIcon('notification');
export const PhoneIcon = createLazySvgIcon('phone');
export const PlusIcon = createLazySvgIcon('plus');
export const ProfileIcon = createLazySvgIcon('profile');
export const ProjectCreateIcon = createLazySvgIcon('newProject');
export const ProjectDetailsIcon = createLazySvgIcon('projectDetails');
export const ProjectsIcon = createLazySvgIcon('projects');
export const ProjectsSideIcon = createLazySvgIcon('projectsSideIcon');
export const RefreshIcon = createLazySvgIcon('refresh');
export const ResourceFilterIcon = createLazySvgIcon('resourceFilterIcon');
export const ResourceHeaderIcon = createLazySvgIcon('resourceHeader');
export const ResourcesIcon = createLazySvgIcon('resourcesIcon');
export const SearchBlackIcon = createLazySvgIcon('searchBlack');
export const SearchIcon = createLazySvgIcon('search');
export const SettingsIcon = createLazySvgIcon('settings');
export const SettingIcon = createLazySvgIcon('setting');
export const SortIcon = createLazySvgIcon('sortIcon');
export const SurveyIcon = createLazySvgIcon('survey');
export const SurveyTemplateIcon = createLazySvgIcon('surveyTemplate');
export const TaskTemplateIcon = createLazySvgIcon('taskTemplate');
export const TechSummaryIcon = createLazySvgIcon('techSummaryIcon');
export const TimeSheetIcon = createLazySvgIcon('timeSheetIcon');
export const TimeLineIcon = createLazySvgIcon('timesheet');
export const TickIcon = createLazySvgIcon('tickIcon');
export const UploadIcon = createLazySvgIcon('Vector');
export const UserIcon = createLazySvgIcon('user');
export const VerticalSeparatorIcon = createLazySvgIcon('verticalSeparatorIcon');
export const OrgIcon = createLazySvgIcon('orgIcon');
export const RejectIcon = createLazySvgIcon('RejectIcon');
export const AcceptIcon = createLazySvgIcon('AcceptIcon');
export const ConfigIcon = createLazySvgIcon('ConfigIcon');
export const ManageGroup = createLazySvgIcon('ManageGroupIcon');
export const GlobalCasesIcon = createLazySvgIcon('cases');
export const ActionItemsIcon = createLazySvgIcon('actionItems');
export const DropDownMenuIcon = createLazySvgIcon('dropdownmenuIcon');
export const InteractionDetailIcon = createLazySvgIcon('interactionDetailIcon');
export const PdfIcon = createLazySvgIcon('pdfIcon');
export const AdminSettingIcon = createLazySvgIcon('adminSetting');
export const DocumentIcon = createLazySvgIcon('documentIcon');
export const EditTextIcon = createLazySvgIcon('editTextIcon');
export const GearIcon = createLazySvgIcon('gearIcon');
export const InfoIcon = createLazySvgIcon('infoIcon');
export const EditTaskIcon = createLazySvgIcon('editTaskIcon');
export const PencilIcon = createLazySvgIcon('pencilIcon');
export const CommentIcon = createLazySvgIcon('commentIcon');
export const CustomChecklistIcon = createLazySvgIcon('customChecklistIcon');
export const CallLogIcon = createLazySvgIcon('callLogIcon');
export const DraftEmailIcon = createLazySvgIcon('draftEmailIcon');
export const MeetingIcon = createLazySvgIcon('meetingIcon');
export const TaskCreateIcon = createLazySvgIcon('taskCreateIcon');
export const PaperclipIcon = createLazySvgIcon('paperclipIcon');
export const LinkTaskIcon = createLazySvgIcon('linkTaskIcon');
export const ExpandViewIcon = createLazySvgIcon('expandView');
export const CollapseViewIcon = createLazySvgIcon('collapseView');
export const AvatarIcon = createLazySvgIcon('avatarIcon');
export const CameraIcon = createLazySvgIcon('cameraIcon');
export const SwapIcon = createLazySvgIcon('swapIcon');
export const WorkflowIcon = createLazySvgIcon('workflowIcon');
export const HistorySubmissionIcon = createLazySvgIcon('historySubmissionIcon');
export const ConfigRuleIcon = createLazySvgIcon('configRuleIcon');
export const ReviewProjectIcon = createLazySvgIcon('reviewProjectIcon');
export const CaseTeamIcon = createLazySvgIcon('caseTeamIcon');
export const DossierIcon = createLazySvgIcon('dossierIcon');
export const ManageRule = createLazySvgIcon('manageRuleIcon');
export const ProjectTaskIcon = createLazySvgIcon('projectTaskIcon');
export const WorkBreakdownIcon = createLazySvgIcon('workBreakdownIcon');
export const AccountUserIcon = createLazySvgIcon('userIcon');
export const ManageGroupAccount = createLazySvgIcon('manageGroupAccount');
export const NotesAdminSideIcon = createLazySvgIcon('notesAdminSideIcon');
export const AttachmentsAdminIcon = createLazySvgIcon('attachmentsAdminIcon');
export const ZoomInIcon = createLazySvgIcon('zoomInIcon');
export const ZoomOutIcon = createLazySvgIcon('zoomOutIcon');
export const DataMapperIcon = createLazySvgIcon('dataMapperIcon');
export const ExportIcon = createLazySvgIcon('exportIcon');
export const FourPartIcon = createLazySvgIcon('fourPartIcon');
