import React from 'react';

const icons = {
  'account-details': () => import('./account-details.svg?react'),
  'account-home': () => import('./account-home.svg?react'),
  'account-settings': () => import('./account-settings.svg?react'),
  accounts: () => import('./accounts.svg?react'),
  action: () => import('./action.svg?react'),
  addicon: () => import('./addicon.svg?react'),
  administration: () => import('./administration.svg?react'),
  'admin-chevron-down': () => import('./admin-chevron-down.svg?react'),
  'admin-chevron-up': () => import('./admin-chevron-up.svg?react'),
  'admin-permission': () => import('./admin-permission.svg?react'),
  'admin-submenu-active': () => import('./admin-submenu-active.svg?react'),
  'admin-template': () => import('./admin-template.svg?react'),
  'all-account': () => import('./all-account.svg?react'),
  arrowBackIcon: () => import('./arrowBackIcon.svg?react'),
  'arrow-down': () => import('./arrow-down.svg?react'),
  'arrow-icon': () => import('./arrow-icon.svg?react'),
  'arrow-up': () => import('./arrow-up.svg?react'),
  attachment: () => import('./attachment.svg?react'),
  'chevron-double-left': () => import('./chevron-double-left.svg?react'),
  burgerMenuIcon: () => import('./burgerMenuIcon.svg?react'),
  calendar: () => import('./calendar.svg?react'),
  case: () => import('./case.svg?react'),
  copyIcon: () => import('./copy-icon.svg?react'),
  checkboxChecked: () => import('./checkboxChecked.svg?react'),
  checkboxUnChecked: () => import('./checkboxUnChecked.svg?react'),
  'checked-icon': () => import('./checked-icon.svg?react'),
  'checklist-template': () => import('./checklist-template.svg?react'),
  'chevron-down': () => import('./chevron-down.svg?react'),
  'chevron-left': () => import('./chevron-left.svg?react'),
  'child-account': () => import('./child-account.svg?react'),
  'close-circle': () => import('./close-circle.svg?react'),
  close: () => import('./close.svg?react'),
  'configure-setting': () => import('./configure-setting.svg?react'),
  'create-resource': () => import('./create-resource.svg?react'),
  dashboard: () => import('./dashboard.svg?react'),
  'delete-icon': () => import('./delete-icon.svg?react'),
  'details-key-contact-error-icon': () =>
    import('./details-key-contact-error-icon.svg?react'),
  detailsIcon: () => import('./details-icon.svg?react'),
  download: () => import('./download.svg?react'),
  edit: () => import('./edit.svg?react'),
  'email-template': () => import('./email-template.svg?react'),
  'error-info-icon': () => import('./error-info-icon.svg?react'),
  'eye-icon': () => import('./eye-icon.svg?react'),
  filterArrowRightIcon: () => import('./filterArrowRightIcon.svg?react'),
  filter: () => import('./filter.svg?react'),
  financialIcon: () => import('./financial-icon.svg?react'),
  'fiscal-year-arrow-icon': () => import('./fiscal-year-arrow-icon.svg?react'),
  globe: () => import('./globe.svg?react'),
  help: () => import('./help.svg?react'),
  'import-icon': () => import('./import-icon.svg?react'),
  'import-template': () => import('./import-template.svg?react'),
  'interaction-template': () => import('./interaction-template.svg?react'),
  'key-contact-add-icon': () => import('./key-contact-add-icon.svg?react'),
  'key-contact-remove-icon': () =>
    import('./key-contact-remove-icon.svg?react'),
  'left-arrow': () => import('./left-arrow.svg?react'),
  logo: () => import('./logo.svg?react'),
  'logo-small': () => import('./logo-small.svg?react'),
  logout: () => import('./logout.svg?react'),
  'manage-geo': () => import('./manage-geo.svg?react'),
  'manage-group': () => import('./manage-group.svg?react'),
  'manager-user': () => import('./manager-user.svg?react'),
  'manage-profile': () => import('./manage-profile.svg?react'),
  'manage-settings': () => import('./manage-settings.svg?react'),
  'manage-user-access': () => import('./manage-user-access.svg?react'),
  'manage-user': () => import('./manage-user.svg?react'),
  resourcesIcon: () => import('./resources-icon.svg?react'),
  projectsSideIcon: () => import('./projects-icon.svg?react'),
  casesIcon: () => import('./cases-icon.svg?react'),
  activitiesIcon: () => import('./activities-icon.svg?react'),
  notesSideIcon: () => import('./notes-icon.svg?react'),
  checklistIcon: () => import('./checklist-icon.svg?react'),
  timeSheetIcon: () => import('./timesheet-icon.svg?react'),
  importsIcon: () => import('./imports-icon.svg?react'),
  attachmentsSideIcon: () => import('./attachments-icon.svg?react'),
  comingSoon: () => import('./coming-soon.svg?react'),
  interactionsIcon: () => import('./interactions-icon.svg?react'),
  techSummaryIcon: () => import('./tech-summary.svg?react'),
  'menu-arrow-right': () => import('./menu-arrow-right.svg?react'),
  'menu-arrow-right-hover': () => import('./menu-arrow-right-hover.svg?react'),
  'menu-icon': () => import('./menu-icon.svg?react'),
  'module-arrow-right': () => import('./module-arrow-right.svg?react'),
  'filter-icon': () => import('./filter-icon.svg?react'),
  notes: () => import('./notes.svg?react'),
  notification: () => import('./notification.svg?react'),
  phone: () => import('./phone.svg?react'),
  plus: () => import('./plus.svg?react'),
  profile: () => import('./profile.svg?react'),
  'new-project': () => import('./new-project.svg?react'),
  'project-details': () => import('./project-details.svg?react'),
  'projects-header': () => import('./projects-header.svg?react'),
  'project-book': () => import('./project-book.svg?react'),
  projects: () => import('./projects.svg?react'),
  'related-list-details-icon': () =>
    import('./related-list-details-icon.svg?react'),
  refresh: () => import('./refresh.svg?react'),
  resourceFilterIcon: () => import('./resourceFilterIcon.svg?react'),
  'resource-header': () => import('./resource-header.svg?react'),
  resourceProfileIcon: () => import('./resourceProfileIcon.svg?react'),
  'search-black': () => import('./search-black.svg?react'),
  search: () => import('./search.svg?react'),
  settings: () => import('./settings.svg?react'),
  'sort-icon': () => import('./sort-icon.svg?react'),
  survey: () => import('./survey.svg?react'),
  'survey-template': () => import('./survey-template.svg?react'),
  'task-template': () => import('./task-template.svg?react'),
  timesheet: () => import('./timesheet.svg?react'),
  Vector: () => import('./Vector.svg?react'),
  user: () => import('./user.svg?react'),
  verticalSeparatorIcon: () => import('./verticalSeparatorIcon.svg?react'),
};

function createLazySvgIcon(name: keyof typeof icons) {
  const importer = icons[name];
  return React.lazy(importer);
}

export const TechSummaryIcon = createLazySvgIcon('techSummaryIcon');
export const InteractionsIcon = createLazySvgIcon('interactionsIcon');
export const ComingSoon = createLazySvgIcon('comingSoon');
export const AttachmentsSideIcon = createLazySvgIcon('attachmentsSideIcon');
export const ImportsIcon = createLazySvgIcon('importsIcon');
export const TimeSheetIcon = createLazySvgIcon('timeSheetIcon');
export const ChecklistIcon = createLazySvgIcon('checklistIcon');
export const NotesSideIcon = createLazySvgIcon('notesSideIcon');
export const ActivitiesIcon = createLazySvgIcon('activitiesIcon');
export const CasesIcon = createLazySvgIcon('casesIcon');
export const ProjectsSideIcon = createLazySvgIcon('projectsSideIcon');
export const ResourcesIcon = createLazySvgIcon('resourcesIcon');
export const AccountDetailsIcon = createLazySvgIcon('account-details');
export const AccountHomeIcon = createLazySvgIcon('account-home');
export const AccountSettingsIcon = createLazySvgIcon('account-settings');
export const AccountsIcon = createLazySvgIcon('accounts');
export const ActionIcon = createLazySvgIcon('action');
export const AddIcon = createLazySvgIcon('addicon');
export const AdministrationIcon = createLazySvgIcon('administration');
export const AdminChevronDownIcon = createLazySvgIcon('admin-chevron-down');
export const AdminChevronUpIcon = createLazySvgIcon('admin-chevron-up');
export const AdminPermissionIcon = createLazySvgIcon('admin-permission');
export const AdminSubmenuActiveIcon = createLazySvgIcon('admin-submenu-active');
export const AdminTemplateIcon = createLazySvgIcon('admin-template');
export const AllAccountIcon = createLazySvgIcon('all-account');
export const ArrowBackIcon = createLazySvgIcon('arrowBackIcon');
export const ArrowDownIcon = createLazySvgIcon('arrow-down');
export const ArrowIcon = createLazySvgIcon('arrow-icon');
export const ArrowUpIcon = createLazySvgIcon('arrow-up');
export const AttachmentIcon = createLazySvgIcon('attachment');
export const BackIcon = createLazySvgIcon('chevron-double-left');
export const BurgerMenuIcon = createLazySvgIcon('burgerMenuIcon');
export const CalendarIcon = createLazySvgIcon('calendar');
export const CaseIcon = createLazySvgIcon('case');
export const CopyIcon = createLazySvgIcon('copyIcon');
export const CheckboxChecked = createLazySvgIcon('checkboxChecked');
export const CheckboxUnchecked = createLazySvgIcon('checkboxUnChecked');
export const CheckedIcon = createLazySvgIcon('checked-icon');
export const ChecklistTemplateIcon = createLazySvgIcon('checklist-template');
export const ChevronDownIcon = createLazySvgIcon('chevron-down');
export const ChevronLeftIcon = createLazySvgIcon('chevron-left');
export const ChildAccountIcon = createLazySvgIcon('child-account');
export const CloseCircleIcon = createLazySvgIcon('close-circle');
export const CloseIcon = createLazySvgIcon('close');
export const ConfigureSettingIcon = createLazySvgIcon('configure-setting');
export const CreateResourceIcon = createLazySvgIcon('create-resource');
export const DashboardIcon = createLazySvgIcon('dashboard');
export const DeleteIcon = createLazySvgIcon('delete-icon');
export const DetailsKeyContactErrorIcon = createLazySvgIcon(
  'details-key-contact-error-icon'
);
export const DetailsIcon = createLazySvgIcon('detailsIcon');
export const DownloadIcon = createLazySvgIcon('download');
export const EditIcon = createLazySvgIcon('edit');
export const EmailTemplateIcon = createLazySvgIcon('email-template');
export const ErrorInfoIcon = createLazySvgIcon('error-info-icon');
export const EyeIcon = createLazySvgIcon('eye-icon');
export const FilterArrowRightIcon = createLazySvgIcon('filterArrowRightIcon');
export const FilterIcon = createLazySvgIcon('filter');
export const FinancialIcon = createLazySvgIcon('financialIcon');
export const FiscalYearArrowIcon = createLazySvgIcon('fiscal-year-arrow-icon');
export const GlobeIcon = createLazySvgIcon('globe');
export const HelpIcon = createLazySvgIcon('help');
export const ImportIcon = createLazySvgIcon('import-icon');
export const ImportTemplateIcon = createLazySvgIcon('import-template');
export const InteractionTemplateIcon = createLazySvgIcon(
  'interaction-template'
);
export const KeyContactAddIcon = createLazySvgIcon('key-contact-add-icon');
export const KeyContactRemoveIcon = createLazySvgIcon(
  'key-contact-remove-icon'
);
export const LeftArrowIcon = createLazySvgIcon('left-arrow');
export const Logo = createLazySvgIcon('logo');
export const LogoSmall = createLazySvgIcon('logo-small');
export const LogoutIcon = createLazySvgIcon('logout');
export const ManageGeoIcon = createLazySvgIcon('manage-geo');
export const ManageGroupIcon = createLazySvgIcon('manage-group');
export const ManagerUserIcon = createLazySvgIcon('manager-user');
export const ManageProfileIcon = createLazySvgIcon('manage-profile');
export const ManageSettingsIcon = createLazySvgIcon('manage-settings');
export const ManageUserAccessIcon = createLazySvgIcon('manage-user-access');
export const ManageUserIcon = createLazySvgIcon('manage-user');
export const MenuArrowRight = createLazySvgIcon('menu-arrow-right');
export const MenuArrowRightHover = createLazySvgIcon('menu-arrow-right-hover');
export const MenuIcon = createLazySvgIcon('menu-icon');
export const ModuleArrowRight = createLazySvgIcon('module-arrow-right');
export const NewFilterIcon = createLazySvgIcon('filter-icon');
export const NotesIcon = createLazySvgIcon('notes');
export const NotificationIcon = createLazySvgIcon('notification');
export const PhoneIcon = createLazySvgIcon('phone');
export const PlusIcon = createLazySvgIcon('plus');
export const ProfileIcon = createLazySvgIcon('profile');
export const ProjectCreateIcon = createLazySvgIcon('new-project');
export const ProjectDetailsIcon = createLazySvgIcon('project-details');
export const ProjectHeaderIcon = createLazySvgIcon('projects-header');
export const ProjectsBook = createLazySvgIcon('project-book');
export const ProjectsIcon = createLazySvgIcon('projects');
export const RealatedListDetailsIcon = createLazySvgIcon(
  'related-list-details-icon'
);
export const RefreshIcon = createLazySvgIcon('refresh');
export const ResourceFilterIcon = createLazySvgIcon('resourceFilterIcon');
export const ResourceHeaderIcon = createLazySvgIcon('resource-header');
export const ResourceProfileIcon = createLazySvgIcon('resourceProfileIcon');
export const SearchBlackIcon = createLazySvgIcon('search-black');
export const SearchIcon = createLazySvgIcon('search');
export const SettingsIcon = createLazySvgIcon('settings');
export const SortIcon = createLazySvgIcon('sort-icon');
export const SurveyIcon = createLazySvgIcon('survey');
export const SurveyTemplateIcon = createLazySvgIcon('survey-template');
export const TaskTemplateIcon = createLazySvgIcon('task-template');
export const TimesheetIcon = createLazySvgIcon('timesheet');
export const UploadIcon = createLazySvgIcon('Vector');
export const UserIcon = createLazySvgIcon('user');
export const VerticalSeparatorIcon = createLazySvgIcon('verticalSeparatorIcon');
