import { InteractionDetails, InteractionListResponse } from '../../../../types';

export const mockInteractionList: InteractionListResponse = {
  statusCode: 200,
  statusMessage: 'Interaction fetched successfully',
  data: {
    page: 1,
    limit: 10,
    totalRecords: 4,
    interactions: [
      {
        rid: 'D001-0001',
        r_number: 'INT-0001',
        iteration: 1,
        interaction_age: 3,
        status: { rid: 'S001', status_name: 'Draft' },
        recipient_details: {
          rid: 'R001',
          recipient_name: 'John Doe',
          recipient_email: 'john.doe@example.com',
        },
        last_sent_on: '2025-06-25 17:02:44+00',
        last_reminder_on: '2025-06-27 09:15:00+00',
        response_submitted_on: '',
        response_updated_on: '',
        attachments: 2,
        interaction_url: 'https://example.com/interactions/INT-0001',
        interaction_history: 'H001',
        parent_interaction_rid: '',
        interaction_type: {
          rid: 'T001',
          type_name: 'Auto',
        },
        response_source: 'Email',
        created_by: {
          rid: 'U001',
          created_by_user_name: 'System',
        },
        created_datetime: '2025-06-25 17:02:44+00',
        modified_by: {
          rid: 'U002',
          modified_by_user_name: 'Admin',
        },
        modified_datetime: '2025-06-27 09:15:00+00',
        account_rid: 'A001',
        project_fiscal_rid: 'PF001',
        fiscal_year: 2024,
      },
      {
        rid: 'D001-0002',
        r_number: 'INT-0002',
        iteration: 2,
        interaction_age: 10,
        status: { rid: 'S002', status_name: 'Response Draft' },
        recipient_details: {
          rid: 'R002',
          recipient_name: 'Jane Smith',
          recipient_email: 'jane.smith@example.com',
        },
        last_sent_on: '2025-05-20 14:30:00+00',
        last_reminder_on: '2025-05-22 10:00:00+00',
        response_submitted_on: '2025-05-25 09:45:00+00',
        response_updated_on: '2025-05-26 08:15:00+00',
        attachments: 1,
        interaction_url: 'https://example.com/interactions/INT-0002',
        interaction_history: 'H002',
        parent_interaction_rid: 'D001-0001',
        interaction_type: {
          rid: 'T002',
          type_name: 'Manual',
        },
        response_source: 'Portal',
        created_by: {
          rid: 'U002',
          created_by_user_name: 'Admin',
        },
        created_datetime: '2025-05-20 14:30:00+00',
        modified_by: {
          rid: 'U002',
          modified_by_user_name: 'Admin',
        },
        modified_datetime: '2025-05-26 08:15:00+00',
        account_rid: 'A002',
        project_fiscal_rid: 'PF002',
        fiscal_year: 2024,
      },
      {
        rid: 'D001-0003',
        r_number: 'INT-0003',
        iteration: 1,
        interaction_age: 5,
        status: { rid: 'S003', status_name: 'Cancelled' },
        recipient_details: {
          rid: 'R003',
          recipient_name: 'Bob Lee',
          recipient_email: 'bob.lee@example.com',
        },
        last_sent_on: '2025-06-10 08:00:00+00',
        last_reminder_on: '',
        response_submitted_on: '',
        response_updated_on: '',
        attachments: 0,
        interaction_url: 'https://example.com/interactions/INT-0003',
        interaction_history: 'H003',
        parent_interaction_rid: '',
        interaction_type: {
          rid: 'T001',
          type_name: 'Auto',
        },
        response_source: 'SMS',
        created_by: {
          rid: 'U001',
          created_by_user_name: 'System',
        },
        created_datetime: '2025-06-10 08:00:00+00',
        modified_by: {
          rid: 'U001',
          modified_by_user_name: 'System',
        },
        modified_datetime: '2025-06-11 12:00:00+00',
        account_rid: 'A003',
        project_fiscal_rid: 'PF003',
        fiscal_year: 2025,
      },
      {
        rid: 'D001-0004',
        r_number: 'INT-0004',
        iteration: 3,
        interaction_age: 15,
        status: { rid: 'S004', status_name: 'Completed' },
        recipient_details: {
          rid: 'R004',
          recipient_name: 'Alice Brown',
          recipient_email: 'alice.brown@example.com',
        },
        last_sent_on: '2025-04-01 11:15:00+00',
        last_reminder_on: '2025-04-05 09:00:00+00',
        response_submitted_on: '2025-04-06 13:45:00+00',
        response_updated_on: '2025-04-07 15:30:00+00',
        attachments: 3,
        interaction_url: 'https://example.com/interactions/INT-0004',
        interaction_history: 'H004',
        parent_interaction_rid: 'D001-0002',
        interaction_type: {
          rid: 'T002',
          type_name: 'Manual',
        },
        response_source: 'Email',
        created_by: {
          rid: 'U003',
          created_by_user_name: 'Manager',
        },
        created_datetime: '2025-04-01 11:15:00+00',
        modified_by: {
          rid: 'U003',
          modified_by_user_name: 'Manager',
        },
        modified_datetime: '2025-04-07 15:30:00+00',
        account_rid: 'A004',
        project_fiscal_rid: 'PF004',
        fiscal_year: 2023,
      },
    ],
  },
};

export const mockInteractionDetailsMap: Record<string, InteractionDetails> = {
  'D001-0001': {
    r_number: 'INT-0001',
    rid: 'D001-0001',
    account_name: 'Zoho-UK',
    project_name: 'CRM-Zoho-UK',
    project_code: 'CRM-768210',
    fiscal_year: 2024,
    interaction_type: 'Auto',
    status: 'Draft',
    response_updated_by: '',
    response_received_on: '',
    created_on: '2025-06-25',
    created_by: 'System',
    updated_on: '2025-06-27',
    updated_by: 'Admin',
    questions: [
      {
        question_id: 'Q001',
        rid: 'D001-0001',
        question:
          'Describe the key advancement in technology you sought to achieve.',
        answer: 'Initial draft pending review.',
        response_received_on: '',
        notes: 'This is a system-generated draft awaiting recipient feedback.',
        mandatory: true,
        attachments: [
          {
            file_id: 'f001',
            file_name: 'initial_brief.pdf',
            file_url: 'https://example.com/files/initial_brief.pdf',
          },
          {
            file_id: 'f002',
            file_name: 'requirements.docx',
            file_url: 'https://example.com/files/requirements.docx',
          },
        ],
      },
    ],
  },

  'D001-0002': {
    r_number: 'INT-0002',
    rid: 'D001-0002',
    account_name: 'Zoho-UK',
    project_name: 'CRM-Zoho-UK',
    project_code: 'CRM-768210',
    fiscal_year: 2024,
    interaction_type: 'Manual',
    status: 'Response Draft',
    response_updated_by: 'Admin',
    response_received_on: '2025-05-25',
    created_on: '2025-05-20',
    created_by: 'Admin',
    updated_on: '2025-05-26',
    updated_by: 'Admin',
    questions: [
      {
        question_id: 'Q002',
        rid: 'D001-0002',
        question: 'Was the compliance report submitted?',
        answer: 'Yes, submitted via portal',
        response_received_on: '2025-05-25',
        notes: 'Report submitted ahead of deadline; awaiting approval.',
        mandatory: true,
        attachments: [
          {
            file_id: 'f003',
            file_name: 'compliance_report.pdf',
            file_url: 'https://example.com/files/compliance_report.pdf',
          },
        ],
      },
    ],
  },

  'D001-0003': {
    r_number: 'INT-0003',
    rid: 'D001-0003',
    account_name: 'Zoho-UK',
    project_name: 'CRM-Zoho-UK',
    project_code: 'CRM-768210',
    fiscal_year: 2025,
    interaction_type: 'Auto',
    status: 'Cancelled',
    response_updated_by: '',
    response_received_on: '',
    created_on: '2025-06-10',
    created_by: 'System',
    updated_on: '2025-06-11',
    updated_by: 'System',
    questions: [],
  },

  'D001-0004': {
    r_number: 'INT-0004',
    rid: 'D001-0004',
    account_name: 'Zoho-US',
    project_name: 'CRM-Zoho-US',
    project_code: 'CRM-998877',
    fiscal_year: 2023,
    interaction_type: 'Manual',
    status: 'Completed',
    response_updated_by: 'Manager',
    response_received_on: '2025-04-06',
    created_on: '2025-04-01',
    created_by: 'Manager',
    updated_on: '2025-04-07',
    updated_by: 'Manager',
    questions: [
      {
        question_id: 'Q003',
        rid: 'D001-0004',
        question: 'Summarize the key outcomes of the completed interaction.',
        answer:
          'All deliverables were met, and the client confirmed satisfaction.',
        response_received_on: '2025-04-06',
        notes: 'Follow-up scheduled for next fiscal year.',
        mandatory: false,
        attachments: [
          {
            file_id: 'f004',
            file_name: 'final_report.pdf',
            file_url: 'https://example.com/files/final_report.pdf',
          },
          {
            file_id: 'f005',
            file_name: 'client_feedback.docx',
            file_url: 'https://example.com/files/client_feedback.docx',
          },
          {
            file_id: 'f006',
            file_name: 'presentation.pptx',
            file_url: 'https://example.com/files/presentation.pptx',
          },
        ],
      },
    ],
  },
};
