import { formatDateToYYYYMMDDWithTime } from '../../../../../common-utils';
import { ListTableColumn } from '../../../../../components/table/types';
import { TaskList } from '../../../../types/task';

export const getTaskTableColumns = (
  permissionMap?: Record<string, { read: boolean; edit: boolean }>
): ListTableColumn<TaskList>[] => [
  {
    id: 'task_id',
    sortId: 'task_id',
    label: 'Task ID',
    width: 140,
    sortable: true,
    sticky: true,
    hide: !permissionMap?.['task_id']?.read,
    sx: {
      position: 'sticky',
      left: 0,
      background: '#fff',
      zIndex: 10,
      borderRight: '1px solid #CBD6E2 !important',
      borderBottom: '1px solid #CBD6E2 !important',
    },
  },
  {
    id: 'task_name',
    sortId: 'task_name',
    label: 'Task Name',
    width: 250,
    sortable: true,
    hide: !permissionMap?.['task_name']?.read,
  },
  {
    id: 'task_description',
    sortId: 'task_description',
    label: 'Task Description',
    width: 300,
    sortable: true,
    hide: !permissionMap?.['task_description']?.read,
    render: (row: TaskList) => row.task_description || '-',
  },
  {
    id: 'fiscal_year',
    sortId: 'fiscal_year',
    label: 'Fiscal Year',
    width: 140,
    sortable: true,
    hide: !permissionMap?.['fiscal_year']?.read,
    render: (row: TaskList) => `FY-${row.fiscal_year}`,
  },
  {
    id: 'assignee',
    sortId: 'assignee',
    label: 'Assignee',
    width: 180,
    sortable: true,
    hide: !permissionMap?.['assignee']?.read,
    render: (row: TaskList) => row.assignee || '-',
  },
  {
    id: 'priority',
    sortId: 'priority',
    label: 'Priority',
    width: 120,
    sortable: true,
    hide: !permissionMap?.['priority']?.read,
    render: (row: TaskList) => row.priority || '-',
  },
  {
    id: 'status',
    sortId: 'status',
    label: 'Status',
    width: 140,
    sortable: true,
    hide: !permissionMap?.['status']?.read,
  },
  {
    id: 'related_entity',
    sortId: 'related_entity',
    label: 'Related Entity',
    width: 150,
    sortable: true,
    hide: !permissionMap?.['related_entity']?.read,
    render: (row: TaskList) => row.related_entity || '-',
  },
  {
    id: 'related_to_id',
    sortId: 'related_to_id',
    label: 'Related To ID',
    width: 180,
    sortable: true,
    hide: !permissionMap?.['related_to_id']?.read,
    render: (row: TaskList) => row.related_to_id || '-',
  },
  {
    id: 'related_to_name',
    sortId: 'related_to_name',
    label: 'Related To Name',
    width: 200,
    sortable: true,
    hide: !permissionMap?.['related_to_name']?.read,
    render: (row: TaskList) => row.related_to_name || '-',
  },
  {
    id: 'created_by',
    sortId: 'created_by',
    label: 'Created By',
    width: 180,
    sortable: true,
    hide: !permissionMap?.['created_by']?.read,
  },
  {
    id: 'created_on',
    sortId: 'created_on',
    label: 'Created On',
    width: 200,
    sortable: true,
    hide: !permissionMap?.['created_on']?.read,
    render: (row: TaskList) => formatDateToYYYYMMDDWithTime(row.created_on),
  },
  {
    id: 'modified_by',
    sortId: 'modified_by',
    label: 'Modified By',
    width: 180,
    sortable: true,
    hide: !permissionMap?.['modified_by']?.read,
    render: (row: TaskList) => row.modified_by || '-',
  },
  {
    id: 'modified_on',
    sortId: 'modified_on',
    label: 'Modified On',
    width: 200,
    sortable: true,
    hide: !permissionMap?.['modified_on']?.read,
    render: (row: TaskList) =>
      row.modified_on ? formatDateToYYYYMMDDWithTime(row.modified_on) : '-',
  },
];
