import { InteractionDetails, InteractionListResponse } from '../../../../types';

export const mockInteractionList: InteractionListResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: '',
  data: {
    interactions: [
      {
        rid: 'a1b2c3d4e5-0001',
        r_number: 'INT-0001',
        iteration: 1,
        age_days: 5,
        status: 'Created',
        recipient_name: 'John Doe',
        recipient_email: 'john.doe@example.com',
        last_sent_date: '2024-05-01',
        last_reminder_date: '2024-05-04',
        response_date: '',
        last_response_update: '',
        attachments: '2 files',
        interaction_history: 'View History',
        interaction_link: 'https://example.com/interactions/INT-0001',
        parent_interaction_id: '',
        type: 'Auto',
        response_source: 'Email',
        created_by: 'System',
        created_date: '2024-05-01',
        last_updated_by: 'Admin',
        last_updated_date: '2024-05-04',
      },
      {
        rid: 'a1b2c3d4e5-0002',
        r_number: 'INT-0002',
        iteration: 2,
        age_days: 10,
        status: 'Response Draft',
        recipient_name: 'Jane Smith',
        recipient_email: 'jane.smith@example.com',
        last_sent_date: '2024-04-20',
        last_reminder_date: '2024-04-25',
        response_date: '2024-04-28',
        last_response_update: '2024-04-29',
        attachments: '1 file',
        interaction_history: 'View History',
        interaction_link: 'https://example.com/interactions/INT-0002',
        parent_interaction_id: 'INT-0001',
        type: 'Manual',
        response_source: 'Portal',
        created_by: 'Admin',
        created_date: '2024-04-20',
        last_updated_by: 'Admin',
        last_updated_date: '2024-04-29',
      },
      {
        rid: 'a1b2c3d4e5-0003',
        r_number: 'INT-0003',
        iteration: 1,
        age_days: 3,
        status: 'Cancelled',
        recipient_name: 'Bob Lee',
        recipient_email: 'bob.lee@example.com',
        last_sent_date: '2024-06-10',
        last_reminder_date: '',
        response_date: '',
        last_response_update: '',
        attachments: '0 files',
        interaction_history: 'View History',
        interaction_link: 'https://example.com/interactions/INT-0003',
        parent_interaction_id: '',
        type: 'Auto',
        response_source: 'SMS',
        created_by: 'System',
        created_date: '2024-06-10',
        last_updated_by: 'System',
        last_updated_date: '2024-06-11',
      },
    ],
    count: 3,
  },
};

export const mockInteractionDetailsMap: Record<string, InteractionDetails> = {
  'a1b2c3d4e5-0001': {
    r_number: 'INT-0001',
    rid: 'a1b2c3d4e5-0001',
    account_name: 'Zoho-UK',
    project_name: 'CRM-Zoho-UK',
    project_code: 'CRM-768210',
    fiscal_year: 2024,
    interaction_type: 'Auto',
    status: 'Created',
    response_updated_by: '',
    response_received_on: '',
    created_on: '2024-05-01',
    created_by: 'System',
    updated_on: '2024-05-04',
    updated_by: 'Admin',
    questions: [
      {
        question_id: 'Q001',
        rid: 'a1b2c3d4e5-0001',
        question:
          'What advancement in technology is being sought, what were the problems or challenges that you could not solve using commonly available tools and or resource experience that required you to seek an advance in the underlying technology to achieve the objective, or what was the new scientific knowledge sought in your work?',
        answer:
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
        response_received_on: '2024-04-28',
        notes:
          'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, doloremque. Vero, nam hic. Soluta culpa possimus similique impedit a eos.',
        mandatory: true,
        attachments: [
          {
            file_id: 'f001',
            file_name: 'status_report.pdf',
            file_url: 'https://example.com/files/status_report.pdf',
          },
          {
            file_id: 'f002',
            file_name: 'summary.docx',
            file_url: 'https://example.com/files/summary.docx',
          },
        ],
      },
      {
        question_id: 'Q002',
        rid: 'a1b2c3d4e5-0002',
        question: 'What is the project status?',
        answer: '',
        response_received_on: '',
        notes:
          'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, doloremque. Vero, nam hic. Soluta culpa possimus similique impedit a eos.',
        mandatory: false,
        attachments: [],
      },
    ],
  },

  'a1b2c3d4e5-0002': {
    r_number: 'INT-0002',
    rid: 'a1b2c3d4e5-0002',
    account_name: 'Zoho-UK',
    project_name: 'CRM-Zoho-UK',
    project_code: 'CRM-768210',
    fiscal_year: 2024,
    interaction_type: 'Manual',
    status: 'Response Draft',
    response_updated_by: 'Admin',
    response_received_on: '2024-04-28',
    created_on: '2024-04-20',
    created_by: 'Admin',
    updated_on: '2024-04-29',
    updated_by: 'Admin',
    questions: [
      {
        question_id: 'Q002',
        rid: 'a1b2c3d4e5-0002',
        question: 'Was the compliance report submitted?',
        answer: 'Yes, submitted via portal',
        response_received_on: '2024-04-28',
        notes:
          'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta, doloremque. Vero, nam hic. Soluta culpa possimus similique impedit a eos.',
        mandatory: true,
        attachments: [
          {
            file_id: 'f003',
            file_name: 'compliance.pdf',
            file_url: 'https://example.com/files/compliance.pdf',
          },
        ],
      },
    ],
  },

  'a1b2c3d4e5-0003': {
    r_number: 'INT-0003',
    rid: 'a1b2c3d4e5-0003',
    account_name: 'Zoho-UK',
    project_name: 'CRM-Zoho-UK',
    project_code: 'CRM-768210',
    fiscal_year: 2024,
    interaction_type: 'Auto',
    status: 'Cancelled',
    response_updated_by: '',
    response_received_on: '',
    created_on: '2024-06-10',
    created_by: 'System',
    updated_on: '2024-06-11',
    updated_by: 'System',
    questions: [],
  },
};
