from pydantic_settings import BaseSettings
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from constants import Constants
from typing import Optional
import os
from dotenv import load_dotenv

load_dotenv()  # Explicitly load .env file
class Settings(BaseSettings):
    # Defaults (can be overridden by env or Key Vault)
    ENTITY_DB_NAME: str = ""
    ENTITY_DB_USER: str = ""
    ENTITY_DB_PASS: str = ""
    ENTITY_DB_HOST: str = ""
    AZURE_STORAGE_CONNECTION_STRING: str = ""
    KEY_VAULT_URI: Optional[str] = None
    MAIN_DB_NAME: str = ""
    MAIN_DB_USER: str = ""
    MAIN_DB_PASSWORD: str = ""
    MAIN_DB_HOST: str = ""
    TENANT_ID: str = ""
    CLIENT_ID: str = ""
    CLIENT_SECRET: str = ""
    EMAIL_FROM: str = ""

    class Config:
        env_file = ".env"
        env_file_encoding = 'utf-8'
        extra = 'ignore'

    def load_secrets_from_keyvault(self):
        if not self.KEY_VAULT_URI:
            print("[Config] KEY_VAULT_URI not set — loading credentials directly from environment variables")
            self.ENTITY_DB_NAME = os.getenv("ORGDB_NAME", "")
            self.ENTITY_DB_USER = os.getenv("ORGDB_USERNAME", "")
            self.ENTITY_DB_PASS = os.getenv("ORGDB_PASSWORD", "")
            self.ENTITY_DB_HOST = os.getenv("ORGDB_ENDPOINT", "")
            self.AZURE_STORAGE_CONNECTION_STRING = os.getenv("AZURE_STORAGE_CONNECTION_STRING", "")
            self.MAIN_DB_NAME = os.getenv("MAINDB_NAME", "")
            self.MAIN_DB_USER = os.getenv("MAINDB_USERNAME", "")
            self.MAIN_DB_PASSWORD = os.getenv("MAINDB_PASSWORD", "")
            self.MAIN_DB_HOST = os.getenv("MAINDB_ENDPOINT", "")
            self.TENANT_ID = os.getenv("MAIL_TENANT_ID", "")
            self.CLIENT_ID = os.getenv("MAIL_CLIENT_ID", "")
            self.CLIENT_SECRET = os.getenv("MAIL_CLIENT_SECRET", "")
            self.EMAIL_FROM = os.getenv("EMAIL_FROM", "")
            return
        try:
            credential = DefaultAzureCredential()
            client = SecretClient(vault_url=self.KEY_VAULT_URI, credential=credential)
            self.ENTITY_DB_NAME = client.get_secret(os.getenv("ORGDB_NAME")).value
            self.ENTITY_DB_USER = client.get_secret(os.getenv("ORGDB_USERNAME")).value
            self.ENTITY_DB_PASS = client.get_secret(os.getenv("ORGDB_PASSWORD")).value
            self.ENTITY_DB_HOST = client.get_secret(os.getenv("ORGDB_ENDPOINT")).value
            self.AZURE_STORAGE_CONNECTION_STRING = client.get_secret(os.getenv("AZURE_STORAGE_CONNECTION_STRING")).value
            self.MAIN_DB_NAME = client.get_secret(os.getenv("MAINDB_NAME")).value
            self.MAIN_DB_USER = client.get_secret(os.getenv("MAINDB_USERNAME")).value
            self.MAIN_DB_PASSWORD = client.get_secret(os.getenv("MAINDB_PASSWORD")).value
            self.MAIN_DB_HOST = client.get_secret(os.getenv("MAINDB_ENDPOINT")).value
            self.TENANT_ID = client.get_secret(os.getenv("MAIL_TENANT_ID")).value
            self.CLIENT_ID = client.get_secret(os.getenv("MAIL_CLIENT_ID")).value
            self.CLIENT_SECRET = client.get_secret(os.getenv("MAIL_CLIENT_SECRET")).value
            self.EMAIL_FROM = client.get_secret(os.getenv("EMAIL_FROM")).value

        except Exception as e:
            print(f"[Key Vault] Failed to load secrets: {str(e)}")
            print("[Key Vault] Falling back to environment variables (if available)")


# Load secrets on startup
settings = Settings()
settings.load_secrets_from_keyvault()


class Config:
    # Kafka Configuration
    KAFKA_BROKER = Constants.KAFKA_BROKER
    KAFKA_TOPIC_RESOURCE = Constants.KAFKA_TOPIC_RESOURCE
    KAFKA_TOPIC_RESOURCE_COST = Constants.KAFKA_TOPIC_RESOURCE_COST
    KAFKA_TOPIC_RESOURCE_SKILL = Constants.KAFKA_TOPIC_RESOURCE_SKILL
    KAFKA_TOPIC_PROJECT = Constants.KAFKA_TOPIC_PROJECT
    KAFKA_TOPIC_PROJECT_RESOURCE = Constants.KAFKA_TOPIC_PROJECT_RESOURCE
    KAFKA_TOPIC_PROJECT_TASK = Constants.KAFKA_TOPIC_PROJECT_TASK

    KAFKA_OUTPUT_TOPIC_RESOURCE = Constants.KAFKA_OUTPUT_TOPIC_RESOURCE
    KAFKA_OUTPUT_TOPIC_RESOURCE_COST = Constants.KAFKA_OUTPUT_TOPIC_RESOURCE_COST
    KAFKA_OUTPUT_TOPIC_RESOURCE_SKILL = Constants.KAFKA_OUTPUT_TOPIC_RESOURCE_SKILL
    KAFKA_OUTPUT_TOPIC_PROJECT = Constants.KAFKA_OUTPUT_TOPIC_PROJECT
    KAFKA_OUTPUT_TOPIC_PROJECT_RESOURCE = Constants.KAFKA_OUTPUT_TOPIC_PROJECT_RESOURCE
    KAFKA_OUTPUT_TOPIC_PROJECT_TASK = Constants.KAFKA_OUTPUT_TOPIC_PROJECT_TASK
    KAFKA_CONSUMER_GROUP = Constants.KAFKA_CONSUMER_GROUP
    WEB = Constants.WEB
    CSV_FORMAT = Constants.CSV_FORMAT
    CHUNK_SIZE = Constants.CHUNK_SIZE

    # JDBC and SQLAlchemy URLs using Key Vault secrets or .env fallback
    ENTITY_DB_URL = (
        f"postgresql://{settings.ENTITY_DB_USER}:{settings.ENTITY_DB_PASS}"
        f"@{settings.ENTITY_DB_HOST}:5432/{settings.ENTITY_DB_NAME}"
    )

    STAGING_JDBC_URL = (
        f"jdbc:postgresql://{settings.ENTITY_DB_HOST}:5432/{settings.ENTITY_DB_NAME}"
        f"?user={settings.ENTITY_DB_USER}"
    )


    # Table names
    STAGING_RESOURCE_TABLE = Constants.STAGING_RESOURCE_TABLE
    STAGING_RESOURCE_SKILL_TABLE = Constants.STAGING_RESOURCE_SKILL_TABLE
    STAGING_RESOURCE_COST_TABLE = Constants.STAGING_RESOURCE_COST_TABLE
    STAGING_PROJECT_TABLE = Constants.STAGING_PROJECT_TABLE
    STAGING_PROJECT_RESOURCE_TABLE = Constants.STAGING_PROJECT_RESOURCE_TABLE
    STAGING_PROJECT_TASK_TABLE = Constants.STAGING_PROJECT_TASK_TABLE
    TEMPLATE_COLUMNS_TABLE = Constants.TEMPLATE_COLUMNS_TABLE
    CLIENT_TEMPLATE_COLUMNS_TEMPLATES_TABLE = Constants.CLIENT_TEMPLATE_COLUMNS_TEMPLATES_TABLE
    DOCUMENT_TABLE = Constants.DOCUMENT_TABLE
    IMPORT_TABLE = Constants.IMPORT_TABLE
    KAFKA_EVENTS_TABLE = Constants.KAFKA_EVENTS_TABLE
    TEMPLATE_COLUMNS_TEMPLATES_TABLE = Constants.CLIENT_TEMPLATE_COLUMNS_TEMPLATES_TABLE
    ACCOUNT_DETAIL_TABLE = Constants.ACCOUNT_DETAIL_TABLE
    ACCOUNT_TABLE = Constants.ACCOUNT_TABLE

    # App Config
    SERVICE_NAME = Constants.SERVICE_NAME
    PRODUCED_MESSAGE = Constants.PRODUCED_MESSAGE
    CONSUMER_MESSAGE_SUCCESS = Constants.CONSUMER_MESSAGE_SUCCESS
    CONSUMER_MESSAGE_PROCESS = Constants.CONSUMER_MESSAGE_PROCESS
    CONSUMER_MESSAGE_FAILURE = Constants.CONSUMER_MESSAGE_FAILURE
    PRODUCED_MESSAGE_SUCCESS = Constants.PRODUCED_MESSAGE_SUCCESS
    PRODUCED_MESSAGE_PROCESS = Constants.PRODUCED_MESSAGE_PROCESS
    PRODUCED_MESSAGE_FAILURE = Constants.PRODUCED_MESSAGE_FAILURE
    VALIDATION_MESSAGE_FAILURE = Constants.VALIDATION_MESSAGE_FAILURE
    VALIDATION_MESSAGE_PROCESS = Constants.VALIDATION_MESSAGE_PROCESS
    VALIDATION_MESSAGE_SUCCESS = Constants.VALIDATION_MESSAGE_SUCCESS

    # Azure Blob
    BLOB_CONTAINER = Constants.BLOB_CONTAINER
    BLOB_NAME = Constants.BLOB_NAME
    WORKING_HOURS = Constants.WORKING_HOURS

    #customisation account names
    MANDATORY_COLUMNS_FULLTIME_US = Constants.MANDATORY_COLUMNS_FULLTIME_US
    MANDATORY_COLUMNS_SUBCON_US = Constants.MANDATORY_COLUMNS_SUBCON_US
    STAGING_PROJECT_RESOURCE_TM_US_TABLE  = Constants.STAGING_PROJECT_RESOURCE_TM_US_TABLE
    MANDATORY_COLUMNS_FULLTIME_CA = Constants.MANDATORY_COLUMNS_FULLTIME_CA
    MANDATORY_COLUMNS_SUBCON_CA = Constants.MANDATORY_COLUMNS_SUBCON_CA
    MANDATORY_COLUMNS_TM_FULLTIME_UK = Constants.MANDATORY_COLUMNS_TM_FULLTIME_UK
    MANDATORY_COLUMNS_TM_SUBCON_UK = Constants.MANDATORY_COLUMNS_TM_SUBCON_UK
    MANDATORY_COLUMNS_BS_PROJECT = Constants.MANDATORY_COLUMNS_BS_PROJECT
    MANDATORY_COLUMNS_BS_PROJECT_RESOURCE = Constants.MANDATORY_COLUMNS_BS_PROJECT_RESOURCE
    MANDATORY_COLUMNS_MASTEK = Constants.MANDATORY_COLUMNS_MASTEK
    MANDATORY_COLUMNS_TM_FULLTIME_IR = Constants.MANDATORY_COLUMNS_TM_FULLTIME_IR
    MANDATORY_COLUMNS_TM_SUBCON_IR = Constants.MANDATORY_COLUMNS_TM_SUBCON_IR
    MANDATORY_COLUMNS_TM_FULLTIME_AU = Constants.MANDATORY_COLUMNS_TM_FULLTIME_AU
    MANDATORY_COLUMNS_TM_SUBCON_AU = Constants.MANDATORY_COLUMNS_TM_SUBCON_AU
    MANDATORY_COLUMNS_TMTI_FULLTIME = Constants.MANDATORY_COLUMNS_TMTI_FULLTIME
    MANDATORY_COLUMNS_TMTI_SUBCON = Constants.MANDATORY_COLUMNS_TMTI_SUBCON
    MANDATORY_COLUMNS_PT_TM_UK = Constants.MANDATORY_COLUMNS_PT_TM_UK
    MANDATORY_COLUMNS_TM_ALLYIS_FULLTIME = Constants.MANDATORY_COLUMNS_TM_ALLYIS_FULLTIME
    MANDATORY_COLUMNS_TM_ALLYIS_SUBCON = Constants.MANDATORY_COLUMNS_TM_ALLYIS_SUBCON
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_CA_TABLE  = Constants.STAGING_PROJECT_RESOURCE_FULLTIME_TM_CA_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_CA_TABLE  = Constants.STAGING_PROJECT_RESOURCE_SUBCON_TM_CA_TABLE
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_US_TABLE  = Constants.STAGING_PROJECT_RESOURCE_FULLTIME_TM_US_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_US_TABLE  = Constants.STAGING_PROJECT_RESOURCE_SUBCON_TM_US_TABLE
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_UK_TABLE  = Constants.STAGING_PROJECT_RESOURCE_FULLTIME_TM_UK_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_UK_TABLE  = Constants.STAGING_PROJECT_RESOURCE_SUBCON_TM_UK_TABLE
    STAGING_PROJECT_TABLE_BR = Constants.STAGING_PROJECT_TABLE_BR
    STAGING_PROJECT_RESOURCE_TABLE_BR = Constants.STAGING_PROJECT_RESOURCE_TABLE_BR
    STAGING_RESOURCE_COST_TABLE_MASTEK = Constants.STAGING_RESOURCE_COST_TABLE_MASTEK
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_IR_TABLE  = Constants.STAGING_PROJECT_RESOURCE_FULLTIME_TM_IR_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_IR_TABLE  = Constants.STAGING_PROJECT_RESOURCE_SUBCON_TM_IR_TABLE
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_AU_TABLE  = Constants.STAGING_PROJECT_RESOURCE_FULLTIME_TM_AU_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_AU_TABLE  = Constants.STAGING_PROJECT_RESOURCE_SUBCON_TM_AU_TABLE
    STAGING_PROJECT_RESOURCE_FULLTIME_TMTI_TABLE  = Constants.STAGING_PROJECT_RESOURCE_FULLTIME_TMTI_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TMTI_TABLE  = Constants.STAGING_PROJECT_RESOURCE_SUBCON_TMTI_TABLE
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_ALLYIS_TABLE  = Constants.STAGING_PROJECT_RESOURCE_FULLTIME_TM_ALLYIS_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_ALLYIS_TABLE  = Constants.STAGING_PROJECT_RESOURCE_SUBCON_TM_ALLYIS_TABLE
    CHECK_CUSTOMISATION_TABLE = Constants.CHECK_CUSTOMISATION_TABLE

# # Final config object used across app
config = Config()