export interface IAccount {
  account_id: string;
  account_number: string;
  account_name: string;
  account_description?: string | null;
  status: "active" | "inactive";
  eid: number;
  is_parent: boolean;
  region: number;
  storage_type: "separate_db" | "store_in_parent";
  parent_account_rid?: string | null;
  account_currency_rid: string;
  account_country_rid: string;
  account_country_region_rid: number;
  account_city_rid: number;
  tax_claim_level: string;
  max_ai_interactions: number;
  expiry_duration: number;
  autosend_interaction: boolean;
  auto_access_rd: boolean;
  fiscal_start_date: string;
  fiscal_end_date: string;
  interaction_cc_list?: string | null;
  blended_rate_fte?: string | null;
  blended_rate_subcon?: string | null;
  created_by?: string | null;
  modified_by?: string | null;
  primary_contact_name: string;
  primary_contact_email: string;
  primary_contact_number: string;
  finance_poc_name: string;
  finance_poc_email: string;
  finance_poc_number: string;
  industry: string;
  website?: string | null;
  project_manager: string;
  database_level: boolean;
  database_connection_rid?: number | null;
  created_datetime?: string | null;
  modified_datetime?: string | null;
  annual_revenue: string;
  data_residency?: string | null;
  data_storage: "separate_db" | "store_in_parent";
}

export interface IUpdateAccount {
  account_rid: string;
  account_id: string;
  account_number: string;
  account_name: string;
  account_description?: string | null;
  status: "active" | "inactive";
  eid: number;
  is_parent: boolean;
  region: number;
  storage_type: "separate_db" | "store_in_parent";
  parent_account_rid?: string | null;
  account_currency_rid: string;
  account_country_rid: string;
  account_country_region_rid: number;
  account_city_rid: number;
  tax_claim_level: string;
  max_ai_interactions: number;
  expiry_duration: number;
  autosend_interaction: boolean;
  auto_access_rd: boolean;
  fiscal_start_date: string;
  fiscal_end_date: string;
  interaction_cc_list?: string | null;
  blended_rate_fte?: string | null;
  blended_rate_subcon?: string | null;
  created_by?: string | null;
  modified_by?: string | null;
  primary_contact_name: string;
  primary_contact_email: string;
  primary_contact_number: string;
  finance_poc_name: string;
  finance_poc_email: string;
  finance_poc_number: string;
  industry: string;
  website?: string | null;
  project_manager: string;
  database_level: boolean;
  database_connection_rid?: number | null;
  created_datetime?: string | null;
  modified_datetime?: string | null;
  annual_revenue: string;
  data_residency?: string | null;
  data_storage: "separate_db" | "store_in_parent";
}