import { Router } from "express";
import controller from "../controllers";

import multer from "multer";
import { checkUserStatusMiddleware } from "../middlewares/authmiddleware";

const routes: Router = Router();
const upload = multer({storage : multer.memoryStorage()})
routes.post(
  "/new",
  checkUserStatusMiddleware("cases_create"),
  controller.caseController.createCases
);
routes.get(
  "/details/:accountRid/:caseRid",
  checkUserStatusMiddleware("cases_view_edit"),
  controller.caseController.getCaseHeadersDetails
);
routes.put(
  "/update",
  checkUserStatusMiddleware("cases_view_edit"),
  controller.caseController.updateCases
);
routes.get(
  "/caseFilingType",
  checkUserStatusMiddleware("NA"),
  controller.caseController.getCaseFilingType
);
routes.get(
  "/caseStatus",
  checkUserStatusMiddleware("NA"),
  controller.caseController.getCaseStatus
);
routes.get(
  "/checkListStatus",
  checkUserStatusMiddleware("NA"),
  controller.caseController.getChecklistStatus
);
routes.get(
  "/caseTeamRoles",
  checkUserStatusMiddleware("NA"),
  controller.caseController.getCaseTeamRoles
);
routes.get(
  "/list",
  checkUserStatusMiddleware("cases_view_edit"),
  controller.caseController.listAllCasesAccount
);
routes.get(
  "/list/caseSummary",
  checkUserStatusMiddleware("cases_view_edit"),
  controller.caseController.listAllCasesSummary
);
routes.get(
  "/export",
  checkUserStatusMiddleware("cases_export"),
  controller.caseController.exportAllCasesAccount
);
routes.get(
  "/export/caseSummary",
  checkUserStatusMiddleware("cases_export"),
  controller.caseController.exportAllCasesSummary
);
routes.post(
  "/projects",
  checkUserStatusMiddleware("projects_view_edit"),
  controller.caseController.fetchProjectForAssign
);
routes.post(
  "/projects/assign",
  checkUserStatusMiddleware("projects_view_edit"),
  controller.caseController.assignProjectToCase
);

routes.post(
  "/assignedProjects",
  checkUserStatusMiddleware("projects_view_edit"),
  controller.caseController.fetchAssignedprojects
);

routes.post(
  "/projects/delete",
  checkUserStatusMiddleware("projects_view_edit"),
  controller.caseController.deleteProjectFromCase
);

routes.post(
  "/createCaseTeam",
  checkUserStatusMiddleware("case_team_create"),
  controller.caseController.createCaseTeam
);
routes.get(
  "/caseTeam/list",
  checkUserStatusMiddleware("case_team_view_edit"),
  controller.caseController.listCaseTeamMembers
);
routes.post(
  "/assignedProjects/export",
  checkUserStatusMiddleware("projects_view_edit"),
  controller.caseController.exportAllAssignedProjects
)
routes.get(
  "/caseTeam/users/:accountRid",
  checkUserStatusMiddleware("NA"),
  controller.caseController.listUsersForCaseTeam
);
routes.get(
  "/caseOwners",
  checkUserStatusMiddleware("NA"),
  controller.caseController.listUserForCaseOwner
);
routes.post(
  "/checklist/create",
  checkUserStatusMiddleware("NA"),
  controller.caseController.createCheckList
);
routes.post(
  "/checklist/update",
  checkUserStatusMiddleware("NA"),
  controller.caseController.updateCheckList
);
routes.get(
  "/checklist/detail/:checkListRid",
  checkUserStatusMiddleware("NA"),
  controller.caseController.getCheckListDetailsById
);
routes.get(
  "/checklist/list",
  checkUserStatusMiddleware("NA"),
  controller.caseController.getAllChecklists
);
routes.get(
  "/checklist/export",
  checkUserStatusMiddleware("NA"),
  controller.caseController.exportAllChecklists
);
routes.get(
  "/workBreakdown/:accountRid/:caseRid",
  checkUserStatusMiddleware("NA"),
  controller.caseController.fetchCaseKanbanBoard
);
routes.post(
  "/task/create",
  checkUserStatusMiddleware("NA"),
  controller.caseController.createTask
);
routes.put(
  '/task/update',
  checkUserStatusMiddleware("NA"),
  controller.caseController.updateTask
);
routes.post(
  "/task/list",
  checkUserStatusMiddleware("NA"),
  controller.caseController.fetchCaseTaskList
)
routes.post(
  "/tag/add",
  checkUserStatusMiddleware("NA"),
  controller.caseController.createOrMapTags
)
routes.get(
  "/tag/list",
  checkUserStatusMiddleware("NA"),
  controller.caseController.fetchAllTags
)
routes.post(
  "/comments/add",
  checkUserStatusMiddleware("NA"),
  upload.array('files'),
  controller.caseController.addCommentsToSpecificTask
)
routes.post(
  "/task/export",
  checkUserStatusMiddleware("NA"),
  controller.caseController.exportCaseTask
)
routes.put(
  "/comments/update",
  checkUserStatusMiddleware("NA"),
  upload.array('files'),
  controller.caseController.updateTaskComments
)
routes.post(
  "/comments/delete",
  checkUserStatusMiddleware("NA"),
  controller.caseController.deleteTaskComments
)

export default routes;
