import { ListTableColumn } from '../../../../../../../components/table/types';
import { ProjectFinancialResourceCostList } from '../../../../../../types';

export const getFinancialResourceCostColumns =
  (): ListTableColumn<ProjectFinancialResourceCostList>[] => [
    {
      id: 'project_code',
      editId: 'project_code',
      sortId: 'project_code',
      label: 'Project Code',
      width: 130,
      sortable: true,
      sticky: true,
      sx: {
        position: 'sticky',
        left: 0,
        background: '#fff',
        zIndex: 10,
        borderRight: '1px solid #CBD6E2 !important',
        borderBottom: '1px solid #CBD6E2 !important',
      },
    },
    {
      id: 'fiscal_year',
      editId: 'fiscal_year',
      sortId: 'fiscal_year',
      label: 'Fiscal Year',
      width: 130,
      sortable: false,
      render: (row: ProjectFinancialResourceCostList) =>
        row.fiscal_year ? `FY-${row.fiscal_year}` : '-',
    },
    {
      id: 'project_name',
      editId: 'project_name',
      sortId: 'project_name',
      label: 'Project Name',
      width: 130,
      sortable: true,
    },
    {
      id: 'r_number',
      editId: 'r_number',
      sortId: 'r_number',
      label: 'Project ID',
      width: 130,
      sortable: true,
    },
    {
      id: 'resource_code',
      editId: 'resource_code',
      sortId: 'resource_code',
      label: 'Resource Code',
      width: 130,
      sortable: true,
    },
    {
      id: 'resource_name',
      editId: 'resource_name',
      sortId: 'resource_name',
      label: 'Resource Name',
      width: 160,
      sortable: true,
    },
    {
      id: 'resource_type_name',
      editId: 'resource_type_name',
      sortId: 'resource_type_name',
      label: 'Resource Type',
      width: 130,
      sortable: true,
    },
    {
      id: 'country_name',
      editId: 'country_name',
      sortId: 'country_name',
      label: 'Country',
      width: 130,
      sortable: true,
    },
    {
      id: 'total_cost_pro_res',
      editId: 'total_cost_pro_res',
      sortId: 'total_cost_pro_res',
      label: 'Cost',
      width: 130,
      sortable: true,
    },
    {
      id: 'rd_percent_final',
      editId: 'rd_percent_final',
      sortId: 'rd_percent_final',
      label: 'RD %',
      width: 130,
      sortable: true,
    },
    {
      id: 'qre_final',
      editId: 'qre_final',
      sortId: 'qre_final',
      label: 'Project QRE',
      width: 130,
      sortable: true,
    },
    {
      id: 'rd_credits_total',
      editId: 'rd_credits_total',
      sortId: 'rd_credits_total',
      label: 'RD Credit',
      width: 130,
      sortable: true,
    },
  ];
