import { ListTableColumn } from '../../../../../../../components/table/types';
import { FinancialResourceCostList } from '../../../../../../types';

export const getFinancialResourceCostColumns =
  (): ListTableColumn<FinancialResourceCostList>[] => [
    {
      id: 'project_code',
      editId: 'project_code',
      sortId: 'project_code',
      label: 'Project Code',
      width: 130,
      sortable: true,
      sx: {
        position: 'sticky',
        left: 0,
        background: '#fff',
        zIndex: 10,
        borderRight: '1px solid #CBD6E2 !important',
        borderBottom: '1px solid #CBD6E2 !important',
      },
    },
    {
      id: 'fiscal_year',
      editId: 'fiscal_year',
      sortId: 'fiscal_year',
      label: 'Fiscal Year',
      width: 130,
      sortable: true,
    },
    {
      id: 'project_name',
      editId: 'project_name',
      sortId: 'project_name',
      label: 'Project Name',
      width: 130,
      sortable: true,
    },
    {
      id: 'project_id',
      editId: 'project_id',
      sortId: 'project_id',
      label: 'Project ID',
      width: 130,
      sortable: true,
    },
    {
      id: 'resource_code',
      editId: 'resource_code',
      sortId: 'resource_code',
      label: 'Resource Code',
      width: 130,
      sortable: true,
    },
    {
      id: 'resource_name',
      editId: 'resource_name',
      sortId: 'resource_name',
      label: 'Resource Name',
      width: 160,
      sortable: true,
    },
    {
      id: 'resource_type',
      editId: 'resource_type',
      sortId: 'resource_type',
      label: 'Resource Type',
      width: 130,
      sortable: true,
    },
    {
      id: 'country',
      editId: 'country',
      sortId: 'country',
      label: 'Country',
      width: 130,
      sortable: true,
    },
    {
      id: 'cost',
      editId: 'cost',
      sortId: 'cost',
      label: 'Cost',
      width: 130,
      sortable: true,
    },
    {
      id: 'rd',
      editId: 'rd',
      sortId: 'rd',
      label: 'RD %',
      width: 130,
      sortable: true,
    },
    {
      id: 'project_qre',
      editId: 'project_qre',
      sortId: 'project_qre',
      label: 'Project QRE',
      width: 130,
      sortable: true,
    },
    {
      id: 'rd_credit',
      editId: 'rd_credit',
      sortId: 'rd_credit',
      label: 'RD Credit',
      width: 130,
      sortable: true,
    },
  ];
