export const mockAccountListData = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: '',
  data: {
    account: [
      {
        rid: '42aebc2d-ad29-4202-9bdd-bee58fc24992',
        r_number: 'ACC0001',
        account_name: 'TechM-Global',
        account_description: 'This is a description of the account.',
        eid: null,
        status: 'active',
        is_parent: true,
        annual_revenue: '10000',
        region: '69366422-5283-47d5-a972-e07bfd688af0',
        storage_type: 'separate_db',
        parent_account_rid: null,
        database_connection_rid: null,
        country_rid: 'e66380cd-d24c-4581-8e29-07ada063acdb',
        currency_rid: '571523e6-2dba-41ff-b857-6aee33dc3db5',
        industry: 'Technology',
        primary_contact_name: 'John Doe',
        created_datetime: '2025-04-15T12:03:17.291Z',
        modified_datetime: '2025-04-15T12:03:17.291Z',
        child_accounts: [
          {
            rid: 'ac584a98-8e61-4f56-935e-8fa59d12fce7',
            r_number: 'ACC0002',
            account_name: 'TechM-US',
            account_description: 'This is a description of the account.',
            eid: null,
            status: 'active',
            is_parent: false,
            annual_revenue: '10000',
            region: '69366422-5283-47d5-a972-e07bfd688af0',
            storage_type: 'store_in_parent',
            parent_account_rid: '42aebc2d-ad29-4202-9bdd-bee58fc24992',
            database_connection_rid: null,
            country_rid: 'e66380cd-d24c-4581-8e29-07ada063acdb',
            currency_rid: '571523e6-2dba-41ff-b857-6aee33dc3db5',
            industry: 'Technology',
            primary_contact_name: 'John Doe',
            created_datetime: '2025-04-15T12:04:43.685Z',
            modified_datetime: '2025-04-15T12:04:43.685Z',
            country: {
              country_name: 'United States',
            },
            currency: {
              currency_code: 'USD',
            },
            parent_account: {
              account_name: 'TechM-Global',
            },
          },
          {
            rid: '582f23d1-1823-49f1-8b3f-96f2017773fd',
            r_number: 'ACC0003',
            account_name: 'TechM-UK',
            account_description:
              'This is a sample account for demonstration purposes.',
            eid: null,
            status: 'active',
            is_parent: false,
            annual_revenue: '1033000',
            region: '69366422-5283-47d5-a972-e07bfd688af0',
            storage_type: 'separate_db',
            parent_account_rid: '42aebc2d-ad29-4202-9bdd-bee58fc24992',
            database_connection_rid: null,
            country_rid: 'e66380cd-d24c-4581-8e29-07ada063acdb',
            currency_rid: '571523e6-2dba-41ff-b857-6aee33dc3db5',
            industry: 'Technology',
            primary_contact_name: 'David Doe',
            created_datetime: '2025-04-15T12:06:22.816Z',
            modified_datetime: '2025-04-15T12:06:22.816Z',
            country: {
              country_name: 'United States',
            },
            currency: {
              currency_code: 'USD',
            },
            parent_account: {
              account_name: 'TechM-Global',
            },
          },
        ],
        country: {
          country_name: 'United States',
        },
        currency: {
          currency_code: 'USD',
        },
      },
    ],
    count: 1,
  },
  requestId: 'd7812cd6-e2d6-4fa3-8d42-ade6093c2b3a',
};

export const mockAccountsData = [
  {
    accountName: 'True Tech AI Solutions Inc - Global',
    accountId: '1001001',
    parentAccount: null,
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'In Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: 'True Tech AI Solutions Inc - US',
    accountId: '1001002',
    parentAccount: 'True Tech AI Solutions Inc - Global',
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: 'True Tech AI Solutions Inc - CAN',
    accountId: '1001003',
    parentAccount: 'True Tech AI Solutions Inc - Global',
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: 'True Tech AI Solutions Inc - UK',
    accountId: '1001004',
    parentAccount: 'True Tech AI Solutions Inc - Global',
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: "L'Avenir Pharmaceuticals Inc - Global",
    accountId: '1001005',
    parentAccount: null,
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: "L'Avenir Pharmaceuticals Inc - CAN",
    accountId: '1001006',
    parentAccount: "L'Avenir Pharmaceuticals Inc - Global",
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: "L'Avenir Pharmaceuticals Inc - USA",
    accountId: '1001007',
    parentAccount: "L'Avenir Pharmaceuticals Inc - Global",
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
];
