import { Account } from '../types/account';

export const mockAccountsData: Account[] = [
  {
    accountName: 'True Tech AI Solutions Inc - Global',
    accountId: '1001001',
    parentAccount: null,
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'In Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: 'True Tech AI Solutions Inc - US',
    accountId: '1001002',
    parentAccount: 'True Tech AI Solutions Inc - Global',
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: 'True Tech AI Solutions Inc - CAN',
    accountId: '1001003',
    parentAccount: 'True Tech AI Solutions Inc - Global',
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: 'True Tech AI Solutions Inc - UK',
    accountId: '1001004',
    parentAccount: 'True Tech AI Solutions Inc - Global',
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: "L'Avenir Pharmaceuticals Inc - Global",
    accountId: '1001005',
    parentAccount: null,
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: "L'Avenir Pharmaceuticals Inc - CAN",
    accountId: '1001006',
    parentAccount: "L'Avenir Pharmaceuticals Inc - Global",
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
  {
    accountName: "L'Avenir Pharmaceuticals Inc - USA",
    accountId: '1001007',
    parentAccount: "L'Avenir Pharmaceuticals Inc - Global",
    accountNumber: 'AC001',
    industry: 'ITServices',
    country: 'USA',
    currency: 'USD',
    status: 'Active',
    primaryContact: 'John Doe',
  },
];
