import { CaseProjectResourceListResponse } from '../types/case-project-resource';

export const mockCaseProjectResourceList: CaseProjectResourceListResponse = {
  data: {
    projectResources: [
      {
        rid: 'CPR001',
        r_number: 'R001',
        resource_code: 'RCODE-001',
        project_resource_code: 'PR-001',
        project_resource_id: 'PRD-001',
        resource_name: 'John Doe',
        resource_firstname: 'John',
        resource_lastname: 'Doe',
        resource_type_name: 'Full-Time',
        resource_type_rid: 'RT-001',
        designation: 'Senior Developer',
        resource_role: 'Developer',
        resource_orgname: 'Hubino',
        project_rid: 'PROJ-001',
        project_code: 'PRJ-001',
        project_name: 'Project Alpha',
        project_resource_role: 'Lead Developer',
        country_rid: 'CTRY-001',
        country_name: 'United States',
        country_code: 'US',
        region_rid: 'REG-001',
        region_name: 'North America',
        resource_region: 'Eastern',
        resource_country: 'USA',
        city_rid: 'CITY-001',
        city_name: 'New York',
        currency_rid: 'CUR-001',
        currency_name: 'US Dollar',
        currency_symbol: '$',
        resource_startdate: '2024-01-15',
        resource_enddate: '2024-12-31',
        start_date: '2024-01-15',
        end_date: '2024-12-31',
        resource_total_experience: 8,
        resource_total_experience_organization: 3,
        total_hours_pro_res: 1200,
        effort_hours: 1200,
        total_cost_pro_res: 60000,
        net_resource_cost: 55000,
        net_total_cost_pro_res: 55000,
        effort_project_resource_level: 80,
        cost_project_resource_level: 85,
        qre_final: 90,
        qre_percent: 0.9,
        salary: 50000,
        bonus: 5000,
        insurance: 3000,
        deductions: 2000,
        status_rid: 'STS-001',
        status_name: 'Active',
        comments: 'Developer',
        description: 'Senior developer working on core features',
        account_rid: 'ACC-001',
        created_by: 'admin',
        modified_by: 'admin',
        created_datetime: '2024-01-01T10:00:00Z',
        modified_datetime: '2024-11-13T10:00:00Z',
        attachment: [],
        assigned_skill_role_type_rid: 'SKILL-001',
        skill_role_rid: 'SR-001',
        skill_role_others: null,
        fiscal_year: 2024,
        project_fiscal_rid: 'PF-001',
        resource_rid: 'RES-001',
        account_number: 'ACC-NUM-001',
      },
      {
        rid: 'CPR002',
        r_number: 'R002',
        resource_code: 'RCODE-002',
        project_resource_code: 'PR-002',
        project_resource_id: 'PRD-002',
        resource_name: 'Jane Smith',
        resource_firstname: 'Jane',
        resource_lastname: 'Smith',
        resource_type_name: 'Contract',
        resource_type_rid: 'RT-002',
        designation: 'QA Engineer',
        resource_role: 'Tester',
        resource_orgname: 'Certainti',
        project_rid: 'PROJ-001',
        project_code: 'PRJ-001',
        project_name: 'Project Alpha',
        project_resource_role: 'QA Lead',
        country_rid: 'CTRY-002',
        country_name: 'Canada',
        country_code: 'CA',
        region_rid: 'REG-002',
        region_name: 'North America',
        resource_region: 'Central',
        resource_country: 'Canada',
        city_rid: 'CITY-002',
        city_name: 'Toronto',
        currency_rid: 'CUR-002',
        currency_name: 'Canadian Dollar',
        currency_symbol: 'C$',
        resource_startdate: '2024-02-01',
        resource_enddate: '2024-11-30',
        start_date: '2024-02-01',
        end_date: '2024-11-30',
        resource_total_experience: 6,
        resource_total_experience_organization: 2,
        total_hours_pro_res: 960,
        effort_hours: 960,
        total_cost_pro_res: 38400,
        net_resource_cost: 35200,
        net_total_cost_pro_res: 35200,
        effort_project_resource_level: 75,
        cost_project_resource_level: 78,
        qre_final: 85,
        qre_percent: 0.85,
        salary: 35000,
        bonus: 2000,
        insurance: 2000,
        deductions: 1400,
        status_rid: 'STS-001',
        status_name: 'Active',
        comments: 'Good performance',
        description: 'QA Engineer ensuring product quality',
        account_rid: 'ACC-002',
        created_by: 'admin',
        modified_by: 'admin',
        created_datetime: '2024-02-01T10:00:00Z',
        modified_datetime: '2024-11-13T10:00:00Z',
        attachment: [],
        assigned_skill_role_type_rid: 'SKILL-002',
        skill_role_rid: 'SR-002',
        skill_role_others: 'Automation Testing',
        fiscal_year: 2024,
        project_fiscal_rid: 'PF-001',
        resource_rid: 'RES-002',
        account_number: 'ACC-NUM-002',
      },
    ],
    count: 2,
    totalCount: 2,
  },
};
