import { cases } from '../types';

export const casesList: cases[] = [
  {
    caseId: '50005011',
    caseNo: 'CS00011',
    fiscalYear: 2024,
    caseCode: 'TrueTechAI2024_All_RD',
    caseType: 'RD Assessment',
    country: 'USA',
    region: 'Federal',
    caseOwner: 'Krish Balaraman',
    rdClaim: '22M',
    creator: '6/4/20',
  },
  {
    caseId: '50005010',
    caseNo: 'CS00010',
    fiscalYear: 2024,
    caseCode: 'TrueTechAI2024_All_RD',
    caseType: 'RD Assessment',
    country: 'USA',
    region: 'Federal',
    caseOwner: 'Krish Balaraman',
    rdClaim: '16.3M',
    creator: '3/4/20',
  },
  {
    caseId: '50005009',
    caseNo: 'CS00009',
    fiscalYear: 2023,
    caseCode: 'TrueTechAI2024_All_RD',
    caseType: 'RD Assessment',
    country: 'USA',
    region: 'Texas',
    caseOwner: 'Krish Balaraman',
    rdClaim: '3.2M',
    creator: '10/4/20',
  },
  {
    caseId: '50005008',
    caseNo: 'CS00008',
    fiscalYear: 2024,
    caseCode: 'TrueTechAI2024_All_RD',
    caseType: 'RD Assessment',
    country: 'USA',
    region: 'Texas',
    caseOwner: 'Krish Balaraman',
    rdClaim: '8M',
    creator: '3/4/20',
  },
  {
    caseId: '50005007',
    caseNo: 'CS00007',
    fiscalYear: 2023,
    caseCode: 'TrueTechAI2024_All_RD',
    caseType: 'RD Assessment',
    country: 'USA',
    region: 'Federal',
    caseOwner: 'Krish Balaraman',
    rdClaim: '7.6M',
    creator: '10/4/20',
  },
  {
    caseId: '50005006',
    caseNo: 'CS00006',
    fiscalYear: 2024,
    caseCode: 'TrueTechAI2024_All_RD',
    caseType: 'RD Assessment',
    country: 'USA',
    region: 'Federal',
    caseOwner: 'Krish Balaraman',
    rdClaim: '3.2M',
    creator: '7/3/20',
  },
  {
    caseId: '50005005',
    caseNo: 'CS00005',
    fiscalYear: 2024,
    caseCode: 'TrueTechAI2024_All_RD',
    caseType: 'RD Assessment',
    country: 'USA',
    region: 'Texas',
    caseOwner: 'Krish Balaraman',
    rdClaim: '10M',
    creator: '9/7/20',
  },
  {
    caseId: '50005004',
    caseNo: 'CS00004',
    fiscalYear: 2023,
    caseCode: 'TrueTechAI2024_All_RD',
    caseType: 'RD Assessment',
    country: 'USA',
    region: 'Federal',
    caseOwner: 'Krish Balaraman',
    rdClaim: '2.2M',
    creator: '15/5/20',
  },
  {
    caseId: '50005003',
    caseNo: 'CS00003',
    fiscalYear: 2024,
    caseCode: 'TrueTechAI2024_All_RD',
    caseType: 'RD Assessment',
    country: 'USA',
    region: 'Texas',
    caseOwner: 'Krish Balaraman',
    rdClaim: '4.3M',
    creator: '19/12/20',
  },
];
