import {
  DashboardCountDetailsResponse,
  GlobalLevelChartResponse,
  HealthStatusResponse,
  OverallProjectValueResponse,
  WeeklyProductivityResponse,
  OverdueApprovalsResponse,
  DashboardTaskResponse,
} from '../types';

export const dashboardCountDetailsMock: DashboardCountDetailsResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    { name: 'Active Accounts', count: '310', order: 1 },
    { name: 'Total Cases', count: '384', order: 2 },
    { name: 'Completed Cases', count: '63', order: 3 },
    { name: 'On Hold Cases', count: '1', order: 4 },
    { name: 'Open Tasks', count: '3440', order: 5 },
    { name: 'Overdue Tasks', count: '2523', order: 6 },
    { name: 'Upcoming Tasks', count: '117', order: 7 },
    { name: 'Weekly Completed Tasks', count: '0', order: 8 },
  ],
};

export const healthStatusDetailMock: HealthStatusResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    // Avasoft
    {
      account_rid: 'D090k-acc-001',
      account_name: 'Avasoft',
      fiscal_year: 2026,
      progress: '75',
    },
    {
      account_rid: 'D090k-acc-001',
      account_name: 'Avasoft',
      fiscal_year: 2025,
      progress: '68',
    },
    {
      account_rid: 'D090k-acc-001',
      account_name: 'Avasoft',
      fiscal_year: 2024,
      progress: '60',
    },
    {
      account_rid: 'D090k-acc-001',
      account_name: 'Avasoft',
      fiscal_year: 2022,
      progress: '40',
    },
    {
      account_rid: 'D090k-acc-001',
      account_name: 'Avasoft',
      fiscal_year: 2021,
      progress: '15',
    },

    // Avasoft1
    {
      account_rid: 'D090k-acc-002',
      account_name: 'Avasoft1',
      fiscal_year: 2026,
      progress: '70',
    },
    {
      account_rid: 'D090k-acc-002',
      account_name: 'Avasoft1',
      fiscal_year: 2025,
      progress: '62',
    },
    {
      account_rid: 'D090k-acc-002',
      account_name: 'Avasoft1',
      fiscal_year: 2024,
      progress: '58',
    },
    {
      account_rid: 'D090k-acc-002',
      account_name: 'Avasoft1',
      fiscal_year: 2023,
      progress: '55',
    },
    // Backend Test Account - 1
    {
      account_rid: 'D090k-acc-003',
      account_name: 'Backend Test Account - 1',
      fiscal_year: 2026,
      progress: '55',
    },
    {
      account_rid: 'D090k-acc-003',
      account_name: 'Backend Test Account - 1',
      fiscal_year: 2023,
      progress: '45',
    },
    {
      account_rid: 'D090k-acc-003',
      account_name: 'Backend Test Account - 1',
      fiscal_year: 2022,
      progress: '25',
    },
    {
      account_rid: 'D090k-acc-003',
      account_name: 'Backend Test Account - 1',
      fiscal_year: 2021,
      progress: '10',
    },

    // Internal QA Account
    {
      account_rid: 'D090k-acc-004',
      account_name: 'Internal QA Account',
      fiscal_year: 2026,
      progress: '80',
    },
    {
      account_rid: 'D090k-acc-004',
      account_name: 'Internal QA Account',
      fiscal_year: 2024,
      progress: '72',
    },
    {
      account_rid: 'D090k-acc-004',
      account_name: 'Internal QA Account',
      fiscal_year: 2023,
      progress: '70',
    },
    {
      account_rid: 'D090k-acc-004',
      account_name: 'Internal QA Account',
      fiscal_year: 2022,
      progress: '50',
    },
  ],
};

export const overallProjectValueMock: OverallProjectValueResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    {
      country_rid: 'CNT-US',
      country_code: 'US',
      country_name: 'United States',
      total_project_cost: '950',
      qualified_project_cost: '720',
      qre_cost: '410',
      rd_credits_computed: '82',
      rd_credits_submitted: '75',
      rd_credits_approved: '60',
    },
    {
      country_rid: 'CNT-CA',
      country_code: 'CA',
      country_name: 'Canada',
      total_project_cost: '780',
      qualified_project_cost: '560',
      qre_cost: '320',
      rd_credits_computed: '96',
      rd_credits_submitted: '88',
      rd_credits_approved: '70',
    },
    {
      country_rid: 'CNT-GB',
      country_code: 'GB',
      country_name: 'United Kingdom',
      total_project_cost: '640',
      qualified_project_cost: '480',
      qre_cost: '260',
      rd_credits_computed: '52',
      rd_credits_submitted: '48',
      rd_credits_approved: '40',
    },
    {
      country_rid: 'CNT-IE',
      country_code: 'IE',
      country_name: 'Ireland',
      total_project_cost: '420',
      qualified_project_cost: '300',
      qre_cost: '180',
      rd_credits_computed: '45',
      rd_credits_submitted: '40',
      rd_credits_approved: '35',
    },
    {
      country_rid: 'CNT-AU',
      country_code: 'AU',
      country_name: 'Australia',
      total_project_cost: '510',
      qualified_project_cost: '360',
      qre_cost: '220',
      rd_credits_computed: '66',
      rd_credits_submitted: '60',
      rd_credits_approved: '52',
    },
  ],
};

export const globalLevelChartMock: GlobalLevelChartResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    {
      account_name: 'Cases Infosys USA',
      country_name: 'United States',
      country_code: 'USA',
      total_project_cost: '850',
      qualified_project_cost: '620',
      qre_cost: '410',
      rd_credits_computed: '82',
      rd_credits_submitted: '75',
      rd_credits_approved: '60',
    },
    {
      account_name: 'Zoho-US',
      country_name: 'United States',
      country_code: 'USA',
      total_project_cost: '720',
      qualified_project_cost: '540',
      qre_cost: '300',
      rd_credits_computed: '60',
      rd_credits_submitted: '55',
      rd_credits_approved: '45',
    },
    {
      account_name: 'Shopify-CA',
      country_name: 'Canada',
      country_code: 'CAN',
      total_project_cost: '640',
      qualified_project_cost: '480',
      qre_cost: '260',
      rd_credits_computed: '78',
      rd_credits_submitted: '70',
      rd_credits_approved: '58',
    },
    {
      account_name: 'TechNova-UK',
      country_name: 'United Kingdom',
      country_code: 'GBR',
      total_project_cost: '590',
      qualified_project_cost: '430',
      qre_cost: '240',
      rd_credits_computed: '48',
      rd_credits_submitted: '42',
      rd_credits_approved: '35',
    },
    {
      account_name: 'FinEdge-UK',
      country_name: 'United Kingdom',
      country_code: 'GBR',
      total_project_cost: '510',
      qualified_project_cost: '370',
      qre_cost: '210',
      rd_credits_computed: '42',
      rd_credits_submitted: '38',
      rd_credits_approved: '30',
    },
    {
      account_name: 'Dublin Labs',
      country_name: 'Ireland',
      country_code: 'IRL',
      total_project_cost: '460',
      qualified_project_cost: '330',
      qre_cost: '190',
      rd_credits_computed: '47',
      rd_credits_submitted: '44',
      rd_credits_approved: '36',
    },
    {
      account_name: 'Sydney Innovations',
      country_name: 'Australia',
      country_code: 'AUS',
      total_project_cost: '530',
      qualified_project_cost: '380',
      qre_cost: '220',
      rd_credits_computed: '66',
      rd_credits_submitted: '60',
      rd_credits_approved: '50',
    },
    {
      account_name: 'Melbourne Tech Hub',
      country_name: 'Australia',
      country_code: 'AUS',
      total_project_cost: '480',
      qualified_project_cost: '350',
      qre_cost: '200',
      rd_credits_computed: '60',
      rd_credits_submitted: '54',
      rd_credits_approved: '45',
    },
  ],
};

export const weeklyProductivityMock: WeeklyProductivityResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    {
      category: 'Tasks Completed',
      count: '45',
      total: '120',
      unit: 'tasks',
    },
    {
      category: 'Meetings / Sessions Attended',
      count: 12,
      total: 15,
      unit: 'meetings',
    },
    {
      category: 'Pending Tasks',
      count: '109',
      total: '120',
      unit: 'tasks',
    },
    {
      category: 'Blocked / Bottlenecks',
      count: '2',
      total: 10,
      unit: 'issues',
    },
  ],
};

export const overdueApprovalsMock: OverdueApprovalsResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    {
      rid: 'D001-7314ce50-d607-4f89-8aaa-dabf0be77254',
      r_number: 'CSTK-0000005073',
      task_name: 'test',
      status: 'To Do',
      effective_start_datetime: '2025-12-16T00:00:00.000Z',
      effective_end_datetime: '2025-12-17T00:00:00.000Z',
      case_r_number: 'CHS-0000000070',
      case_name: 'Test-23323',
      assigned_to: '',
      priority_name: 'Low',
      fiscal_year: 2020,
      account_name: 'Brilliant',
      assigned_to_name: '',
      category_name: 'Approvals & Sign-offs',
      profile_url: null,
    },
    {
      rid: 'D001-c2e19b7c-4e7e-4572-8fa4-36b29deedc16',
      r_number: 'CSTK-0000004193',
      task_name: 'test',
      status: 'To Do',
      effective_start_datetime: '2024-11-29T00:00:00.000Z',
      effective_end_datetime: '2024-11-30T00:00:00.000Z',
      case_r_number: 'CAS-0000000238',
      case_name: 'Testragu',
      assigned_to: 'D001-79c7fc6e-d99c-4a69-9e24-c064bac251a0',
      priority_name: 'Low',
      fiscal_year: 2024,
      account_name: 'Zoho-USA',
      assigned_to_name: 'Arun Mani',
      category_name: 'Approvals & Sign-offs',
      profile_url: null,
    },
    {
      rid: 'D001-8185b01b-2861-4fdd-92ad-4cb5a56220be',
      r_number: 'CSTK-0000004140',
      task_name: 'Assign Projects',
      status: 'To Do',
      effective_start_datetime: '2024-01-07T00:00:00.000Z',
      effective_end_datetime: '2024-01-08T00:00:00.000Z',
      case_r_number: 'CAS-0000000270',
      case_name: 'Game Developing - GTA 2',
      assigned_to: '',
      priority_name: 'Medium',
      fiscal_year: 2025,
      account_name: 'Backend Test Account',
      assigned_to_name: '',
      category_name: 'Approvals & Sign-offs',
      profile_url: null,
    },
  ],
};
export const upcomingTasksMock: DashboardTaskResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    {
      rid: 'D001-1001',
      r_number: 'CSTK-0000005101',
      task_name: 'Prepare QRE Summary',
      status: 'To Do',
      effective_start_datetime: '2026-02-15T00:00:00.000Z',
      effective_end_datetime: '2026-02-18T00:00:00.000Z',
      case_r_number: 'CHS-0000000201',
      case_name: 'R&D Case - US',
      assigned_to: 'USR-01',
      priority_name: 'High',
      fiscal_year: 2026,
      account_name: 'Test Account US',
      assigned_to_name: 'John Smith',
      profile_url: null,
    },
    {
      rid: 'D001-1002',
      r_number: 'CSTK-0000005102',
      task_name: 'Client Documentation Review',
      status: 'To Do',
      effective_start_datetime: '2026-02-16T00:00:00.000Z',
      effective_end_datetime: '2026-02-20T00:00:00.000Z',
      case_r_number: 'CHS-0000000202',
      case_name: 'Canada Innovation Case',
      assigned_to: 'USR-02',
      priority_name: 'Medium',
      fiscal_year: 2026,
      account_name: 'Test Account CA',
      assigned_to_name: 'Priya N',
      profile_url: null,
    },
    {
      rid: 'D001-1003',
      r_number: 'CSTK-0000005103',
      task_name: 'Tax Credit Validation',
      status: 'To Do',
      effective_start_datetime: '2026-02-17T00:00:00.000Z',
      effective_end_datetime: '2026-02-22T00:00:00.000Z',
      case_r_number: 'CHS-0000000203',
      case_name: 'UK Tech Case',
      assigned_to: 'USR-03',
      priority_name: 'Low',
      fiscal_year: 2026,
      account_name: 'Test Account UK',
      assigned_to_name: 'David Lee',
      profile_url: null,
    },
    {
      rid: 'D001-1004',
      r_number: 'CSTK-0000005104',
      task_name: 'Financial Data Sync',
      status: 'To Do',
      effective_start_datetime: '2026-02-18T00:00:00.000Z',
      effective_end_datetime: '2026-02-23T00:00:00.000Z',
      case_r_number: 'CHS-0000000204',
      case_name: 'Ireland R&D Filing',
      assigned_to: 'USR-04',
      priority_name: 'High',
      fiscal_year: 2026,
      account_name: 'Test Account IE',
      assigned_to_name: 'Aishwarya K',
      profile_url: null,
    },
    {
      rid: 'D001-1005',
      r_number: 'CSTK-0000005105',
      task_name: 'Audit Preparation',
      status: 'To Do',
      effective_start_datetime: '2026-02-19T00:00:00.000Z',
      effective_end_datetime: '2026-02-25T00:00:00.000Z',
      case_r_number: 'CHS-0000000205',
      case_name: 'Australia Innovation',
      assigned_to: 'USR-05',
      priority_name: 'Medium',
      fiscal_year: 2026,
      account_name: 'Test Account AU',
      assigned_to_name: 'Michael Brown',
      profile_url: null,
    },
  ],
};

export const dueTodayOverdueTasksMock: DashboardTaskResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    {
      rid: 'D001-2001',
      r_number: 'CSTK-0000005201',
      task_name: 'Finalize Cost Report',
      status: 'Overdue',
      effective_start_datetime: '2026-02-05T00:00:00.000Z',
      effective_end_datetime: '2026-02-10T00:00:00.000Z',
      case_r_number: 'CHS-0000000301',
      case_name: 'US Filing Case',
      assigned_to: 'USR-01',
      priority_name: 'High',
      fiscal_year: 2026,
      account_name: 'Test Account US',
      assigned_to_name: 'John Smith',
      profile_url: null,
    },
    {
      rid: 'D001-2002',
      r_number: 'CSTK-0000005202',
      task_name: 'Upload Supporting Docs',
      status: 'Due Today',
      effective_start_datetime: '2026-02-12T00:00:00.000Z',
      effective_end_datetime: '2026-02-14T00:00:00.000Z',
      case_r_number: 'CHS-0000000302',
      case_name: 'Canada R&D Case',
      assigned_to: 'USR-02',
      priority_name: 'Medium',
      fiscal_year: 2026,
      account_name: 'Test Account CA',
      assigned_to_name: 'Priya N',
      profile_url: null,
    },
    {
      rid: 'D001-2003',
      r_number: 'CSTK-0000005203',
      task_name: 'Review Client Notes',
      status: 'Overdue',
      effective_start_datetime: '2026-02-01T00:00:00.000Z',
      effective_end_datetime: '2026-02-08T00:00:00.000Z',
      case_r_number: 'CHS-0000000303',
      case_name: 'UK Claim',
      assigned_to: 'USR-03',
      priority_name: 'Low',
      fiscal_year: 2026,
      account_name: 'Test Account UK',
      assigned_to_name: 'David Lee',
      profile_url: null,
    },
    {
      rid: 'D001-2004',
      r_number: 'CSTK-0000005204',
      task_name: 'Recheck Financials',
      status: 'Due Today',
      effective_start_datetime: '2026-02-10T00:00:00.000Z',
      effective_end_datetime: '2026-02-14T00:00:00.000Z',
      case_r_number: 'CHS-0000000304',
      case_name: 'IE Tax Filing',
      assigned_to: 'USR-04',
      priority_name: 'High',
      fiscal_year: 2026,
      account_name: 'Test Account IE',
      assigned_to_name: 'Aishwarya K',
      profile_url: null,
    },
    {
      rid: 'D001-2005',
      r_number: 'CSTK-0000005205',
      task_name: 'Confirm Project Scope',
      status: 'Overdue',
      effective_start_datetime: '2026-01-30T00:00:00.000Z',
      effective_end_datetime: '2026-02-07T00:00:00.000Z',
      case_r_number: 'CHS-0000000305',
      case_name: 'AU R&D Review',
      assigned_to: 'USR-05',
      priority_name: 'Medium',
      fiscal_year: 2026,
      account_name: 'Test Account AU',
      assigned_to_name: 'Michael Brown',
      profile_url: null,
    },
  ],
};

export const openTasksMock: DashboardTaskResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    {
      rid: 'D001-3001',
      r_number: 'CSTK-0000005301',
      task_name: 'Data Mapping Validation',
      status: 'In Progress',
      effective_start_datetime: '2026-02-06T00:00:00.000Z',
      effective_end_datetime: '2026-02-15T00:00:00.000Z',
      case_r_number: 'CHS-0000000401',
      case_name: 'US Case',
      assigned_to: 'USR-01',
      priority_name: 'High',
      fiscal_year: 2026,
      account_name: 'Test Account US',
      assigned_to_name: 'John Smith',
      profile_url: null,
    },
    {
      rid: 'D001-3002',
      r_number: 'CSTK-0000005302',
      task_name: 'Technical Interview Review',
      status: 'In Progress',
      effective_start_datetime: '2026-02-08T00:00:00.000Z',
      effective_end_datetime: '2026-02-18T00:00:00.000Z',
      case_r_number: 'CHS-0000000402',
      case_name: 'Canada Case',
      assigned_to: 'USR-02',
      priority_name: 'Medium',
      fiscal_year: 2026,
      account_name: 'Test Account CA',
      assigned_to_name: 'Priya N',
      profile_url: null,
    },
    {
      rid: 'D001-3003',
      r_number: 'CSTK-0000005303',
      task_name: 'Expense Categorization',
      status: 'To Do',
      effective_start_datetime: '2026-02-09T00:00:00.000Z',
      effective_end_datetime: '2026-02-20T00:00:00.000Z',
      case_r_number: 'CHS-0000000403',
      case_name: 'UK Case',
      assigned_to: 'USR-03',
      priority_name: 'Low',
      fiscal_year: 2026,
      account_name: 'Test Account UK',
      assigned_to_name: 'David Lee',
      profile_url: null,
    },
    {
      rid: 'D001-3004',
      r_number: 'CSTK-0000005304',
      task_name: 'Client Email Follow-up',
      status: 'To Do',
      effective_start_datetime: '2026-02-10T00:00:00.000Z',
      effective_end_datetime: '2026-02-21T00:00:00.000Z',
      case_r_number: 'CHS-0000000404',
      case_name: 'IE Case',
      assigned_to: 'USR-04',
      priority_name: 'Medium',
      fiscal_year: 2026,
      account_name: 'Test Account IE',
      assigned_to_name: 'Aishwarya K',
      profile_url: null,
    },
  ],
};

export const completedTasksThisWeekMock: DashboardTaskResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Success',
  data: [
    {
      rid: 'D001-4001',
      r_number: 'CSTK-0000005401',
      task_name: 'Final Cost Approval',
      status: 'Completed',
      effective_start_datetime: '2026-02-03T00:00:00.000Z',
      effective_end_datetime: '2026-02-10T00:00:00.000Z',
      case_r_number: 'CHS-0000000501',
      case_name: 'US Case',
      assigned_to: 'USR-01',
      priority_name: 'High',
      fiscal_year: 2026,
      account_name: 'Test Account US',
      assigned_to_name: 'John Smith',
      profile_url: null,
    },
    {
      rid: 'D001-4002',
      r_number: 'CSTK-0000005402',
      task_name: 'Documentation Submission',
      status: 'Completed',
      effective_start_datetime: '2026-02-04T00:00:00.000Z',
      effective_end_datetime: '2026-02-11T00:00:00.000Z',
      case_r_number: 'CHS-0000000502',
      case_name: 'Canada Case',
      assigned_to: 'USR-02',
      priority_name: 'Medium',
      fiscal_year: 2026,
      account_name: 'Test Account CA',
      assigned_to_name: 'Priya N',
      profile_url: null,
    },
    {
      rid: 'D001-4003',
      r_number: 'CSTK-0000005403',
      task_name: 'Audit Confirmation',
      status: 'Completed',
      effective_start_datetime: '2026-02-05T00:00:00.000Z',
      effective_end_datetime: '2026-02-12T00:00:00.000Z',
      case_r_number: 'CHS-0000000503',
      case_name: 'UK Case',
      assigned_to: 'USR-03',
      priority_name: 'Low',
      fiscal_year: 2026,
      account_name: 'Test Account UK',
      assigned_to_name: 'David Lee',
      profile_url: null,
    },
    {
      rid: 'D001-4004',
      r_number: 'CSTK-0000005404',
      task_name: 'Financial Closure',
      status: 'Completed',
      effective_start_datetime: '2026-02-06T00:00:00.000Z',
      effective_end_datetime: '2026-02-13T00:00:00.000Z',
      case_r_number: 'CHS-0000000504',
      case_name: 'AU Case',
      assigned_to: 'USR-05',
      priority_name: 'High',
      fiscal_year: 2026,
      account_name: 'Test Account AU',
      assigned_to_name: 'Michael Brown',
      profile_url: null,
    },
  ],
};
