import {
  ProjectDocumentListResponse,
  ResourceSummaryListResponse,
  ProjectSummaryListResponse,
  QualifiedProjectListResponse,
  DossierSummaryResponse,
} from '../types';

export const ProjectDocumentListMockData: ProjectDocumentListResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Operation completed successfully!',
  data: {
    page: 1,
    limit: 10,
    count: 6,
    projectDocuments: [
      {
        rid: 'D001-65cc9c6a-f5b8-4bd5-abe9-2755d7dabd23',
        r_number: 'TT2P009',
        project_name: 'Virginia Health',
        created_datetime: '2025-12-31T13:13:25.809Z',
        created_by: 'D001-e9c4c4da-27bb-4f82-8f44-1cb9e2931180',
        modified_datetime: null,
        modified_by: null,
        account_rid: 'D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9',
        browse_file:
          'https://developmentthinkrd365sto.blob.core.windows.net/acc-00386/D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9/attachments/1767186805788-AI_License.xlsx',
        document_name: 'AI_License',
        attach_to: 'D001-8ed0b691-44ed-42fc-b046-c94e451ecb54',
        attachment_level: 'project',
        fiscal_year: 2024,
        format: '.xlsx',
        size_in_mb: '0.01 mb',
        document_category_rid: 'D001-fb5ae22d-d664-4e68-9f63-c87c52b7e404',
        document_type_rid: 'D001-0064d632-32ff-419c-a366-e90b503050e0',
        document_category_others: null,
        document_type_others: null,
        comments: null,
        document_type: 'Summary Reports / Executive Briefings',
        document_category: 'Final Submission / Reporting Documents',
        uploaded_by: 'Tamil Dev',
        attached_to: 'Project-TT2P009',
      },
      {
        rid: 'D001-75cc9c6a-f5b8-4bd5-abe9-2755d7dabd24',
        r_number: 'TT2P010',
        project_name: 'Texas Medical',
        created_datetime: '2025-12-30T10:20:15.809Z',
        created_by: 'D001-e9c4c4da-27bb-4f82-8f44-1cb9e2931180',
        modified_datetime: null,
        modified_by: null,
        account_rid: 'D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9',
        browse_file:
          'https://developmentthinkrd365sto.blob.core.windows.net/acc-00386/D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9/attachments/1767186805789-Compliance_Report.pdf',
        document_name: 'Compliance_Report',
        attach_to: 'D001-8ed0b691-44ed-42fc-b046-c94e451ecb55',
        attachment_level: 'project',
        fiscal_year: 2024,
        format: '.pdf',
        size_in_mb: '0.25 mb',
        document_category_rid: 'D001-fb5ae22d-d664-4e68-9f63-c87c52b7e405',
        document_type_rid: 'D001-0064d632-32ff-419c-a366-e90b503050e1',
        document_category_others: null,
        document_type_others: null,
        comments: null,
        document_type: 'Compliance Documents',
        document_category: 'Legal / Regulatory Documents',
        uploaded_by: 'John Smith',
        attached_to: 'Project-TT2P010',
      },
      {
        rid: 'D001-85cc9c6a-f5b8-4bd5-abe9-2755d7dabd25',
        r_number: 'TT2P011',
        project_name: 'California Care',
        created_datetime: '2025-12-29T14:30:45.809Z',
        created_by: 'D001-e9c4c4da-27bb-4f82-8f44-1cb9e2931180',
        modified_datetime: null,
        modified_by: null,
        account_rid: 'D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9',
        browse_file:
          'https://developmentthinkrd365sto.blob.core.windows.net/acc-00386/D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9/attachments/1767186805790-Project_Agreement.docx',
        document_name: 'Project_Agreement',
        attach_to: 'D001-8ed0b691-44ed-42fc-b046-c94e451ecb56',
        attachment_level: 'project',
        fiscal_year: 2024,
        format: '.docx',
        size_in_mb: '0.15 mb',
        document_category_rid: 'D001-fb5ae22d-d664-4e68-9f63-c87c52b7e406',
        document_type_rid: 'D001-0064d632-32ff-419c-a366-e90b503050e2',
        document_category_others: null,
        document_type_others: null,
        comments: null,
        document_type: 'Contracts / Agreements',
        document_category: 'Legal / Regulatory Documents',
        uploaded_by: 'Alice Johnson',
        attached_to: 'Project-TT2P011',
      },
      {
        rid: 'D001-95cc9c6a-f5b8-4bd5-abe9-2755d7dabd26',
        r_number: 'TT2P012',
        project_name: 'New York Labs',
        created_datetime: '2025-12-28T09:15:30.809Z',
        created_by: 'D001-e9c4c4da-27bb-4f82-8f44-1cb9e2931180',
        modified_datetime: null,
        modified_by: null,
        account_rid: 'D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9',
        browse_file:
          'https://developmentthinkrd365sto.blob.core.windows.net/acc-00386/D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9/attachments/1767186805791-Budget_Sheet.xlsx',
        document_name: 'Budget_Sheet',
        attach_to: 'D001-8ed0b691-44ed-42fc-b046-c94e451ecb57',
        attachment_level: 'project',
        fiscal_year: 2024,
        format: '.xlsx',
        size_in_mb: '0.08 mb',
        document_category_rid: 'D001-fb5ae22d-d664-4e68-9f63-c87c52b7e407',
        document_type_rid: 'D001-0064d632-32ff-419c-a366-e90b503050e3',
        document_category_others: null,
        document_type_others: null,
        comments: null,
        document_type: 'Financial Documents',
        document_category: 'Budget / Financial Planning',
        uploaded_by: 'Robert Brown',
        attached_to: 'Project-TT2P012',
      },
      {
        rid: 'D001-a5cc9c6a-f5b8-4bd5-abe9-2755d7dabd27',
        r_number: 'TT2P013',
        project_name: 'Florida Wellness',
        created_datetime: '2025-12-27T16:45:20.809Z',
        created_by: 'D001-e9c4c4da-27bb-4f82-8f44-1cb9e2931180',
        modified_datetime: null,
        modified_by: null,
        account_rid: 'D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9',
        browse_file:
          'https://developmentthinkrd365sto.blob.core.windows.net/acc-00386/D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9/attachments/1767186805792-Roadmap_Presentation.pptx',
        document_name: 'Roadmap_Presentation',
        attach_to: 'D001-8ed0b691-44ed-42fc-b046-c94e451ecb58',
        attachment_level: 'project',
        fiscal_year: 2024,
        format: '.pptx',
        size_in_mb: '0.50 mb',
        document_category_rid: 'D001-fb5ae22d-d664-4e68-9f63-c87c52b7e408',
        document_type_rid: 'D001-0064d632-32ff-419c-a366-e90b503050e4',
        document_category_others: null,
        document_type_others: null,
        comments: null,
        document_type: 'Presentations / Proposals',
        document_category: 'Project Planning Documents',
        uploaded_by: 'Sophia Davis',
        attached_to: 'Project-TT2P013',
      },
      {
        rid: 'D001-b5cc9c6a-f5b8-4bd5-abe9-2755d7dabd28',
        r_number: 'TT2P014',
        project_name: 'Ohio Diagnostics',
        created_datetime: '2025-12-26T11:30:10.809Z',
        created_by: 'D001-e9c4c4da-27bb-4f82-8f44-1cb9e2931180',
        modified_datetime: null,
        modified_by: null,
        account_rid: 'D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9',
        browse_file:
          'https://developmentthinkrd365sto.blob.core.windows.net/acc-00386/D001-f5f3d900-8688-4f17-a578-8ab539f6fdb9/attachments/1767186805793-Audit_Report.pdf',
        document_name: 'Audit_Report',
        attach_to: 'D001-8ed0b691-44ed-42fc-b046-c94e451ecb59',
        attachment_level: 'project',
        fiscal_year: 2024,
        format: '.pdf',
        size_in_mb: '0.35 mb',
        document_category_rid: 'D001-fb5ae22d-d664-4e68-9f63-c87c52b7e409',
        document_type_rid: 'D001-0064d632-32ff-419c-a366-e90b503050e5',
        document_category_others: null,
        document_type_others: null,
        comments: null,
        document_type: 'Audit Reports',
        document_category: 'Final Submission / Reporting Documents',
        uploaded_by: 'Michael Wilson',
        attached_to: 'Project-TT2P014',
      },
    ],
  },
};

export const ProjectSummaryMockData: ProjectSummaryListResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Operation completed successfully!',
  data: {
    count: 5,
    projectSummary: [
      {
        rid: 'D001-proj-sum-001',
        r_number: 'PRJ-001',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-001',
        project_code: 'TT2P009',
        project_name: 'Virginia Health Platform',
        project_type_name: 'Software Development',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Healthcare',
        project_group: 'Digital Health',
        total_effort_prj: 2400,
        total_cost_prj: 250000,
        total_cost_fte_prj: 150000,
        total_cost_subcon_prj: 60000,
        total_cost_nonlabor_prj: 40000,
        assessment_status: 'Completed',
        rd_percent_final: '85%',
        qre_final: '212500',
        comments: 'High priority healthcare project',
        modified_datetime: '2024-12-15T14:30:00Z',
        project_point_of_contact: 'John Smith',
        project_technical_point_of_contact: 'Sarah Johnson',
        currency_symbol: '$',
      },
      {
        rid: 'D001-proj-sum-002',
        r_number: 'PRJ-002',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-002',
        project_code: 'TT2P010',
        project_name: 'Texas Medical System',
        project_type_name: 'System Integration',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Medical',
        project_group: 'Enterprise Systems',
        total_effort_prj: 3200,
        total_cost_prj: 320000,
        total_cost_fte_prj: 180000,
        total_cost_subcon_prj: 90000,
        total_cost_nonlabor_prj: 50000,
        assessment_status: 'In Progress',
        rd_percent_final: '78%',
        qre_final: '249600',
        comments: 'Large scale integration project',
        modified_datetime: '2024-12-10T10:15:00Z',
        project_point_of_contact: 'Michael Brown',
        project_technical_point_of_contact: 'Emily Davis',
        currency_symbol: '$',
      },
      {
        rid: 'D001-proj-sum-003',
        r_number: 'PRJ-003',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-003',
        project_code: 'TT2P011',
        project_name: 'California Care Analytics',
        project_type_name: 'Data Analytics',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Healthcare',
        project_group: 'Analytics',
        total_effort_prj: 2800,
        total_cost_prj: 380000,
        total_cost_fte_prj: 220000,
        total_cost_subcon_prj: 100000,
        total_cost_nonlabor_prj: 60000,
        assessment_status: 'Completed',
        rd_percent_final: '90%',
        qre_final: '342000',
        comments: 'Advanced analytics implementation',
        modified_datetime: '2024-12-05T16:45:00Z',
        project_point_of_contact: 'Robert Wilson',
        project_technical_point_of_contact: 'Jennifer Martinez',
        currency_symbol: '$',
      },
      {
        rid: 'D001-proj-sum-004',
        r_number: 'PRJ-004',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-004',
        project_code: 'TT2P012',
        project_name: 'New York Labs Infrastructure',
        project_type_name: 'Infrastructure',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Laboratory',
        project_group: 'Infrastructure',
        total_effort_prj: 1800,
        total_cost_prj: 280000,
        total_cost_fte_prj: 160000,
        total_cost_subcon_prj: 80000,
        total_cost_nonlabor_prj: 40000,
        assessment_status: 'In Progress',
        rd_percent_final: '72%',
        qre_final: '201600',
        comments: 'Critical infrastructure upgrade',
        modified_datetime: '2024-11-28T09:20:00Z',
        project_point_of_contact: 'David Anderson',
        project_technical_point_of_contact: 'Lisa Thompson',
        currency_symbol: '$',
      },
      {
        rid: 'D001-proj-sum-005',
        r_number: 'PRJ-005',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-005',
        project_code: 'TT2P013',
        project_name: 'Florida Wellness Mobile App',
        project_type_name: 'Mobile Development',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Wellness',
        project_group: 'Mobile Solutions',
        total_effort_prj: 2200,
        total_cost_prj: 290000,
        total_cost_fte_prj: 170000,
        total_cost_subcon_prj: 75000,
        total_cost_nonlabor_prj: 45000,
        assessment_status: 'Completed',
        rd_percent_final: '82%',
        qre_final: '237800',
        comments: 'Innovative mobile health solution',
        modified_datetime: '2024-11-20T13:10:00Z',
        project_point_of_contact: 'Patricia Garcia',
        project_technical_point_of_contact: 'Christopher Lee',
        currency_symbol: '$',
      },
    ],
  },
};

export const QualifiedProjectsMockData: QualifiedProjectListResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Operation completed successfully!',
  data: {
    count: 5,
    qualifiedProjects: [
      {
        rid: 'D001-qual-proj-001',
        r_number: 'QPRJ-001',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-001',
        project_code: 'TT2P015',
        project_name: 'AI Research Platform',
        project_type_name: 'Research & Development',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Technology',
        project_group: 'AI Solutions',
        total_effort_prj: 3500,
        total_cost_prj: 450000,
        total_cost_fte_prj: 280000,
        total_cost_subcon_prj: 120000,
        total_cost_nonlabor_prj: 50000,
        assessment_status: 'Qualified',
        rd_percent_final: '95%',
        qre_final: '427500',
        comments: 'Cutting-edge AI research project',
        modified_datetime: '2024-12-20T15:30:00Z',
        project_point_of_contact: 'Dr. James Wilson',
        project_technical_point_of_contact: 'Dr. Maria Garcia',
        currency_symbol: '$',
      },
      {
        rid: 'D001-qual-proj-002',
        r_number: 'QPRJ-002',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-002',
        project_code: 'TT2P016',
        project_name: 'Quantum Computing Initiative',
        project_type_name: 'Advanced Research',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Science',
        project_group: 'Quantum Tech',
        total_effort_prj: 4200,
        total_cost_prj: 580000,
        total_cost_fte_prj: 350000,
        total_cost_subcon_prj: 150000,
        total_cost_nonlabor_prj: 80000,
        assessment_status: 'Qualified',
        rd_percent_final: '92%',
        qre_final: '533600',
        comments: 'Breakthrough quantum computing research',
        modified_datetime: '2024-12-18T11:45:00Z',
        project_point_of_contact: 'Prof. Richard Chen',
        project_technical_point_of_contact: 'Dr. Susan Miller',
        currency_symbol: '$',
      },
      {
        rid: 'D001-qual-proj-003',
        r_number: 'QPRJ-003',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-003',
        project_code: 'TT2P017',
        project_name: 'Biotech Innovation Lab',
        project_type_name: 'Biotechnology',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Healthcare',
        project_group: 'Biotech',
        total_effort_prj: 3800,
        total_cost_prj: 520000,
        total_cost_fte_prj: 310000,
        total_cost_subcon_prj: 140000,
        total_cost_nonlabor_prj: 70000,
        assessment_status: 'Qualified',
        rd_percent_final: '88%',
        qre_final: '457600',
        comments: 'Innovative biotechnology research',
        modified_datetime: '2024-12-15T09:20:00Z',
        project_point_of_contact: 'Dr. Amanda Taylor',
        project_technical_point_of_contact: 'Dr. Kevin Brown',
        currency_symbol: '$',
      },
      {
        rid: 'D001-qual-proj-004',
        r_number: 'QPRJ-004',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-004',
        project_code: 'TT2P018',
        project_name: 'Clean Energy Solutions',
        project_type_name: 'Energy Research',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Energy',
        project_group: 'Renewable Energy',
        total_effort_prj: 3200,
        total_cost_prj: 480000,
        total_cost_fte_prj: 290000,
        total_cost_subcon_prj: 130000,
        total_cost_nonlabor_prj: 60000,
        assessment_status: 'Qualified',
        rd_percent_final: '90%',
        qre_final: '432000',
        comments: 'Sustainable energy research project',
        modified_datetime: '2024-12-12T14:10:00Z',
        project_point_of_contact: 'Dr. Thomas Anderson',
        project_technical_point_of_contact: 'Dr. Lisa Martinez',
        currency_symbol: '$',
      },
      {
        rid: 'D001-qual-proj-005',
        r_number: 'QPRJ-005',
        account_rid: 'D001-account-001',
        project_rid: 'D001-project-005',
        project_code: 'TT2P019',
        project_name: 'Advanced Materials Research',
        project_type_name: 'Materials Science',
        classification_name: 'R&D',
        fiscal_year: 2024,
        project_classification_rid: 'D001-class-001',
        project_classification_name: 'Research & Development',
        project_client_group: 'Manufacturing',
        project_group: 'Materials',
        total_effort_prj: 2900,
        total_cost_prj: 420000,
        total_cost_fte_prj: 250000,
        total_cost_subcon_prj: 110000,
        total_cost_nonlabor_prj: 60000,
        assessment_status: 'Qualified',
        rd_percent_final: '93%',
        qre_final: '390600',
        comments: 'Next-generation materials development',
        modified_datetime: '2024-12-08T16:55:00Z',
        project_point_of_contact: 'Dr. Daniel Lee',
        project_technical_point_of_contact: 'Dr. Rachel White',
        currency_symbol: '$',
      },
    ],
  },
};

export const DossierSummaryMockData: DossierSummaryResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Operation completed successfully!',
  data: {
    dossierSummary: {
      title: 'TechM USA 2024 - Dossier',
      account_name: 'TechM',
      country_name: 'USA',
      fiscal_year: 2024,
      company_overview: [
        {
          title: 'Company Background',
          summary: `TechM is a leading global technology company specializing in digital transformation, cloud solutions, and enterprise software development. Founded in 2010, the company has grown to serve over 500 Fortune 1000 clients across various industries including healthcare, finance, manufacturing, and retail.

With offices in 25 countries and a workforce of over 15,000 professionals, TechM maintains a strong global presence while delivering localized solutions. The company has consistently achieved year-over-year revenue growth of 20%+ and maintains a client retention rate of 95%.`,
        },
        {
          title: 'Core Competencies',
          summary: `* **Digital Transformation**: End-to-end digital transformation services helping businesses modernize their operations
* **Cloud Solutions**: Expertise in AWS, Azure, and Google Cloud Platform
* **AI & Machine Learning**: Advanced analytics and AI-driven solutions
* **Cybersecurity**: Comprehensive security solutions and compliance services`,
        },
        {
          title: 'Innovation Focus',
          summary: `TechM invests heavily in R&D, allocating approximately 15% of annual revenue to research and development activities. This commitment to innovation has resulted in numerous patents and industry-leading solutions in areas such as:

* Quantum computing
* Blockchain technology
* Advanced AI applications
* Edge computing solutions
* Next-generation cybersecurity`,
        },
      ],
      overall_projects_summary: [
        {
          title: 'Portfolio Overview',
          summary: `During fiscal year 2024, TechM executed a comprehensive portfolio of R&D projects totaling $2.5M in qualified research expenditures. The project portfolio demonstrates significant innovation across multiple technology domains.

**Key Statistics:**
* Total Projects: 15 qualified R&D projects
* Total QRE: $2,500,000
* Average Project Duration: 8-12 months
* Success Rate: 87% of projects met or exceeded technical objectives`,
        },
        {
          title: 'Project Categories',
          summary: `**Software Development (40%)**
Advanced software engineering projects focusing on next-generation platforms:
* AI-powered healthcare diagnostic systems
* Quantum computing algorithms
* Blockchain-based supply chain solutions

**Data Analytics & AI (30%)**
Machine learning and data science initiatives:
* Predictive analytics for financial services
* Natural language processing for customer service automation
* Computer vision applications for manufacturing quality control

**Infrastructure & Cloud (20%)**
Cloud architecture and infrastructure modernization:
* Hybrid cloud migration frameworks
* Edge computing solutions
* Serverless architecture implementations

**Emerging Technologies (10%)**
Exploratory research in cutting-edge technologies:
* Quantum cryptography
* Advanced materials for semiconductor manufacturing
* Biotechnology applications`,
        },
        {
          title: 'Geographic Distribution',
          summary: `Projects were conducted across multiple US locations:
* **California**: 35% (focus on AI/ML and cloud solutions)
* **Texas**: 25% (healthcare and enterprise systems)
* **New York**: 20% (financial technology)
* **Florida**: 15% (mobile and wellness applications)
* **Other**: 5%`,
        },
        {
          title: 'Key Achievements',
          summary: `* Successfully completed 13 out of 15 projects on time and within budget
* Filed 8 patent applications for innovative solutions developed during FY 2024
* Achieved 92% average QRE qualification rate across all projects
* Implemented new documentation standards improving audit readiness by 40%
* Established cross-functional R&D teams increasing collaboration efficiency by 35%`,
        },
      ],
      assessment_methodology: `All projects were evaluated using the four-part test criteria (Permitted Purpose, Elimination of Uncertainty, Process of Experimentation, and Technological Information) in compliance with IRC Section 41 requirements. Comprehensive documentation standards were maintained including technical design documents, time tracking, and financial records. Multi-level technical reviews and compliance checks ensured accuracy and audit readiness.`,
    },
  },
};

export const ResourceSummaryMockData: ResourceSummaryListResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Operation completed successfully!',
  data: {
    count: 5,
    resourceSummary: [
      {
        rid: 'D001-res-001-uuid',
        r_number: 'PR-RES-001',
        resource_code: 'RES-001',
        project_resource_code: 'PR-RES-001',
        resource_name: 'John Doe',
        resource_firstname: 'John',
        resource_lastname: 'Doe',
        resource_type_name: 'FTE',
        resource_type_rid: 'D001-type-fte',
        designation: 'Senior Developer',
        resource_role: 'Technical Lead',
        resource_orgname: 'Tech Solutions Inc',
        project_rid: 'D001-proj-001',
        project_code: 'TT2P009',
        project_name: 'Virginia Health',
        project_resource_role: 'Lead Developer',
        country_rid: 'D001-country-us',
        country_name: 'United States',
        country_code: 'US',
        region_rid: 'D001-region-east',
        region_name: 'East',
        city_rid: 'D001-city-ny',
        city_name: 'New York',
        currency_rid: 'D001-currency-usd',
        currency_name: 'US Dollar',
        currency_symbol: '$',
        resource_startdate: '2024-01-01',
        resource_enddate: '2024-12-31',
        resource_total_experience: 8,
        resource_total_experience_organization: 5,
        total_hours_pro_res: 1600,
        total_cost_pro_res: 120000,
        net_total_cost_pro_res: 115000,
        effort_project_resource_level: 80,
        cost_project_resource_level: 85,
        qre_final: 92000,
        qre_percent: 80,
        salary: 100000,
        bonus: 10000,
        insurance: 5000,
        deductions: 5000,
        status_rid: 'D001-status-active',
        status_name: 'Active',
        comments: null,
        description: 'Primary developer for the project',
        account_rid: 'D001-account-001',
        created_by: 'D001-user-001',
        modified_by: 'D001-user-001',
        created_datetime: '2024-01-01T10:00:00Z',
        modified_datetime: '2024-01-15T14:30:00Z',
        fiscal_year: 2024,
        project_fiscal_rid: 'D001-fiscal-2024',
        resource_rid: 'D001-resource-001',
        account_number: 'ACC-001',
        assigned_skill_role_type_rid: null,
        skill_role_rid: null,
        skill_role_others: null,
      },
      {
        rid: 'D001-res-002-uuid',
        r_number: 'PR-RES-002',
        resource_code: 'RES-002',
        project_resource_code: 'PR-RES-002',
        resource_name: 'Alice Johnson',
        resource_firstname: 'Alice',
        resource_lastname: 'Johnson',
        resource_type_name: 'Sub Con',
        resource_type_rid: 'D001-type-subcon',
        designation: 'QA Engineer',
        resource_role: 'Quality Assurance',
        resource_orgname: 'Quality First LLC',
        project_rid: 'D001-proj-002',
        project_code: 'TT2P010',
        project_name: 'Texas Medical',
        project_resource_role: 'QA Lead',
        country_rid: 'D001-country-us',
        country_name: 'United States',
        country_code: 'US',
        region_rid: 'D001-region-south',
        region_name: 'South',
        city_rid: 'D001-city-austin',
        city_name: 'Austin',
        currency_rid: 'D001-currency-usd',
        currency_name: 'US Dollar',
        currency_symbol: '$',
        resource_startdate: '2024-02-01',
        resource_enddate: '2024-11-30',
        resource_total_experience: 6,
        resource_total_experience_organization: 3,
        total_hours_pro_res: 1400,
        total_cost_pro_res: 95000,
        net_total_cost_pro_res: 90000,
        effort_project_resource_level: 75,
        cost_project_resource_level: 80,
        qre_final: 67500,
        qre_percent: 75,
        salary: 80000,
        bonus: 8000,
        insurance: 4000,
        deductions: 3000,
        status_rid: 'D001-status-active',
        status_name: 'Active',
        comments: null,
        description: 'QA specialist for medical systems',
        account_rid: 'D001-account-001',
        created_by: 'D001-user-002',
        modified_by: 'D001-user-002',
        created_datetime: '2024-02-01T09:00:00Z',
        modified_datetime: '2024-02-10T11:20:00Z',
        fiscal_year: 2024,
        project_fiscal_rid: 'D001-fiscal-2024',
        resource_rid: 'D001-resource-002',
        account_number: 'ACC-001',
        assigned_skill_role_type_rid: null,
        skill_role_rid: null,
        skill_role_others: null,
      },
      {
        rid: 'D001-res-003-uuid',
        r_number: 'PR-RES-003',
        resource_code: 'RES-003',
        project_resource_code: 'PR-RES-003',
        resource_name: 'Robert Brown',
        resource_firstname: 'Robert',
        resource_lastname: 'Brown',
        resource_type_name: 'Consultant',
        resource_type_rid: 'D001-type-consultant',
        designation: 'Solutions Architect',
        resource_role: 'Architecture',
        resource_orgname: 'Arch Consulting Group',
        project_rid: 'D001-proj-003',
        project_code: 'TT2P011',
        project_name: 'California Care',
        project_resource_role: 'Chief Architect',
        country_rid: 'D001-country-us',
        country_name: 'United States',
        country_code: 'US',
        region_rid: 'D001-region-west',
        region_name: 'West',
        city_rid: 'D001-city-sf',
        city_name: 'San Francisco',
        currency_rid: 'D001-currency-usd',
        currency_name: 'US Dollar',
        currency_symbol: '$',
        resource_startdate: '2024-03-01',
        resource_enddate: '2024-12-31',
        resource_total_experience: 12,
        resource_total_experience_organization: 7,
        total_hours_pro_res: 1800,
        total_cost_pro_res: 180000,
        net_total_cost_pro_res: 175000,
        effort_project_resource_level: 90,
        cost_project_resource_level: 95,
        qre_final: 143500,
        qre_percent: 82,
        salary: 150000,
        bonus: 20000,
        insurance: 7000,
        deductions: 8000,
        status_rid: 'D001-status-active',
        status_name: 'Active',
        comments: null,
        description: 'Senior architect for healthcare solutions',
        account_rid: 'D001-account-001',
        created_by: 'D001-user-003',
        modified_by: 'D001-user-003',
        created_datetime: '2024-03-01T08:30:00Z',
        modified_datetime: '2024-03-05T16:45:00Z',
        fiscal_year: 2024,
        project_fiscal_rid: 'D001-fiscal-2024',
        resource_rid: 'D001-resource-003',
        account_number: 'ACC-001',
        assigned_skill_role_type_rid: null,
        skill_role_rid: null,
        skill_role_others: null,
      },
      {
        rid: 'D001-res-004-uuid',
        r_number: 'PR-RES-004',
        resource_code: 'RES-004',
        project_resource_code: 'PR-RES-004',
        resource_name: 'Sophia Davis',
        resource_firstname: 'Sophia',
        resource_lastname: 'Davis',
        resource_type_name: 'FTE',
        resource_type_rid: 'D001-type-fte',
        designation: 'Data Analyst',
        resource_role: 'Analytics',
        resource_orgname: 'Data Insights Corp',
        project_rid: 'D001-proj-004',
        project_code: 'TT2P012',
        project_name: 'New York Labs',
        project_resource_role: 'Senior Analyst',
        country_rid: 'D001-country-us',
        country_name: 'United States',
        country_code: 'US',
        region_rid: 'D001-region-north',
        region_name: 'North',
        city_rid: 'D001-city-boston',
        city_name: 'Boston',
        currency_rid: 'D001-currency-usd',
        currency_name: 'US Dollar',
        currency_symbol: '$',
        resource_startdate: '2024-01-15',
        resource_enddate: '2024-10-31',
        resource_total_experience: 5,
        resource_total_experience_organization: 2,
        total_hours_pro_res: 1300,
        total_cost_pro_res: 85000,
        net_total_cost_pro_res: 82000,
        effort_project_resource_level: 70,
        cost_project_resource_level: 75,
        qre_final: 57400,
        qre_percent: 70,
        salary: 75000,
        bonus: 6000,
        insurance: 3500,
        deductions: 2500,
        status_rid: 'D001-status-active',
        status_name: 'Active',
        comments: null,
        description: 'Data analysis and reporting specialist',
        account_rid: 'D001-account-001',
        created_by: 'D001-user-004',
        modified_by: 'D001-user-004',
        created_datetime: '2024-01-15T10:15:00Z',
        modified_datetime: '2024-01-20T13:30:00Z',
        fiscal_year: 2024,
        project_fiscal_rid: 'D001-fiscal-2024',
        resource_rid: 'D001-resource-004',
        account_number: 'ACC-001',
        assigned_skill_role_type_rid: null,
        skill_role_rid: null,
        skill_role_others: null,
      },
      {
        rid: 'D001-res-005-uuid',
        r_number: 'PR-RES-005',
        resource_code: 'RES-005',
        project_resource_code: 'PR-RES-005',
        resource_name: 'Michael Wilson',
        resource_firstname: 'Michael',
        resource_lastname: 'Wilson',
        resource_type_name: 'Sub Con',
        resource_type_rid: 'D001-type-subcon',
        designation: 'DevOps Engineer',
        resource_role: 'Infrastructure',
        resource_orgname: 'Cloud Ops Solutions',
        project_rid: 'D001-proj-005',
        project_code: 'TT2P013',
        project_name: 'Florida Wellness',
        project_resource_role: 'DevOps Lead',
        country_rid: 'D001-country-us',
        country_name: 'United States',
        country_code: 'US',
        region_rid: 'D001-region-south',
        region_name: 'South',
        city_rid: 'D001-city-miami',
        city_name: 'Miami',
        currency_rid: 'D001-currency-usd',
        currency_name: 'US Dollar',
        currency_symbol: '$',
        resource_startdate: '2024-02-15',
        resource_enddate: '2024-12-15',
        resource_total_experience: 7,
        resource_total_experience_organization: 4,
        total_hours_pro_res: 1500,
        total_cost_pro_res: 110000,
        net_total_cost_pro_res: 105000,
        effort_project_resource_level: 78,
        cost_project_resource_level: 82,
        qre_final: 81900,
        qre_percent: 78,
        salary: 95000,
        bonus: 9000,
        insurance: 4500,
        deductions: 3500,
        status_rid: 'D001-status-active',
        status_name: 'Active',
        comments: null,
        description: 'Infrastructure and deployment specialist',
        account_rid: 'D001-account-001',
        created_by: 'D001-user-005',
        modified_by: 'D001-user-005',
        created_datetime: '2024-02-15T11:00:00Z',
        modified_datetime: '2024-02-20T15:20:00Z',
        fiscal_year: 2024,
        project_fiscal_rid: 'D001-fiscal-2024',
        resource_rid: 'D001-resource-005',
        account_number: 'ACC-001',
        assigned_skill_role_type_rid: null,
        skill_role_rid: null,
        skill_role_others: null,
      },
    ],
  },
};
