import {
  ProjectDocumentListResponse,
  ResourceSummaryListResponse,
  ProjectSummaryListResponse,
} from '../types';

export const ProjectDocumentListMockData: ProjectDocumentListResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Operation completed successfully!',
  data: {
    page: 1,
    limit: 10,
    count: 6,
    projectDocuments: [
      {
        rid: 'DOC-RID-001',
        r_number: 'TT2P009',
        project_ref_id: 'Y.LL2100234',
        project_name: 'Virginia Health',
        document_number: 'DOC0011002',
        document_type: '.xlsx',
        document_name: 'AI_License',
      },
      {
        rid: 'DOC-RID-002',
        r_number: 'TT2P010',
        project_ref_id: 'Y.LL2100235',
        project_name: 'Texas Medical',
        document_number: 'DOC0011003',
        document_type: '.pdf',
        document_name: 'Compliance_Report',
      },
      {
        rid: 'DOC-RID-003',
        r_number: 'TT2P011',
        project_ref_id: 'Y.LL2100236',
        project_name: 'California Care',
        document_number: 'DOC0011004',
        document_type: '.docx',
        document_name: 'Project_Agreement',
      },
      {
        rid: 'DOC-RID-004',
        r_number: 'TT2P012',
        project_ref_id: 'Y.LL2100237',
        project_name: 'New York Labs',
        document_number: 'DOC0011005',
        document_type: '.xlsx',
        document_name: 'Budget_Sheet',
      },
      {
        rid: 'DOC-RID-005',
        r_number: 'TT2P013',
        project_ref_id: 'Y.LL2100238',
        project_name: 'Florida Wellness',
        document_number: 'DOC0011006',
        document_type: '.pptx',
        document_name: 'Roadmap_Presentation',
      },
      {
        rid: 'DOC-RID-006',
        r_number: 'TT2P014',
        project_ref_id: 'Y.LL2100239',
        project_name: 'Ohio Diagnostics',
        document_number: 'DOC0011007',
        document_type: '.pdf',
        document_name: 'Audit_Report',
      },
    ],
  },
};

export const ProjectSummaryMockData: ProjectSummaryListResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Operation completed successfully!',
  data: {
    count: 5,
    projectSummary: [
      {
        rid: 'PROJ-SUM-001',
        r_number: 'TT2P009',
        project_ref_id: 'Y.LL2100234',
        project_name: 'Virginia Health',
        fte_cost: '$1,002',
        sub_con_cost: '$2,123',
        non_labour_cost: '$12,142',
        project_cost: '$422',
        rd_percentage: '80%',
        project_qre: '$11,213',
        rd_credit: '$32,323',
      },
      {
        rid: 'PROJ-SUM-002',
        r_number: 'TT2P010',
        project_ref_id: 'Y.LL2100235',
        project_name: 'Texas Medical',
        fte_cost: '$1,850',
        sub_con_cost: '$3,120',
        non_labour_cost: '$14,200',
        project_cost: '$520',
        rd_percentage: '75%',
        project_qre: '$13,590',
        rd_credit: '$28,740',
      },
      {
        rid: 'PROJ-SUM-003',
        r_number: 'TT2P011',
        project_ref_id: 'Y.LL2100236',
        project_name: 'California Care',
        fte_cost: '$2,150',
        sub_con_cost: '$4,200',
        non_labour_cost: '$18,600',
        project_cost: '$610',
        rd_percentage: '82%',
        project_qre: '$18,327',
        rd_credit: '$40,120',
      },
      {
        rid: 'PROJ-SUM-004',
        r_number: 'TT2P012',
        project_ref_id: 'Y.LL2100237',
        project_name: 'New York Labs',
        fte_cost: '$1,650',
        sub_con_cost: '$2,890',
        non_labour_cost: '$13,400',
        project_cost: '$480',
        rd_percentage: '70%',
        project_qre: '$11,480',
        rd_credit: '$25,600',
      },
      {
        rid: 'PROJ-SUM-005',
        r_number: 'TT2P013',
        project_ref_id: 'Y.LL2100238',
        project_name: 'Florida Wellness',
        fte_cost: '$1,950',
        sub_con_cost: '$3,500',
        non_labour_cost: '$15,900',
        project_cost: '$560',
        rd_percentage: '78%',
        project_qre: '$15,483',
        rd_credit: '$31,250',
      },
    ],
  },
};

export const ResourceSummaryMockData: ResourceSummaryListResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Operation completed successfully!',
  data: {
    count: 5,
    resourceSummary: [
      {
        rid: 'RES-SUM-001',
        r_number: 'TT2P009',
        project_ref_id: 'Y.LL2100234',
        project_name: 'Virginia Health',
        resource_ref_id: 'RES3100234',
        resource_name: 'John',
        resource_type: 'Sub Con',
        country_region: 'US - East',
        cost: '$12,142',
        rd_percentage: '80%',
        qre: '$11,213',
        rd_credit: '$32,323',
      },
      {
        rid: 'RES-SUM-002',
        r_number: 'TT2P010',
        project_ref_id: 'Y.LL2100235',
        project_name: 'Texas Medical',
        resource_ref_id: 'RES3100235',
        resource_name: 'Alice',
        resource_type: 'FTE',
        country_region: 'US - South',
        cost: '$18,120',
        rd_percentage: '75%',
        qre: '$13,590',
        rd_credit: '$28,740',
      },
      {
        rid: 'RES-SUM-003',
        r_number: 'TT2P011',
        project_ref_id: 'Y.LL2100236',
        project_name: 'California Care',
        resource_ref_id: 'RES3100236',
        resource_name: 'Robert',
        resource_type: 'Sub Con',
        country_region: 'US - West',
        cost: '$22,350',
        rd_percentage: '82%',
        qre: '$18,327',
        rd_credit: '$40,120',
      },
      {
        rid: 'RES-SUM-004',
        r_number: 'TT2P012',
        project_ref_id: 'Y.LL2100237',
        project_name: 'New York Labs',
        resource_ref_id: 'RES3100237',
        resource_name: 'Sophia',
        resource_type: 'FTE',
        country_region: 'US - North',
        cost: '$16,400',
        rd_percentage: '70%',
        qre: '$11,480',
        rd_credit: '$25,600',
      },
      {
        rid: 'RES-SUM-005',
        r_number: 'TT2P013',
        project_ref_id: 'Y.LL2100238',
        project_name: 'Florida Wellness',
        resource_ref_id: 'RES3100238',
        resource_name: 'Michael',
        resource_type: 'Consultant',
        country_region: 'US - South',
        cost: '$19,850',
        rd_percentage: '78%',
        qre: '$15,483',
        rd_credit: '$31,250',
      },
    ],
  },
};
