export const mockData = {
  statusCode: 200,
  statusCodeValue: 'OK',
  statusMessage: 'OK',
  data: {
    count: 3,
    projectResources: [
      {
        project_rid: 'D001-de8be79a-4d13-4f96-aa68-0c878bec4cc3',
        account_rid: 'D001-64ad097e-8093-4680-9bfc-ab1587a2b75b',
        resource_name: null,
        resource_code: 'RCODE-001',
        resource_type_rid: 'D001-82794940-384c-47b6-a91f-84926f219606',
        resource_orgname: 'Hubino',
        designation: null,
        resource_role: 'Developer',
        assigned_skill_role_type_rid: null,
        skill_role_rid: null,
        skill_role_others: null,
        status_rid: null,
        country_rid: null,
        region_rid: 'D001-f14309d6-eb10-4f5a-b3d0-8b540197a54f',
        currency_rid: null,
        start_date: null,
        end_date: null,
        total_hours_pro_res: '150',
        total_cost_pro_res: '3000',
        salary: null,
        bonus: null,
        insurance: null,
        deductions: null,
        description: null,
      },
      {
        project_rid: 'D001-a12b3c4d-1111-2222-3333-abcabcabcabc',
        account_rid: 'D001-b21a4321-aaaa-bbbb-cccc-defdefdefdef',
        resource_name: 'Jane Smith',
        resource_code: 'RCODE-002',
        resource_type_rid: 'D001-ffeeddcc-bbaa-9988-7766-554433221100',
        resource_orgname: 'Certainti',
        designation: 'Analyst',
        resource_role: 'Business Analyst',
        assigned_skill_role_type_rid: null,
        skill_role_rid: 'D001-aaaabbbb-cccc-dddd-eeeeeeeeeeee',
        skill_role_others: null,
        status_rid: 'D001-status-001',
        country_rid: 'D001-country-002',
        region_rid: 'D001-region-002',
        currency_rid: 'D001-currency-002',
        start_date: '2024-01-01',
        end_date: '2024-12-31',
        total_hours_pro_res: '120',
        total_cost_pro_res: '2400',
        salary: '4000',
        bonus: '500',
        insurance: '300',
        deductions: '200',
        description: 'Support for Q1-Q4 project phases',
      },
      {
        project_rid: 'D001-c34d56ef-4444-5555-6666-xyzxyzxyzxyz',
        account_rid: 'D001-cba321cb-dddd-eeee-ffff-123412341234',
        resource_name: 'Amit Kumar',
        resource_code: 'RCODE-003',
        resource_type_rid: 'D001-type-003',
        resource_orgname: 'Zoho Corp',
        designation: 'QA Engineer',
        resource_role: 'Tester',
        assigned_skill_role_type_rid: 'D001-skill-type-003',
        skill_role_rid: null,
        skill_role_others: 'Automation',
        status_rid: 'D001-status-003',
        country_rid: 'D001-country-003',
        region_rid: 'D001-region-003',
        currency_rid: 'D001-currency-003',
        start_date: '2025-04-01',
        end_date: '2025-10-31',
        total_hours_pro_res: '200',
        total_cost_pro_res: '6000',
        salary: '5000',
        bonus: null,
        insurance: null,
        deductions: null,
        description: 'Test automation and bug tracking',
      },
    ],
  },
};

export const resourceDetails = {
  statusCode: 200,
  statusCodeValue: 'OK',
  statusMessage: 'OK',
  data: {
    projectResourceDetails: {
      id: '2323432',
      project_resource_number: 'PRS0001',
      project_name: 'Project 1',
      project_id: '122fef23',
      resource_code: '122fef23',
      resource_full_name: 'John Doe',
      resource_type: 'Full-Time',
      resource_org_name: 'Hubino',
      resource_role: 'Developer',
      status: 'active',
      country: 'USA',
      region: 'chicago',
      currency: 'YEN',
      resource_effective_from: '2023-01-01',
      resource_effective_enddate: '2023-01-01',
      designation: 'Developer',
      effort: 1212,
      cost: '122',
      financeEffort: 1212,
      description: 'Developer',
    },
  },
};
