import { KanbanColumn, User } from './types';

export const mockUserData: User[] = [
  { id: '1', name: 'John Doe', initials: 'JD', color: '#3B82F6' },
  { id: '2', name: 'Jane Smith', initials: 'JS', color: '#10B981' },
  { id: '3', name: 'Mike Johnson', initials: 'MJ', color: '#F59E0B' },
  { id: '4', name: 'Sarah Wilson', initials: 'SW', color: '#EF4444' },
  { id: '5', name: 'David Brown', initials: 'DB', color: '#8B5CF6' },
];

export const mockKanbanData: KanbanColumn[] = [
  {
    id: 'todo',
    name: 'To Do',
    taskCount: 3,
    tasks: [
      {
        id: 'task-1',
        title: 'Design homepage wireframes',
        description:
          'Create wireframes for the new homepage design including mobile responsive layouts',
        status: 'To Do',
        priority: 'High',
        assignee: {
          name: 'John Doe',
          initials: 'JD',
          color: '#3B82F6',
        },
        collaborators: [
          {
            name: 'Jane Smith',
            initials: 'JS',
            color: '#10B981',
          },
        ],
        tags: ['Design', 'UI/UX'],
        startDate: new Date('2025-11-01'),
        endDate: new Date('2025-11-15'),
        attachments: ['wireframe-v1.pdf', 'design-specs.figma'],
        commentCount: 5,
        createdAt: new Date('2025-10-28'),
        checklist: [
          {
            id: '1-1',
            text: 'Research current design trends',
            completed: true,
          },
          { id: '1-2', text: 'Create mobile wireframes', completed: false },
          { id: '1-3', text: 'Design desktop layout', completed: false },
          { id: '1-4', text: 'Review with stakeholders', completed: false },
          { id: '1-5', text: 'Create interactive prototype', completed: false },
          { id: '1-6', text: 'Test navigation flow', completed: false },
        ],
        activities: [
          {
            id: 'task-1-activity-1',
            user: 'John Doe',
            action: 'created this task',
            date: '3 days ago',
          },
          {
            id: 'task-1-activity-2',
            user: 'Jane Smith',
            action: 'added this task to',
            link: 'Project Management',
            date: '2 days ago',
          },
          {
            id: 'task-1-activity-3',
            user: 'John Doe',
            action: 'set the priority to High',
            date: '1 day ago',
          },
        ],
      },
      {
        id: 'task-2',
        title: 'Set up development environment',
        description:
          'Configure local development environment with all necessary tools and dependencies',
        status: 'To Do',
        priority: 'Medium',
        assignee: {
          name: 'Mike Johnson',
          initials: 'MJ',
          color: '#F59E0B',
        },
        tags: ['Development', 'Setup'],
        commentCount: 2,
        createdAt: new Date('2025-10-30'),
        checklist: [
          { id: '2-1', text: 'Install Node.js and npm', completed: true },
          {
            id: '2-2',
            text: 'Set up code editor with extensions',
            completed: true,
          },
          { id: '2-3', text: 'Configure Git repository', completed: false },
          { id: '2-4', text: 'Install project dependencies', completed: false },
          { id: '2-5', text: 'Set up database connection', completed: false },
          {
            id: '2-6',
            text: 'Configure environment variables',
            completed: false,
          },
          { id: '2-7', text: 'Test development server', completed: false },
          { id: '3-1', text: 'Identify top 5 competitors', completed: false },
          { id: '3-2', text: 'Analyze competitor features', completed: false },
          { id: '3-3', text: 'Document pricing strategies', completed: false },
          { id: '3-4', text: 'Review user feedback', completed: false },
          { id: '3 -5', text: 'Create comparison matrix', completed: false },
        ],
        activities: [
          {
            id: 'task-2-activity-1',
            user: 'Mike Johnson',
            action: 'created this task',
            date: '4 days ago',
          },
          {
            id: 'task-2-activity-2',
            user: 'David Brown',
            action: 'added development requirements',
            date: '2 days ago',
          },
        ],
      },
      {
        id: 'task-3',
        title: 'Research competitor analysis',
        status: 'To Do',
        priority: 'Low',
        assignee: {
          name: 'Sarah Wilson',
          initials: 'SW',
          color: '#EF4444',
        },
        commentCount: 1,
        createdAt: new Date('2025-11-01'),
        checklist: [
          //  { id: '3-1', text: 'Identify top 5 competitors', completed: false },
          //   { id: '3-2', text: 'Analyze competitor features', completed: false },
          //   { id: '3-3', text: 'Document pricing strategies', completed: false },
          //   { id: '3-4', text: 'Review user feedback', completed: false },
          //   { id: '3 -5', text: 'Create comparison matrix', completed: false },
        ],
        activities: [
          {
            id: 'task-3-activity-1',
            user: 'Sarah Wilson',
            action: 'created this task',
            date: '2 days ago',
          },
          {
            id: 'task-3-activity-2',
            user: 'John Doe',
            action: 'added research guidelines',
            date: '1 day ago',
          },
          {
            id: 'task-3-activity-3',
            user: 'Sarah Wilson',
            action: 'started competitor research',
            date: '4 hours ago',
          },
        ],
      },
    ],
  },
  {
    id: 'in-progress',
    name: 'In Progress',
    taskCount: 2,
    tasks: [
      {
        id: 'task-4',
        title: 'Implement user authentication',
        description:
          'Build secure user authentication system with JWT tokens and password encryption',
        status: 'In Progress',
        priority: 'High',
        assignee: {
          name: 'David Brown',
          initials: 'DB',
          color: '#8B5CF6',
        },
        collaborators: [
          {
            name: 'John Doe',
            initials: 'JD',
            color: '#3B82F6',
          },
          {
            name: 'Mike Johnson',
            initials: 'MJ',
            color: '#F59E0B',
          },
        ],
        tags: ['Backend', 'Security'],
        startDate: new Date('2025-10-25'),
        endDate: new Date('2025-11-10'),
        attachments: ['auth-flow.png'],
        commentCount: 8,
        createdAt: new Date('2025-10-25'),
        checklist: [
          {
            id: '4-1',
            text: 'Review technical specifications',
            completed: true,
          },
          { id: '4-2', text: 'Set up JWT token generation', completed: true },
          { id: '4-3', text: 'Implement password encryption', completed: true },
          { id: '4-4', text: 'Create login API endpoint', completed: false },
          {
            id: '4-5',
            text: 'Add token validation middleware',
            completed: false,
          },
          { id: '4-6', text: 'Test authentication flow', completed: false },
          {
            id: '4-7',
            text: 'Add password reset functionality',
            completed: false,
          },
          { id: '4-8', text: 'Implement session management', completed: false },
        ],
        activities: [
          {
            id: 'task-4-activity-1',
            user: 'David Brown',
            action: 'created this task',
            date: '9 days ago',
          },
          {
            id: 'task-4-activity-2',
            user: 'John Doe',
            action: 'added this task to',
            link: 'Security Sprint',
            date: '8 days ago',
          },
          {
            id: 'task-4-activity-3',
            user: 'Mike Johnson',
            action: 'added JWT implementation notes',
            date: '5 days ago',
          },
          {
            id: 'task-4-activity-4',
            user: 'David Brown',
            action: 'moved to In Progress',
            date: '3 days ago',
          },
        ],
      },
      {
        id: 'task-5',
        title: 'Create product landing page',
        status: 'In Progress',
        priority: 'Medium',
        assignee: {
          name: 'Jane Smith',
          initials: 'JS',
          color: '#10B981',
        },
        tags: ['Frontend', 'Marketing'],
        commentCount: 3,
        createdAt: new Date('2025-10-28'),
        checklist: [
          { id: '5-1', text: 'Design landing page layout', completed: true },
          { id: '5-2', text: 'Create hero section', completed: true },
          { id: '5-3', text: 'Add product features section', completed: false },
          { id: '5-4', text: 'Implement contact form', completed: false },
          { id: '5-5', text: 'Add testimonials section', completed: false },
          { id: '5-6', text: 'Optimize for mobile devices', completed: false },
        ],
        activities: [
          {
            id: 'task-5-activity-1',
            user: 'Jane Smith',
            action: 'created this task',
            date: '6 days ago',
          },
          {
            id: 'task-5-activity-2',
            user: 'Sarah Wilson',
            action: 'provided marketing content',
            date: '4 days ago',
          },
          {
            id: 'task-5-activity-3',
            user: 'Jane Smith',
            action: 'started page development',
            date: '2 days ago',
          },
        ],
      },
    ],
  },
  {
    id: 'done',
    name: 'Done',
    taskCount: 2,
    tasks: [
      {
        id: 'task-6',
        title: 'Database schema design',
        description:
          'Design and implement the database schema for user management and content storage',
        status: 'Done',
        priority: 'High',
        assignee: {
          name: 'Mike Johnson',
          initials: 'MJ',
          color: '#F59E0B',
        },
        tags: ['Database', 'Backend'],
        startDate: new Date('2025-10-15'),
        endDate: new Date('2025-10-25'),
        attachments: ['schema.sql', 'er-diagram.png'],
        commentCount: 12,
        createdAt: new Date('2025-10-15'),
        checklist: [
          { id: '6-1', text: 'Analyze data requirements', completed: true },
          { id: '6-2', text: 'Design user tables', completed: true },
          { id: '6-3', text: 'Create content storage schema', completed: true },
          { id: '6-4', text: 'Add indexes for performance', completed: true },
          {
            id: '6-5',
            text: 'Set up foreign key constraints',
            completed: true,
          },
          { id: '6-6', text: 'Test database migrations', completed: true },
          { id: '6-7', text: 'Generate ER diagram', completed: true },
        ],
        activities: [
          {
            id: 'task-6-activity-1',
            user: 'Mike Johnson',
            action: 'created this task',
            date: '19 days ago',
          },
          {
            id: 'task-6-activity-2',
            user: 'David Brown',
            action: 'reviewed database requirements',
            date: '15 days ago',
          },
          {
            id: 'task-6-activity-3',
            user: 'Mike Johnson',
            action: 'completed schema design',
            date: '10 days ago',
          },
          {
            id: 'task-6-activity-4',
            user: 'John Doe',
            action: 'approved schema implementation',
            date: '9 days ago',
          },
        ],
      },
      {
        id: 'task-7',
        title: 'Project requirements gathering',
        status: 'Done',
        assignee: {
          name: 'Sarah Wilson',
          initials: 'SW',
          color: '#EF4444',
        },
        tags: ['Planning'],
        commentCount: 6,
        createdAt: new Date('2025-10-10'),
        checklist: [
          {
            id: '7-1',
            text: 'Conduct stakeholder interviews',
            completed: true,
          },
          {
            id: '7-2',
            text: 'Document functional requirements',
            completed: true,
          },
          {
            id: '7-3',
            text: 'Define technical specifications',
            completed: true,
          },
          { id: '7-4', text: 'Create user stories', completed: true },
          { id: '7-5', text: 'Set project timeline', completed: true },
          { id: '7-6', text: 'Get stakeholder approval', completed: true },
        ],
        activities: [
          {
            id: 'task-7-activity-1',
            user: 'Sarah Wilson',
            action: 'created this task',
            date: '24 days ago',
          },
          {
            id: 'task-7-activity-2',
            user: 'John Doe',
            action: 'added stakeholder feedback',
            date: '20 days ago',
          },
          {
            id: 'task-7-activity-3',
            user: 'Sarah Wilson',
            action: 'finalized requirements document',
            date: '15 days ago',
          },
        ],
      },
    ],
  },
];
