from pydantic_settings import BaseSettings 
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient
from constants import Constants
import os
from dotenv import load_dotenv

load_dotenv()  # Explicitly load .env file


class Settings(BaseSettings):
    ENTITY_DB_NAME: str = ""
    ENTITY_DB_USER: str = ""
    ENTITY_DB_PASSWORD: str = ""
    ENTITY_DB_HOST: str = ""
    KEY_VAULT_URI: str
    MAIN_DB_NAME: str = ""
    MAIN_DB_USER: str = ""
    MAIN_DB_PASSWORD: str = ""
    MAIN_DB_HOST: str = ""
    DB_PORT: str =""
    MAIN_DB_PORT: str =""
    TENANT_ID: str = ""
    CLIENT_ID: str = ""
    CLIENT_SECRET: str = ""
    EMAIL_FROM: str = ""
    class Config:
        env_file = ".env"
        env_file_encoding = 'utf-8'
        extra = 'ignore'

    def load_secrets_from_keyvault(self):
        credential = DefaultAzureCredential()
        client = SecretClient(vault_url=self.KEY_VAULT_URI, credential=credential)
        try:
            self.ENTITY_DB_NAME = client.get_secret(os.getenv("ORGDB_NAME")).value
            self.ENTITY_DB_USER = client.get_secret(os.getenv("ORGDB_USERNAME")).value
            self.ENTITY_DB_PASSWORD = client.get_secret(os.getenv("ORGDB_PASSWORD")).value
            self.ENTITY_DB_HOST = client.get_secret(os.getenv("ORGDB_ENDPOINT")).value
            self.MAIN_DB_NAME = client.get_secret(os.getenv("MAINDB_NAME")).value
            self.MAIN_DB_USER = client.get_secret(os.getenv("MAINDB_USERNAME")).value
            self.MAIN_DB_PASSWORD = client.get_secret(os.getenv("MAINDB_PASSWORD")).value
            self.MAIN_DB_HOST = client.get_secret(os.getenv("MAINDB_ENDPOINT")).value
            self.DB_PORT = 5432
            self.MAIN_DB_PORT = 5432
            self.TENANT_ID = client.get_secret(os.getenv("MAIL_TENANT_ID")).value
            self.CLIENT_ID = client.get_secret(os.getenv("MAIL_CLIENT_ID")).value
            self.CLIENT_SECRET = client.get_secret(os.getenv("MAIL_CLIENT_SECRET")).value
            self.EMAIL_FROM = client.get_secret(os.getenv("EMAIL_FROM")).value

        except Exception as e:
            print(f"[Key Vault] Failed to load secrets: {str(e)}")


# Load secrets
settings = Settings()
settings.load_secrets_from_keyvault()


class Config:
    # Spark
    SPARK_SHUFFLE_PARTITIONS = Constants.Spark.SHUFFLE_PARTITIONS

    # Kafka
    KAFKA_BROKER = Constants.Kafka.BROKER
    KAFKA_TOPIC_RESOURCE = Constants.Kafka.KAFKA_TOPIC_RESOURCE
    KAFKA_TOPIC_RESOURCE_COST = Constants.Kafka.KAFKA_TOPIC_RESOURCE_COST
    KAFKA_TOPIC_RESOURCE_SKILL = Constants.Kafka.KAFKA_TOPIC_RESOURCE_SKILL
    KAFKA_TOPIC_PROJECT = Constants.Kafka.KAFKA_TOPIC_PROJECT
    KAFKA_TOPIC_PROJECT_RESOURCE = Constants.Kafka.KAFKA_TOPIC_PROJECT_RESOURCE
    KAFKA_TOPIC_PROJECT_TASK = Constants.Kafka.KAFKA_TOPIC_PROJECT_TASK

    KAFKA_OUTPUT_TOPIC_RESOURCE = Constants.Kafka.KAFKA_OUTPUT_TOPIC_RESOURCE
    KAFKA_OUTPUT_TOPIC_RESOURCE_COST = Constants.Kafka.KAFKA_OUTPUT_TOPIC_RESOURCE_COST
    KAFKA_OUTPUT_TOPIC_RESOURCE_SKILL = Constants.Kafka.KAFKA_OUTPUT_TOPIC_RESOURCE_SKILL
    KAFKA_OUTPUT_TOPIC_PROJECT = Constants.Kafka.KAFKA_OUTPUT_TOPIC_PROJECT
    KAFKA_OUTPUT_TOPIC_PROJECT_RESOURCE = Constants.Kafka.KAFKA_OUTPUT_TOPIC_PROJECT_RESOURCE
    KAFKA_OUTPUT_TOPIC_PROJECT_TASK = Constants.Kafka.KAFKA_OUTPUT_TOPIC_PROJECT_TASK
    
    KAFKA_OUTPUT_TOPIC = Constants.Kafka.OUTPUT_TOPIC
    KAFKA_GROUP_ID = Constants.Kafka.GROUP_ID
    KAFKA_AUTO_OFFSET_RESET = Constants.Kafka.AUTO_OFFSET_RESET
    KAFKA_AI_REQUEST_TRIGGER_TOPIC = Constants.Kafka.KAFKA_AI_REQUEST_TRIGGER_TOPIC
    KAFKA_AI_RESPONSE_TRIGGER_TOPIC = Constants.Kafka.KAFKA_AI_RESPONSE_TRIGGER_TOPIC

    # DB Config
    ENTITY_DB_NAME = settings.ENTITY_DB_NAME
    ENTITY_DB_USER = settings.ENTITY_DB_USER
    ENTITY_DB_HOST = settings.ENTITY_DB_HOST
    ENTITY_DB_PASSWORD = settings.ENTITY_DB_PASSWORD
    ENTITY_DB_DRIVER = Constants.Database.DRIVER
    MAIN_DB_NAME = settings.MAIN_DB_NAME
    MAIN_DB_USER = settings.MAIN_DB_USER
    MAIN_DB_HOST = settings.MAIN_DB_HOST
    MAIN_DB_PASSWORD = settings.MAIN_DB_PASSWORD

    # SQLAlchemy-style URL
    # ENTITY_DB_URL = (
    #     f"postgresql://{settings.ENTITY_DB_USER}:{settings.ENTITY_DB_PASSWORD}"
    #     f"@{settings.ENTITY_DB_HOST}:5432/{settings.ENTITY_DB_NAME}"
    # )

    # JDBC-style URL (optional alternative)
    ENTITY_DB_URL = (
        f"jdbc:postgresql://{settings.ENTITY_DB_HOST}:5432/{settings.ENTITY_DB_NAME}"
        "?sslmode=require"
        "&loginTimeout=30"
        "&socketTimeout=60"
        "&tcpKeepAlive=true"
        "&keepalives=1"
        "&keepalives_idle=15"
        "&keepalives_interval=5"
        "&keepalives_count=5"
    )
    MAIN_DB_URL   = (
        f"jdbc:postgresql://{settings.MAIN_DB_HOST}:5432/{settings.MAIN_DB_NAME}"
        "?sslmode=require"
        "&loginTimeout=30"
        "&socketTimeout=60"
        "&tcpKeepAlive=true"
        "&keepalives=1"
        "&keepalives_idle=15"
        "&keepalives_interval=5"
        "&keepalives_count=5"
    )
    # Tables
    STAGING_RESOURCE_TABLE = Constants.Tables.STAGING_RESOURCE_TABLE
    STAGING_RESOURCE_SKILL_TABLE = Constants.Tables.STAGING_RESOURCE_SKILL_TABLE
    STAGING_RESOURCE_COST_TABLE = Constants.Tables.STAGING_RESOURCE_COST_TABLE
    STAGING_PROJECT_TABLE = Constants.Tables.STAGING_PROJECT_TABLE
    STAGING_PROJECT_RESOURCE_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_TABLE
    STAGING_PROJECT_TASK_TABLE = Constants.Tables.STAGING_PROJECT_TASK_TABLE

    HISTORY_RESOURCE_TABLE_STAGING = Constants.Tables.HISTORY_RESOURCE_TABLE_STAGING
    HISTORY_RESOURCE_SKILL_TABLE_STAGING = Constants.Tables.HISTORY_RESOURCE_SKILL_TABLE_STAGING
    HISTORY_RESOURCE_COST_TABLE_STAGING = Constants.Tables.HISTORY_RESOURCE_COST_TABLE_STAGING
    HISTORY_PROJECT_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_TABLE_STAGING
    HISTORY_PROJECT_TASK_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_TASK_TABLE_STAGING
    DOCUMENT_TABLE = Constants.Tables.DOCUMENT
    IMPORT_TABLE = Constants.Tables.IMPORT

    PROD_RESOURCE_TABLE = Constants.Tables.RESOURCE_TABLE
    PROD_RESOURCE_COST_TABLE = Constants.Tables.RESOURCE_COST_TABLE
    PROD_RESOURCE_SKILL_TABLE = Constants.Tables.RESOURCE_SKILL_TABLE
    PROD_RESOURCE_HISTORY_TABLE = Constants.Tables.RESOURCE_HISTORY
    PROD_RESOURCE_COST_HISTORY_TABLE = Constants.Tables.RESOURCE_COST_HISTORY
    PROD_RESOURCE_SKILL_HISTORY_TABLE = Constants.Tables.RESOURCE_SKILL_HISTORY

    PROD_RESOURCE_FISCAL_TABLE = Constants.Tables.RESOURCE_FISCAL
    PROD_PROJECT_FISCAL_TABLE = Constants.Tables.PROJECT_FISCAL

    PROD_PROJECT_TABLE = Constants.Tables.PROJECT_TABLE
    PROD_PROJECT_RESOURCE_TABLE = Constants.Tables.PROJECT_RESOURCE_TABLE
    PROD_PROJECT_TASK_TABLE = Constants.Tables.PROJECT_TASK_TABLE
    PROD_PROJECT_HISTORY_TABLE = Constants.Tables.PROJECT_HISTORY_TABLE
    PROD_PROJECT_RESOURCE_HISTORY_TABLE = Constants.Tables.PROJECT_RESOURCE_HISTORY_TABLE
    PROD_PROJECT_TASK_HISTORY_TABLE = Constants.Tables.PROJECT_TASK_HISTORY_TABLE
    PROD_PROJECT_RESOURCE_FISCAL_TABLE =Constants.Tables.PROJECT_RESOURCE_FISCAL
    PROD_RESOURCE_FISCAL_REGION_TABLE = Constants.Tables.RESOURCE_FISCAL_REGION
    PROD_PROJECT_FISCAL_REGION_TABLE = Constants.Tables.PROJECT_FISCAL_REGION
    PROD_PROJECT_RESOURCE_FISCAL_REGION_TABLE= Constants.Tables.PROJECT_RESOURCE_FISCAL_REGION

    RESOURCE_TIMELINE_TABLE = Constants.Tables.RESOURCE_TIMELINE
    RESOURCE_COST_TIMELINE_TABLE = Constants.Tables.RESOURCE_COST_TIMELINE
    RESOURCE_SKILL_TIMELINE_TABLE = Constants.Tables.RESOURCE_SKILL_TIMELINE
    PROJECT_TIMELINE_TABLE =Constants.Tables.PROJECT_TIMELINE
    PROJECT_RESOURCE_TIMELINE_TABLE =Constants.Tables.PROJECT_RESOURCE_TIMELINE
    PROJECT_TASK_TIMELINE_TABLE =Constants.Tables.PROJECT_TASK_TIMELINE
    ACCOUNT_FISCAL_REGION_TABLE = Constants.Tables.ACCOUNT_FISCAL_REGION
    ACCOUNT_FISCAL_TABLE = Constants.Tables.ACCOUNT_FISCAL
    ACCOUNT_FISCAL_SUMMARY_TABLE = Constants.Tables.ACCOUNT_FISCAL_SUMMARY
    ACCOUNT_TABLE = Constants.Tables.ACCOUNT
    KEY_CONTACTS_TABLE = Constants.Tables.KEY_CONTACTS
    KEY_CONTACTS_ROLE_TABLE = Constants.Tables.KEY_CONTACTS_ROLE
    PROJECT_CLASSIFICATION_TABLE = Constants.Tables.PROJECT_CLASSIFICATION
    PROJECT_SUMMARY_TABLE = Constants.Tables.PROJECT_SUMMARY
    PROJECT_FISCAL_SUMMARY_TABLE = Constants.Tables.PROJECT_FISCAL_SUMMARY
    PROJECT_INDUSTRY_TABLE = Constants.Tables.PROJECT_INDUSTRY
    SKILL_TYPE_TABLE = Constants.Tables.SKILL_TYPE
    SKILL_SUB_TYPE_TABLE = Constants.Tables.SKILL_SUB_TYPE
    CURRENCY_TABLE = Constants.Tables.CURRENCY
    CITY_TABLE = Constants.Tables.CITY
    STATE_TABLE = Constants.Tables.STATE
    COUNTRY_TABLE = Constants.Tables.COUNTRY
    KAFKA_EVENTS_TABLE = Constants.Tables.KAFKA_EVENTS
    SCHEMA_NAME = Constants.Database.SCHEMA_NAME
    STATUS_TABLE = Constants.Tables.STATUS_TABLE
    PROJECT_TYPE = Constants.Tables.PROJECT_TYPE_TABLE
    TASK_TYPE = Constants.Tables.TASK_TYPE_TABLE
    TASK_CLASSIFICATION = Constants.Tables.TASK_CLASSIFICATION_TABLE
    RESOURCE_TYPE = Constants.Tables.RESOURCE_TYPE_TABLE
    SKILL_LEVEL_TABLE = Constants.Tables.SKILL_LEVEL_TABLE
    ACCOUNT_DETAIL_TABLE = Constants.Tables.ACCOUNT_DETAIL_TABLE
    RESOURCE_STATUS_TABLE = Constants.Tables.RESOURCE_STATUS_TABLE
    CASE_STATUS_TABLE = Constants.Tables.CASE_STATUS_TABLE
    CASE_PROJECTS_TABLE = Constants.Tables.CASE_PROJECTS_TABLE
    CASES_TABLE = Constants.Tables.CASES_TABLE
    CASE_PROJECT_FISCAL_REGION_TABLE = Constants.Tables.CASE_PROJECT_FISCAL_REGION_TABLE
    CASE_PROJECT_RESOURCE_TABLE = Constants.Tables.CASE_PROJECT_RESOURCE_TABLE
    CASE_PROJECT_RESOURCE_FISCAL_TABLE = Constants.Tables.CASE_PROJECT_RESOURCE_FISCAL_TABLE
    CASE_PROJECT_TASK_TABLE = Constants.Tables.CASE_PROJECT_TASK_TABLE
    CASES_KEY_CONTACT_TABLE = Constants.Tables.CASES_KEY_CONTACT_TABLE
    EVENT_TYPE_TABLE = Constants.Tables.EVENT_TYPE_TABLE
    ACCOUNT_TIMELINE_TABLE = Constants.Tables.ACCOUNT_TIMELINE_TABLE
    ORG_LICENSES_TABLE = Constants.Tables.ORG_LICENSES_TABLE
    # App
    PRODUCED_MESSAGE = Constants.Messages.PRODUCED
    PROCESS_MESSAGE = Constants.Messages.PROCESS
    CONSUMER_MESSAGE_SUCCESS = Constants.Messages.SUCCESS
    CONSUMER_MESSAGE_PROCESS = Constants.Messages.PROCESS
    CONSUMER_MESSAGE_FAILURE = Constants.Messages.FAILURE
    POSTGRES_JDBC_JAR = Constants.Database.JDBC_JAR
    INVALID_UUID = Constants.Messages.INVALID_UUID
    RESOURCE_STATUS_ACTIVE = Constants.Messages.RESOURCE_STATUS_ACTIVE
    STATUS_MESG_FAILED = Constants.Messages.FAILURE
    STATUS_MESG_SUCCESS = Constants.Messages.SUCCESS

    #Threshold 
    RESOURCE_COST_SALARY = Constants.Threshold.RESOURCE_COST_SALARY
    RESOURCE_COST_HOURLY = Constants.Threshold.RESOURCE_COST_HOURLY
    RESOURCE_COST_TOTAL_COST = Constants.Threshold.RESOURCE_COST_TOTAL_COST

    WORKING_HOURS = Constants.Threshold.WORKING_HOURS

    AI_URL = os.getenv("AI_URL")
    
    # Mastek UK Constants
    INCLUSION_GL_CODES = Constants.Mastek_UK_Constants.INCLUSION_GL_CODES
    EXCLUSION_GL_CODES = Constants.Mastek_UK_Constants.EXCLUSION_GL_CODES
    INCLUSION_GL_TEXTS = Constants.Mastek_UK_Constants.INCLUSION_GL_TEXTS
    EXCLUSION_GL_TEXTS = Constants.Mastek_UK_Constants.EXCLUSION_GL_TEXTS

    #customisation
    STAGING_PROJECT_RESOURCE_SUBCON_TM_US_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_SUBCON_TM_US_TABLE
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_US_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_FULLTIME_TM_US_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_CA_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_SUBCON_TM_CA_TABLE
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_CA_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_FULLTIME_TM_CA_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_UK_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_SUBCON_TM_UK_TABLE
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_UK_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_FULLTIME_TM_UK_TABLE
    HISTORY_PROJECT_RESOURCE_SUBCON_TM_CA_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_SUBCON_TM_CA_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_FULLTIME_TM_CA_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_FULLTIME_TM_CA_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_SUBCON_TM_US_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_SUBCON_TM_US_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_FULLTIME_TM_US_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_FULLTIME_TM_US_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_SUBCON_TM_UK_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_SUBCON_TM_UK_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_FULLTIME_TM_UK_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_FULLTIME_TM_UK_TABLE_STAGING
    STAGING_PROJECT_TABLE_BR = Constants.Tables.STAGING_PROJECT_TABLE_BR
    STAGING_PROJECT_RESOURCE_TABLE_BR = Constants.Tables.STAGING_PROJECT_RESOURCE_TABLE_BR
    HISTORY_PROJECT_TABLE_BR_STAGING = Constants.Tables.HISTORY_PROJECT_TABLE_BR_STAGING
    HISTORY_PROJECT_RESOURCE_TABLE_BR_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_TABLE_BR_STAGING
    STAGING_RESOURCE_COST_TABLE_MASTEK_UK = Constants.Tables.STAGING_RESOURCE_COST_TABLE_MASTEK_UK
    HISTORY_RESOURCE_COST_TABLE_MASTEK_UK = Constants.Tables.HISTORY_RESOURCE_COST_TABLE_MASTEK_UK
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_IR_TABLE  = Constants.Tables.STAGING_PROJECT_RESOURCE_FULLTIME_TM_IR_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_IR_TABLE  = Constants.Tables.STAGING_PROJECT_RESOURCE_SUBCON_TM_IR_TABLE
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_AU_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_FULLTIME_TM_AU_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_AU_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_SUBCON_TM_AU_TABLE
    HISTORY_PROJECT_RESOURCE_SUBCON_TM_IR_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_SUBCON_TM_IR_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_FULLTIME_TM_IR_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_FULLTIME_TM_IR_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_SUBCON_TM_AU_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_SUBCON_TM_AU_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_FULLTIME_TM_AU_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_FULLTIME_TM_AU_TABLE_STAGING
    STAGING_PROJECT_RESOURCE_FULLTIME_TMTI_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_FULLTIME_TMTI_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TMTI_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_SUBCON_TMTI_TABLE
    HISTORY_PROJECT_RESOURCE_SUBCON_TMTI_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_SUBCON_TMTI_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_FULLTIME_TMTI_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_FULLTIME_TMTI_TABLE_STAGING
    STAGING_PROJECT_RESOURCE_FULLTIME_TM_ALLYIS_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_FULLTIME_TM_ALLYIS_TABLE
    STAGING_PROJECT_RESOURCE_SUBCON_TM_ALLYIS_TABLE = Constants.Tables.STAGING_PROJECT_RESOURCE_SUBCON_TM_ALLYIS_TABLE
    HISTORY_PROJECT_RESOURCE_SUBCON_TM_ALLYIS_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_SUBCON_TM_ALLYIS_TABLE_STAGING
    HISTORY_PROJECT_RESOURCE_FULLTIME_TM_ALLYIS_TABLE_STAGING = Constants.Tables.HISTORY_PROJECT_RESOURCE_FULLTIME_TM_ALLYIS_TABLE_STAGING
    CHECK_CUSTOMISATION_TABLE = Constants.Tables.CHECK_CUSTOMISATION_TABLE
    
config = Config()
