import {
  accountsIcon,
  attachmentIcon,
  caseIcon,
  dashboardIcon,
  helpIcon,
  notesIcon,
  projectsIcon,
  settingsIcon,
  surveyIcon,
  timesheetIcon,
} from '../../assets';
import { MenuOption } from '../../common-service';
import { INavItem } from '../../consultant/types';
import { ACCOUNT, MAIN_ROUTE, NOT_FOUND, PROJECT } from '../../routes';

export const accountNavItems: INavItem[] = [
  {
    id: MenuOption.DASHBOARD,
    icon: dashboardIcon,
    name: 'Dashboard',
    link: MAIN_ROUTE,
    type: 'link',
    matchLink: MAIN_ROUTE,
  },
  {
    id: MenuOption.ACCOUNTS,
    icon: accountsIcon,
    name: 'Accounts',
    link: ACCOUNT,
    type: 'link',
    matchLink: ACCOUNT,
  },
  {
    id: MenuOption.PROJECTS,
    icon: projectsIcon,
    name: 'Projects',
    link: PROJECT,
    type: 'link',
    matchLink: PROJECT,
  },
  {
    id: MenuOption.TIMESHEET,
    icon: timesheetIcon,
    name: 'Timeline',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  {
    id: MenuOption.CASES,
    icon: caseIcon,
    name: 'Cases',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  {
    id: MenuOption.SURVEY,
    icon: surveyIcon,
    name: 'Survey',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  {
    id: MenuOption.NOTES,
    icon: notesIcon,
    name: 'Notes',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  {
    id: MenuOption.ATTACHMENTS,
    icon: attachmentIcon,
    name: 'Attachments',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  {
    id: '',
    icon: '',
    name: '',
    link: '',
    type: 'divider',
    matchLink: '',
  },
  {
    id: MenuOption.HELP,
    icon: helpIcon,
    name: 'Help',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  {
    id: MenuOption.SETTINGS,
    icon: settingsIcon,
    name: 'Settings',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  // {
  //   icon: logoutIcon,
  //   name: 'Logout',
  //   link: MAIN_ROUTE,
  //   type: 'link',
  //   matchLink: '',
  // },
];
