import {
  AccountsIcon,
  AttachmentIcon,
  DashboardIcon,
  HelpIcon,
  NotesIcon,
  ProjectsIcon,
  SettingsIcon,
  TimeLineIcon,
} from '../../assets';
import { MenuOption } from '../../common-service';
import { INavItem } from '../../consultant/types';
import {
  ACCOUNT,
  ATTACHMENTS,
  MAIN_ROUTE,
  NOT_FOUND,
  NOTES,
  PROJECT,
} from '../../routes';

export const accountNavItems: INavItem[] = [
  {
    id: MenuOption.DASHBOARD,
    icon: DashboardIcon,
    name: 'Dashboard',
    link: MAIN_ROUTE,
    type: 'link',
    matchLink: MAIN_ROUTE,
    noRedirect: true,
    activePath: 'dashboard',
  },
  {
    id: MenuOption.ACCOUNTS,
    icon: AccountsIcon,
    name: 'Accounts',
    link: ACCOUNT,
    type: 'link',
    matchLink: ACCOUNT,
    activePath: 'account',
  },
  {
    id: MenuOption.PROJECTS,
    icon: ProjectsIcon,
    name: 'Projects',
    link: PROJECT,
    type: 'link',
    matchLink: PROJECT,
    activePath: 'project',
  },
  {
    id: MenuOption.TIMESHEET,
    icon: TimeLineIcon,
    name: 'Timeline',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  // {
  //   id: MenuOption.CASES,
  //   icon: CaseIcon,
  //   name: 'Cases',
  //   link: CASE,
  //   type: 'link',
  //   matchLink: CASE,
  // },
  // Global Interactions removed as of now will be added in future if required
  // {
  //   id: MenuOption.INTERACTIONS,
  //   icon: InteractionDetailIcon,
  //   name: 'Interactions',
  //   link: INTERACTIONS,
  //   type: 'link',
  //   matchLink: INTERACTIONS,
  // },
  {
    id: MenuOption.NOTES,
    icon: NotesIcon,
    name: 'Notes',
    link: NOTES,
    type: 'link',
    matchLink: NOTES,
    activePath: 'notes',
  },
  {
    id: MenuOption.ATTACHMENTS,
    icon: AttachmentIcon,
    name: 'Attachments',
    link: ATTACHMENTS,
    type: 'link',
    matchLink: ATTACHMENTS,
    activePath: 'attachments',
  },
  {
    id: '',
    icon: '',
    name: '',
    link: '',
    type: 'divider',
    matchLink: '',
  },
  {
    id: MenuOption.HELP,
    icon: HelpIcon,
    name: 'Help',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  {
    id: MenuOption.SETTINGS,
    icon: SettingsIcon,
    name: 'Settings',
    link: NOT_FOUND,
    type: 'link',
    matchLink: '',
  },
  // {
  //   icon: logoutIcon,
  //   name: 'Logout',
  //   link: MAIN_ROUTE,
  //   type: 'link',
  //   matchLink: '',
  // },
];
