import {
  AdminPermissionIcon,
  AdminTemplateIcon,
  ChecklistTemplateIcon,
  ConfigureSettingIcon,
  EmailTemplateIcon,
  ImportTemplateIcon,
  InteractionTemplateIcon,
  ManageRule,
  ManageGroupIcon,
  ManageProfileIcon,
  ManagerUserIcon,
  ManageSettingsIcon,
  ManageUserAccessIcon,
  TaskTemplateIcon,
  WorkflowIcon,
  SettingsIcon,
} from '../../assets';
import { MenuOption } from '../../common-service';
import { AdminNavItem } from '../../consultant/types';
import {
  ADMIN_MANAGE_USER,
  CHECKLIST_TEMPLATES,
  EMAIL_TEMPLATES,
  IMPORT_TEMPLATES,
  INTERACTION_TEMPLATES,
  MANAGE_ACCOUNT_ACCESS,
  MANAGE_GEO_BASED_RULE,
  MANAGE_PROFILE,
  MANAGE_SETTINGS,
  MANAGE_USER_GROUP,
  DATA_MAPPER,
  TASK_TEMPLATES,
  WORKFLOW_BUILDER,
} from '../../routes';

export const sideNavAdminItems: AdminNavItem[] = [
  {
    title: 'Admin Permission',
    icon: AdminPermissionIcon,
    openStatus: false,
    subItemTitle: [
      {
        id: MenuOption.MANAGE_USER,
        name: 'Manage User',
        icon: ManagerUserIcon,
        link: ADMIN_MANAGE_USER,
        matchLink: ADMIN_MANAGE_USER,
      },
      {
        id: MenuOption.MANAGE_PROFILE,
        name: 'Manage Profile',
        icon: ManageProfileIcon,
        link: MANAGE_PROFILE,
        matchLink: MANAGE_PROFILE,
      },
      {
        id: MenuOption.MANAGE_USER_GROUP,
        name: 'Manage User Group',
        icon: ManageGroupIcon,
        link: MANAGE_USER_GROUP,
        matchLink: MANAGE_USER_GROUP,
      },
      {
        id: MenuOption.MANAGE_ACCOUNT_ACCESS,
        name: 'Manage Account Access',
        icon: ManageUserAccessIcon,
        link: MANAGE_ACCOUNT_ACCESS,
        matchLink: MANAGE_ACCOUNT_ACCESS,
      },
    ],
  },
  {
    title: 'Configure Settings',
    icon: ConfigureSettingIcon,
    openStatus: false,
    subItemTitle: [
      {
        id: MenuOption.MANAGE_SETTINGS,
        name: 'Manage Settings',
        icon: ManageSettingsIcon,
        link: MANAGE_SETTINGS,
        matchLink: MANAGE_SETTINGS,
      },
      {
        id: MenuOption.MANAGE_GEO_BASED_RULE,
        name: 'Manage Jurisdiction Rules',
        icon: ManageRule,
        link: MANAGE_GEO_BASED_RULE,
        matchLink: MANAGE_GEO_BASED_RULE,
      },
      {
        id: MenuOption.WORKFLOW_BUILDER,
        name: 'Workflow Builder',
        icon: WorkflowIcon,
        link: WORKFLOW_BUILDER,
        matchLink: WORKFLOW_BUILDER,
      },
      {
        id: MenuOption.DATA_MAPPER,
        name: 'RD Form data mapper',
        icon: SettingsIcon,
        link: DATA_MAPPER,
        matchLink: DATA_MAPPER,
      },
    ],
  },
  {
    title: 'Admin Template',
    icon: AdminTemplateIcon,
    openStatus: false,
    subItemTitle: [
      {
        id: MenuOption.IMPORT_TEMPLATE,
        name: 'Import templates',
        icon: ImportTemplateIcon,
        link: IMPORT_TEMPLATES,
        matchLink: IMPORT_TEMPLATES,
      },
      {
        id: MenuOption.INTERACTION_TEMPLATE,
        name: 'Interaction templates',
        icon: InteractionTemplateIcon,
        link: INTERACTION_TEMPLATES,
        matchLink: INTERACTION_TEMPLATES,
      },
      {
        id: MenuOption.EMAIL_TEMPLATE,
        name: 'Email templates',
        icon: EmailTemplateIcon,
        link: EMAIL_TEMPLATES,
        matchLink: EMAIL_TEMPLATES,
      },
      // Commented for it may use in future
      // {
      //   id: MenuOption.SURVEY_TEMPLATE,
      //   name: 'Survey templates',
      //   icon: SurveyTemplateIcon,
      //   link: SURVEY_TEMPLATES,
      //   matchLink: SURVEY_TEMPLATES,
      // },
      {
        id: MenuOption.TASK_TEMPLATE,
        name: 'Task templates',
        icon: TaskTemplateIcon,
        link: TASK_TEMPLATES,
        matchLink: TASK_TEMPLATES,
      },
      {
        id: MenuOption.CHECKLIST_TEMPLATE,
        name: 'Checklist templates',
        icon: ChecklistTemplateIcon,
        link: CHECKLIST_TEMPLATES,
        matchLink: CHECKLIST_TEMPLATES,
      },
    ],
  },
];
