import { ManageUser } from '../types/manage-user';

export const ManageUserMockData: ManageUser[] = [
  {
    id: '1',
    username: 'john_doe',
    fullName: 'John Doe',
    email: 'johndoe@gmail.com',
    profile: 'Software Engineer',
    status: 'Active',
  },
  {
    id: '2',
    username: 'jane_smith',
    fullName: 'Jane Smith',
    email: 'janesmith@gmail.com',
    profile: 'Product Manager',
    status: 'Active',
  },
  {
    id: '3',
    username: 'michael_brown',
    fullName: 'Michael Brown',
    email: 'michaelb@gmail.com',
    profile: 'Data Analyst',
    status: 'Active',
  },
  {
    id: '4',
    username: 'emily_jones',
    fullName: 'Emily Jones',
    email: 'emilyjones@gmail.com',
    profile: 'Graphic Designer',
    status: 'Active',
  },
  {
    id: '5',
    username: 'david_wilson',
    fullName: 'David Wilson',
    email: 'davidw@gmail.com',
    profile: 'Marketing Specialist',
    status: 'Active',
  },
  {
    id: '6',
    username: 'sarah_miller',
    fullName: 'Sarah Miller',
    email: 'sarahmiller@gmail.com',
    profile: 'HR Coordinator',
    status: 'Active',
  },
  {
    id: '7',
    username: 'chris_lee',
    fullName: 'Chris Lee',
    email: 'chrislee@gmail.com',
    profile: 'Web Developer',
    status: 'Active',
  },
  {
    id: '8',
    username: 'laura_adams',
    fullName: 'Laura Adams',
    email: 'lauraadams@gmail.com',
    profile: 'Content Writer',
    status: 'Active',
  },
];
