import { RuleDetailsResponse } from '../types';

export const RuleDetailsMockData: RuleDetailsResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: 'Operation completed successfully!',
  data: {
    rule: {
      rid: 'D001-ec02dad8-a8f5-4f99-a768-c7e884f76ea8',
      r_number: null,
      eid: null,
      rule_name: 'First Rule Check',
      description: '',
      event_rid: 't1',
      trigger_type: 1,
      condition_rid: 'ec1',
      is_active: true,
      scope_type_rid: 'D001-00016d03-1684-48d1-a247-64a5139daef6',
      schedule_offset_type: null,
      schedule_offset_value: null,
      created_by: 'test',
      modified_by: 'test',
      created_datetime: '2025-12-11T08:26:19.956Z',
      modified_datetime: '2025-12-11T08:26:19.956Z',
    },
    event: {
      event_rid: 't1',
      event_name: 'task created',
      description: 'creating the task',
    },
    condition: {
      condition_rid: 'ec1',
      condition_name: 'if(Add a condition)',
      description: 'used to check condition',
      condition_type: 'IF',
    },
    conditions: [
      {
        category_rid: 'cc1',
        category_name: 'status',
        category_description: 'based on status',
        category_operator: null,
        field_rid: 'd999883r4',
        field_name: 'task.status',
        operator_rid: 'op1',
        operator_name: 'equals',
        value_rid: 'v1',
        value_name: 'open',
      },
      {
        category_rid: 'cc2',
        category_name: 'validation',
        category_description: 'based on validation',
        category_operator: 'AND',
        field_rid: 'd999883r5',
        field_name: 'task.overdue',
        operator_rid: 'op2',
        operator_name: 'equals',
        value_rid: 'v2',
        value_name: 'close',
      },
    ],
    actions: [
      {
        action_rid: 'sa1',
        action_name: 'create task',
        description: 'create a new task',
      },
      {
        action_rid: 'sa2',
        action_name: 'Assign task',
        description: 'assign a new task',
      },
    ],
  },
};
