import { ProjectAccordionResponse } from './types';

export const ManageProjectsMockData: ProjectAccordionResponse = {
  statusCode: 200,
  statusCodeValue: 'Success',
  statusMessage: '',
  data: {
    projects: [
      {
        project_code: 'PRC460',
        project_name: null,
        account_name: 'acc-123',
        account_id: '139de5b6-2489-461e-a381-26109a21885c',
        project_rid: '8087694d-b28a-40db-a871-39479243e61e',
        modified_datetime: '2025-06-16T09:26:03.234Z',
        assessment_status: null,
        qre: null,
        is_rd_qualified: false,
        industry_name_other: null,
        project_type: 'Fixed',
        project_client_group: null,
        project_group: null,
        project_classification_rid: null,
        classification_name: null,
        project_status: 'Active',
        project_point_of_contact: null,
        technical_point_of_contact: null,
        r_number: 'PRS 0000000109',
        program_name: null,
        project_startdate: null,
        project_enddate: null,
        total_cost: null,
        total_effort: null,
        total_fte: null,
        total_cost_fte: null,
        total_subcon: null,
        total_cost_subcon: null,
        total_cost_nonlabor: null,
        comments: null,
        country_name: null,
        currency_code: 'USD',
        currency_symbol: '$',
        region_name: null,
        created_datetime: '2025-06-16T09:26:03.234Z',
        project_fiscal_summary: [
          {
            project_code: 'PRC460',
            project_group: null,
            project_name: null,
            project_type: 'Fixed',
            fiscal_year: 2024,
            project_client_group: null,
            account_name: 'acc-123',
            qre: null,
            classification_name: null,
            total_effort: null,
            total_cost: null,
            total_cost_fte: null,
            total_cost_subcon: null,
            total_cost_nonlabor: null,
            assessment_status: null,
            qre_final: null,
            project_point_of_contact: null,
            technical_point_of_contact: null,
            comments: null,
            modified_datetime: '2025-06-16T09:26:03.272+00:00',
            project_rid: '8087694d-b28a-40db-a871-39479243e61e',
            created_datetime: '2025-06-16T09:26:03.272+00:00',
            rid: '8087694d-b28a-40db-a871-39479243e61s',
          },
        ],
      },
    ],
    count: 1,
  },
};
