import { gql } from '@apollo/client';

export const UPDATE_PROJECT = gql`
  mutation UpdateSpecificProjectDetails($data: updateInlineProject!) {
    updateSpecificProjectDetails(data: $data) {
      statusCode
      statusCodeValue
      statusMessage
      data {
        rid
        r_number
        eid
        created_datetime
        modified_datetime
        created_by
        modified_by
        project_code
        industry_rid
        industry_name
        account_rid
        program_name
        project_name
        project_startdate
        project_enddate
        project_type_rid
        project_classification_rid
        project_classification_other
        project_client_group
        project_group
        status_rid
        country_rid
        region_rid
        currency_rid
        comments
        project_description
        assessment_status
        total_fte
        total_subcon
        total_effort
        total_cost
        total_effort_fte
        total_effort_subcon
        total_cost_fte
        total_cost_subcon
        total_cost_nonlabor
        auto_send_ai_interaction
        auto_access_rd
        max_ai_interaction
        blended_rate_fte
        blended_rate_subcon
        blended_rate
        is_rd_qualified
        qre
        project_rid
        technical_point_of_contact
        financial_consultant
        project_point_of_contact
        currency_code
        currency_symbol
        classification_name
        is_other_classification
        project_type_name
        status_name
        ProjectFiscal {
          rid
          project_fiscal_rid
          classification_name
          r_number
          eid
          created_by
          modified_by
          created_datetime
          modified_datetime
          currency_symbol
          project_rid
          project_code
          industry_rid
          industry_name
          fiscal_year
          project_name
          program_name
          project_type_rid
          project_classification_rid
          project_classification_other
          project_client_group
          project_group
          auto_send_ai_interaction
          account_rid
          country_rid
          region_rid
          currency_rid
          max_ai_interaction
          expiry_duration
          auto_access_rd
          status_rid
          project_startdate
          project_enddate
          total_fte_prj
          total_fte_from_prj_res
          total_fte_from_tasks
          total_subcon_prj
          total_subcon_from_prj_res
          total_subcon_from_tasks
          total_nonlabor_prj
          total_nonlabor_from_prj_res
          total_resources_prj
          total_resources_from_prj_res
          total_resources_from_tasks
          total_effort_prj
          total_effort_fte_prj
          total_effort_subcon_prj
          total_effort_from_prj_res
          total_effort_fte_from_prj_res
          total_effort_subcon_from_prj_res
          total_effort_from_tasks
          total_effort_fte_from_tasks
          total_effort_subcon_from_tasks
          total_cost_prj
          total_cost_fte_prj
          total_cost_subcon_prj
          total_cost_nonlabor_prj
          total_cost_from_prj_res
          total_cost_fte_from_prj_res
          total_cost_subcon_from_prj_res
          total_cost_nonlabor_from_prj_res
          total_cost_from_tasks
          total_cost_fte_from_tasks
          total_cost_subcon_from_tasks
          total_cost_prj_blended
          qre_final
          total_cost_fte_prj_blended
          total_cost_subcon_prj_blended
          total_cost_from_prj_res_blended
          total_cost_fte_from_prj_res_blended
          total_cost_subcon_from_prj_res_blended
          total_cost_from_tasks_blended
          total_cost_fte_from_tasks_blended
          total_cost_subcon_from_tasks_blended
          blended_rate_fte
          blended_rate_subcon
          rd_percent_potential_ai
          rd_percent_adjustment
          rd_percent_final
          qre_fte
          qre_subcon
          qre_nonlabor
          rd_credits_fte_fed_level
          rd_credits_subcon_fed_level
          rd_credits_nonlabor_fed_level
          rd_credits_fed_level
          rd_credits_total
          interaction_cc_list
          assessment_status
          claim_status
          comments
          project_description
          total_fte
          total_effort
          total_cost
          total_cost_fte
          total_cost_subcon
          total_cost_nonlabor
          project_type_name
        }
      }
    }
  }
`;

export const UPDATE_PROJECT_RESOURCE = gql`
  mutation UpdateProjectResource($data: updateInlineProjectResource!) {
    updateProjectResource(data: $data) {
      statusCode
      statusCodeValue
      statusMessage
      data {
        rid
        r_number
        eid
        created_by
        modified_by
        created_datetime
        modified_datetime
        account_rid
        project_rid
        resource_rid
        project_resource_code
        fiscal_year
        start_date
        end_date
        resource_code
        resource_name
        resource_type_rid
        designation
        resource_role
        assigned_skill_role_type_rid
        total_hours_pro_res
        total_cost_pro_res
        status_rid
        country_rid
        region_rid
        currency_rid
        resource_orgname
        effort_project_resource_level
        cost_project_resource_level
        qre_final
        qre_percent
        salary
        bonus
        insurance
        deductions
        description
        country_name
        country_code
        region_name
        currency_name
        currency_symbol
        created_name
        modified_name
        status_name
        resource_type_name
        assigned_skill_role
        project_fiscal_rid
        status_rid
        status_name
        project_resource_role
      }
    }
  }
`;

export const UPDATE_PROJECT_TASK = gql`
  mutation UpdateProjectTask($data: updateInlineProjectTask!) {
    updateProjectTask(data: $data) {
      statusCode
      statusCodeValue
      statusMessage
      data {
        r_number
        account_rid
        account_name
        project_rid
        project_fiscal_rid
        project_name
        project_code
        project_resource_rid
        resource_rid
        resource_code
        fiscal_year
        start_date
        end_date
        resource_name
        resource_type_rid
        resource_type_name
        designation
        project_resource_role
        status_rid
        country_rid
        country_name
        region_rid
        region_name
        currency_rid
        resource_orgname
        total_cost_pro_task
        total_hours_pro_task
        description
        comments
        created_datetime
        modified_datetime
        created_by
        modified_by
        rid
        status_rid
        status_name
      }
    }
  }
`;

export const UPDATE_QRE_ADJUSTMENT = gql`
  mutation UpdateQreAdjustment($data: QreAdjustmentInput!) {
    updateQreAdjustment(data: $data) {
      statusCode
      statusCodeValue
      statusMessage
      data {
        rid
        r_number
        eid
        created_datetime
        modified_datetime
        created_by
        modified_by
        project_code
        rd_percent_potential_ai
        rd_percent_adjustment
        rd_percent_final
        qre_fte
        qre_subcon
        qre_nonlabor
        qre_final
      }
    }
  }
`;
